### ISSUE TITLE
Concourse binary - runtime error: index out of range

### ISSUE THREAD

**Issue by gbmeuk** [concourse/concourse#1018]
Hi,

I've recently been trying to build my own Docker image including the Concourse binary. We want to do this because we include because we like to run our containers in a [self-orchestrating](http://autopilotpattern.io) manner, so build from our own base images. However, I've found that the concourse binary fails to run when running in a build Docker image. The odd part is that it does run when running each of the build steps manually.

The error we receive is:
```
exec su concourse-web -s /usr/local/bin/concourse -- web --basic-auth-username concourse --basic-auth-password ci --session-signing-key /web/session_signing_key --tsa-host-key /web/tsa_key --tsa-authorized-keys /web/authorized_worker_keys --postgres-data-source postgres://concourse:ci@localhost/concourse
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0xd3b1c0, 0xc4200120a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
reflect.(*rtype).In(0xcd6480, 0x0, 0x193, 0xf242f20)
	/usr/local/go/src/reflect/type.go:982 +0x8e
github.com/concourse/bin/vendor/github.com/jessevdk/go-flags.(*Option).call(0xc42024e680, 0xc420247320, 0x193, 0xf242f20)
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/jessevdk/go-flags/option.go:359 +0xa3
github.com/concourse/bin/vendor/github.com/jessevdk/go-flags.(*Option).set(0xc42024e680, 0xc420247320, 0xc420010092, 0x5)
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/jessevdk/go-flags/option.go:213 +0x279
github.com/concourse/bin/vendor/github.com/jessevdk/go-flags.(*Option).clearDefault(0xc42024e680)
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/jessevdk/go-flags/option.go:269 +0xc1
github.com/concourse/bin/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs.func2(0xc420099880, 0xc420090360, 0xc42024e680)
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/jessevdk/go-flags/parser.go:298 +0x36
github.com/concourse/bin/vendor/github.com/jessevdk/go-flags.(*Command).eachOption.func1.1(0xc420090360)
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/jessevdk/go-flags/command.go:257 +0x70
github.com/concourse/bin/vendor/github.com/jessevdk/go-flags.(*Group).eachGroup(0xc420090360, 0xc420247438)
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/jessevdk/go-flags/group.go:170 +0x34
github.com/concourse/bin/vendor/github.com/jessevdk/go-flags.(*Group).eachGroup(0xc4200902d0, 0xc420247438)
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/jessevdk/go-flags/group.go:173 +0x6d
github.com/concourse/bin/vendor/github.com/jessevdk/go-flags.(*Command).eachOption.func1(0xc420099880)
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/jessevdk/go-flags/command.go:259 +0x5b
github.com/concourse/bin/vendor/github.com/jessevdk/go-flags.(*Command).eachCommand(0xc420099880, 0xc4202474b8, 0xffffffffffffff01)
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/jessevdk/go-flags/command.go:264 +0x34
github.com/concourse/bin/vendor/github.com/jessevdk/go-flags.(*Command).eachOption(0xc420099880, 0xec65148)
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/jessevdk/go-flags/command.go:260 +0x59
github.com/concourse/bin/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc420097080, 0xc420088010, 0xd, 0xd, 0xc420247678, 0x59f1cf, 0xc420097080, 0xe5954d, 0xa)
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/jessevdk/go-flags/parser.go:299 +0x994
github.com/concourse/bin/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc420097080, 0xe5954d, 0xa, 0x0, 0x0, 0x0)
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/vendor/github.com/jessevdk/go-flags/parser.go:185 +0x74
main.main()
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/cmd/concourse/main.go:29 +0x113
root@c327ed843ee2:/#
```

`/tmp/build` initially looks odd but it's not clear to me why, when I'm only downloading the binary why build would even be an issue.  The Dockerfile is:

```
$cat Dockerfile 
FROM ubuntu
MAINTAINER gbmeuk <gareth@mesoform.com>
LABEL description="Concourse CICD pipeline for Mesoform running by Concierge Paradigm"
LABEL com.mesoform.baseimage="False"
LABEL com.joyent.autopilotpattern="True"
LABEL com.mesoform.builddate="2017-04-08T14:57:31Z"
LABEL com.mesoform.baseimage.ver="mesoform/alpine-autopilot-base:onbuild-0.4.2"
LABEL com.docker.img.ver="mesoform/concourse:concierge-0.2.0"

# Set some environment variables
ENV DOCKER_IMG_VER="mesoform/concourse:concierge-0.2.0" \
    DNS_DOMAIN="concourse.dockerlx.oaas.mesoform.com" \
    CONSUL_AGENT=True \
    CONCOURSE_VERSION="2.7.0" \
    CONCOURSE_WORK_DIR="/worker-state" \
    CONCOURSE_TSA_WORKER_PRIVATE_KEY="/concourse-keys/" \
    CONCOURSE_TSA_PUBLIC_KEY="/concourse-keys/tsa_host_key.pub" \
    CONCOURSE_SESSION_SIGNING_KEY="/concourse-keys/session_signing_key" \
    CONCOURSE_TSA_AUTHORIZED_KEYS="/concourse-keys/authorized_worker_keys" \
    CONCOURSE_TSA_HOST_KEY="/concourse-keys/tsa_host_key" \
    CONCOURSE="/var/lib/concourse" \
    CONCOURSE_WEB="$CONCOURSE/web" \
    CONCOURSE_WORK="$CONCOURSE/worker" \
    CONCOURSE_KEYS="$CONCOURSE/keys"

VOLUME [$CONCOURSE_WORK]
CMD ["/bin/bash"]

# add packages needed for Concourse
RUN apt-get update && apt-get -y install iproute2 ca-certificates curl

RUN mkdir -p /run/systemd && echo 'docker' > /run/systemd/container && \
    sed -i 's/^#\s*\(deb.*universe\)$/\1/g' /etc/apt/sources.list && \
    rm -rf /var/lib/apt/lists/* && \
    useradd -d "$CONCOURSE_WEB" -s /bin/false -m -U concourse-web

RUN set -xe   && \
    echo '#!/bin/sh' > /usr/sbin/policy-rc.d  && \
    echo 'exit 101' >> /usr/sbin/policy-rc.d  && \
    chmod +x /usr/sbin/policy-rc.d   && \
    dpkg-divert --local --rename --add /sbin/initctl  && \
    cp -a /usr/sbin/policy-rc.d /sbin/initctl  && \
    sed -i 's/^exit.*/exit 0/' /sbin/initctl  && \
    echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/docker-apt-speedup   && \
    echo 'DPkg::Post-Invoke { "rm -f /var/cache/apt/archives/*.deb \
        /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true"; }; \
    ' > /etc/apt/apt.conf.d/docker-clean  && \
    echo 'APT::Update::Post-Invoke \
        { "rm -f /var/cache/apt/archives/*.deb \
    /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true"; };' \
        >> /etc/apt/apt.conf.d/docker-clean  && \
    echo 'Dir::Cache::pkgcache ""; Dir::Cache::srcpkgcache "";' \
        >> /etc/apt/apt.conf.d/docker-clean   && \
    echo 'Acquire::Languages "none";' > /etc/apt/apt.conf.d/docker-no-languages   && \
    echo 'Acquire::GzipIndexes "true"; \
        Acquire::CompressionTypes::Order:: "gz";' \
        > /etc/apt/apt.conf.d/docker-gzip-indexes   && \
    echo 'Apt::AutoRemove::SuggestsImportant "false";' \
        > /etc/apt/apt.conf.d/docker-autoremove-suggests && \
    curl -Lso /usr/local/bin/concourse \
       https://github.com/concourse/concourse/releases/download/v2.7.0/concourse_linux_amd64 && \
    chmod +x /usr/local/bin/concourse && \
    curl -L https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 \
        -o /usr/local/bin/dumb-init && \
    chmod +x /usr/local/bin/dumb-init


COPY bin /usr/local/bin/
EXPOSE 8080
```

This Dockerfile is not the one we want to use but tries to replicate all (although I understand some are unnecessary) the steps shown when running `docker history` on the [concourse/concourse](https://hub.docker.com/r/concourse/concourse/).

The environment then looks as such:
```
root@560e488744af:/# env
CONCOURSE_KEYS=/keys
HOSTNAME=560e488744af
TERM=xterm
CONCOURSE_TSA_WORKER_PRIVATE_KEY=/concourse-keys/
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
CONCOURSE_WEB=/web
DNS_DOMAIN=concourse.dockerlx.oaas.mesoform.com
CONCOURSE_TSA_AUTHORIZED_KEYS=/concourse-keys/authorized_worker_keys
CONCOURSE_SESSION_SIGNING_KEY=/concourse-keys/session_signing_key
CONCOURSE=/var/lib/concourse
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CONCOURSE_TSA_HOST_KEY=/concourse-keys/tsa_host_key
PWD=/
CONCOURSE_VERSION=2.7.0
CONCOURSE_WORK=/worker
DOCKER_IMG_VER=mesoform/concourse:concierge-0.2.0
SHLVL=1
HOME=/root
CONCOURSE_WORK_DIR=/worker-state
no_proxy=*.local, 169.254/16
CONCOURSE_TSA_PUBLIC_KEY=/concourse-keys/tsa_host_key.pub
CONSUL_AGENT=True
_=/usr/bin/env
root@560e488744af:/#
```

**Comment by clarafu** [comment]
What seems to be causing that error is that you set `CONCOURSE_VERSION` as an environment variable. We automatically have every flag map to an env var, so that ends up being passed as the value for `--version`. The go-flags package doesn't handle this case very well; it gets the value of the env var and tries to call the function with it, even though the function has no arguments. Try removing or renaming that var and running it again.
