### ISSUE TITLE
problem with installing groundcrew process during bosh-init deploy

### ISSUE THREAD

**Issue by codeword** [concourse/concourse#168]
seems like a tempate issue:
```
[main] 2015/10/15 12:02:25 ERROR - Command 'deploy' failed: Deploying: Building state for instance 'concourse/0': Rendering job templates for instance 'concourse/0': Rendering templates for job 'groundcrew/NTE3ZWVlMmE3ZmQyOWY0NDc0MzQ1OTAwOWRiYzJjYzlmZWQyMTRkNA==': Rendering template src: jettison_ctl.erb, dst: bin/jettison_ctl: Rendering template src: /Users/pivotal/.bosh_init/installations/d13b9d50-92a8-45ca-5458-cc4af9bc6eec/tmp/bosh-init-release738435729/extracted_jobs/groundcrew/templates/jettison_ctl.erb, dst: /Users/pivotal/.bosh_init/installations/d13b9d50-92a8-45ca-5458-cc4af9bc6eec/tmp/rendered-jobs147420449/bin/jettison_ctl: Running ruby to render templates: Running command: 'ruby /Users/pivotal/.bosh_init/installations/d13b9d50-92a8-45ca-5458-cc4af9bc6eec/tmp/erb-renderer355255582/erb-render.rb /Users/pivotal/.bosh_init/installations/d13b9d50-92a8-45ca-5458-cc4af9bc6eec/tmp/erb-renderer355255582/erb-context.json /Users/pivotal/.bosh_init/installations/d13b9d50-92a8-45ca-5458-cc4af9bc6eec/tmp/bosh-init-release738435729/extracted_jobs/groundcrew/templates/jettison_ctl.erb /Users/pivotal/.bosh_init/installations/d13b9d50-92a8-45ca-5458-cc4af9bc6eec/tmp/rendered-jobs147420449/bin/jettison_ctl', stdout: '', stderr: '/Users/pivotal/.bosh_init/installations/d13b9d50-92a8-45ca-5458-cc4af9bc6eec/tmp/erb-renderer355255582/erb-render.rb:180:in `rescue in render': Error filling in template '/Users/pivotal/.bosh_init/installations/d13b9d50-92a8-45ca-5458-cc4af9bc6eec/tmp/bosh-init-release738435729/extracted_jobs/groundcrew/templates/jettison_ctl.erb' for groundcrew/0 (line 62: #<NoMethodError: undefined method `esc' for #<TemplateEvaluationContext:0x007fdf3893acf0>>) (RuntimeError)
	from /Users/pivotal/.bosh_init/installations/d13b9d50-92a8-45ca-5458-cc4af9bc6eec/tmp/erb-renderer355255582/erb-render.rb:166:in `render'
	from /Users/pivotal/.bosh_init/installations/d13b9d50-92a8-45ca-5458-cc4af9bc6eec/tmp/erb-renderer355255582/erb-render.rb:191:in `<main>'
': exit status 1```

**Comment by codeword** [comment]
I was using 0.65.0 where this was a known problem  seems to be fixed in 0.65.1
