### ISSUE TITLE
`concourse-lite.yml` with v3.7.0 does not deploy

### ISSUE THREAD

**Issue by jtarchie** [concourse/concourse#1870]
# Bug Report

It does not work!

It looks like the `link` added for [known_hosts](https://github.com/concourse/concourse/blob/master/jobs/groundcrew/templates/known_hosts.erb#L7) needs cannot be evaluated in `bosh create-env`. We need to specify the `tsa.host_public_key` in the `concourse-lite.yml`.

```bash
bosh create-env concourse-lite.yml
Deployment manifest: '/Users/pivotal/Downloads/concourse-lite.yml'
Deployment state: '/Users/pivotal/Downloads/concourse-lite-state.json'

Started validating
  Downloading release 'concourse'... Finished (00:00:50)
  Validating release 'concourse'... Finished (00:00:00)
  Downloading release 'garden-runc'... Finished (00:00:48)
  Validating release 'garden-runc'... Finished (00:00:01)
  Downloading release 'postgres'... Finished (00:00:23)
  Validating release 'postgres'... Finished (00:00:01)
  Downloading release 'bosh-virtualbox-cpi'... Finished (00:00:39)
  Validating release 'bosh-virtualbox-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Finished (00:00:48)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:03:35)

Started installing CPI
  Compiling package 'golang-1.8-linux/c97f9a00c26b34a3f59ca15b0f5a079d7f7e27c334cc8100248143c5dc0d4c0a'... Finished (00:00:13)
  Compiling package 'golang-1.8-darwin/ee2bb46a25872469cd8fe0f4b0804bab5c39cc5512bbcc4335c8691a038d3e73'... Finished (00:00:12)
  Compiling package 'virtualbox_cpi/cb3116b9b6c2111a873bb4ea14a1f3544ccdd2af'... Finished (00:00:10)
  Installing packages... Finished (00:00:03)
  Rendering job templates... Finished (00:00:00)
  Installing job 'virtualbox_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:40)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3468.11'... Finished (00:00:07)

Started deploying
  Creating VM for instance 'concourse/0' from stemcell 'sc-5273e27d-ef47-49f9-5c42-37674a75da65'... Finished (00:00:01)
  Waiting for the agent on VM 'vm-4615e64b-08be-4f96-578e-10d84d5f0d37' to be ready... Finished (00:00:30)
  Creating disk... Finished (00:00:00)
  Attaching disk 'disk-27ef2bae-06d7-41f3-67b8-544321fdc8d1' to VM 'vm-4615e64b-08be-4f96-578e-10d84d5f0d37'... Finished (00:00:04)
  Rendering job templates... Failed (00:00:01)
Failed deploying (00:00:43)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Building state for instance 'concourse/0':
    Rendering job templates for instance 'concourse/0':
      Rendering templates for job 'groundcrew/e565b3c16260306cd7a0ca469b884d1ba5333c13':
        Rendering template src: known_hosts.erb, dst: config/known_hosts:
          Rendering template src: /Users/pivotal/.bosh/installations/c237d4a4-4909-4b50-40ed-681c84d96445/tmp/bosh-release-job989852582/templates/known_hosts.erb, dst: /Users/pivotal/.bosh/installations/c237d4a4-4909-4b50-40ed-681c84d96445/tmp/rendered-jobs876972701/config/known_hosts:
            Running ruby to render templates:
              Running command: 'ruby /Users/pivotal/.bosh/installations/c237d4a4-4909-4b50-40ed-681c84d96445/tmp/erb-renderer397173025/erb-render.rb /Users/pivotal/.bosh/installations/c237d4a4-4909-4b50-40ed-681c84d96445/tmp/erb-renderer397173025/erb-context.json /Users/pivotal/.bosh/installations/c237d4a4-4909-4b50-40ed-681c84d96445/tmp/bosh-release-job989852582/templates/known_hosts.erb /Users/pivotal/.bosh/installations/c237d4a4-4909-4b50-40ed-681c84d96445/tmp/rendered-jobs876972701/config/known_hosts', stdout: '', stderr: '/Users/pivotal/.bosh/installations/c237d4a4-4909-4b50-40ed-681c84d96445/tmp/erb-renderer397173025/erb-render.rb:189:in `rescue in render': Error filling in template '/Users/pivotal/.bosh/installations/c237d4a4-4909-4b50-40ed-681c84d96445/tmp/bosh-release-job989852582/templates/known_hosts.erb' for groundcrew/0 (line 9: #<NoMethodError: undefined method `link' for #<TemplateEvaluationContext:0x007f92d415ed48>>) (RuntimeError)
	from /Users/pivotal/.bosh/installations/c237d4a4-4909-4b50-40ed-681c84d96445/tmp/erb-renderer397173025/erb-render.rb:175:in `render'
	from /Users/pivotal/.bosh/installations/c237d4a4-4909-4b50-40ed-681c84d96445/tmp/erb-renderer397173025/erb-render.rb:200:in `<main>'
':
                exit status 1

Exit code 1
```

The following can also be handy:

* Concourse version: v3.7.0
* Deployment type (BOSH/Docker/binary): bosh concourse-lite

**Comment by vito** [comment]
This should be fixed now; I updated the concourse-deployment repo and re-published the 3.7.0 release. I don't have access to a machine to verify this, though. :(

**Comment by jtarchie** [comment]
I'll give it a go to verify.

**Comment by vito** [comment]
Thanks!

**Comment by jtarchie** [comment]
It deployed fine, but I was not able to access it locally. I'm deleting all my previous VMs and retrying to make sure it just wasn't a differently allocated IP address.

**Comment by jtarchie** [comment]
Looks good! 👍
