### ISSUE TITLE
Panic with baggage claim results in ATC going down

### ISSUE THREAD

**Issue by ctaymor** [concourse/concourse#195]
Running concourse v0.67

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x5b59da]

goroutine 67 [running]:
github.com/concourse/atc/lostandfound.(*baggageCollector).expireVolumes(0xc8203264c0, 0xc8209a4b70, 0x0, 0x0)
	/var/vcap/packages/atc/src/github.com/concourse/atc/lostandfound/baggage_collector.go:169 +0xbaa
github.com/concourse/atc/lostandfound.(*baggageCollector).Collect(0xc8203264c0, 0x0, 0x0)
	/var/vcap/packages/atc/src/github.com/concourse/atc/lostandfound/baggage_collector.go:45 +0xc2
github.com/concourse/atc/lostandfound.NewRunner.func1(0xc8200172c0, 0xc820017320, 0x0, 0x0)
	/var/vcap/packages/atc/src/github.com/concourse/atc/lostandfound/runner.go:52 +0x34c
github.com/tedsuo/ifrit.RunFunc.Run(0xc820320870, 0xc8200172c0, 0xc820017320, 0x0, 0x0)
	/var/vcap/packages/atc/src/github.com/tedsuo/ifrit/runner.go:36 +0x3c
github.com/tedsuo/ifrit/grouper.(*Member).Run(0xc8201953a0, 0xc8200172c0, 0xc820017320, 0x0, 0x0)
	<autogenerated>:1 +0x70
github.com/tedsuo/ifrit.(*process).run(0xc8201935c0)
	/var/vcap/packages/atc/src/github.com/tedsuo/ifrit/process.go:71 +0x53
created by github.com/tedsuo/ifrit.Background
	/var/vcap/packages/atc/src/github.com/tedsuo/ifrit/process.go:49 +0x177
```

Spoke with `challiwill` on concourse slack about this.

- Caroline & @aashah

**Comment by vito** [comment]
fixed in 0.67.1
