### ISSUE TITLE
Can't deploy Concourse Lite 3.9.0 with BOSH on OSX

### ISSUE THREAD

**Issue by iravid** [concourse/concourse#2054]
# Bug Report

I downloaded `concourse-lite.yml` from here: `https://github.com/concourse/concourse/releases/download/v3.9.0/concourse-lite.yml` and replaced the artifact reference to `concourse-3.9.0-3468.22.tgz`.

Getting this error after running `bosh create-env concourse-lite.yml` with BOSH 2.0.48:
```
Deploying:
  Building state for instance 'concourse/0':
    Rendering job templates for instance 'concourse/0':
      Rendering templates for job 'atc/f9fe777e9468efc55dc59069ef1aefb7b28677a3':
        Rendering template src: downgrade_db.erb, dst: bin/experimental_downgrade_db:
          Rendering template src: /Users/iravid/.bosh/installations/46ddb006-01d3-4b6b-7791-640c97a2c533/tmp/bosh-release-job764537757/templates/downgrade_db.erb, dst: /Users/iravid/.bosh/installations/46ddb006-01d3-4b6b-7791-640c97a2c533/tmp/rendered-jobs222717959/bin/experimental_downgrade_db:
            Running ruby to render templates:
              Running command: 'ruby /Users/iravid/.bosh/installations/46ddb006-01d3-4b6b-7791-640c97a2c533/tmp/erb-renderer070949781/erb-render.rb /Users/iravid/.bosh/installations/46ddb006-01d3-4b6b-7791-640c97a2c533/tmp/erb-renderer070949781/erb-context.json /Users/iravid/.bosh/installations/46ddb006-01d3-4b6b-7791-640c97a2c533/tmp/bosh-release-job764537757/templates/downgrade_db.erb /Users/iravid/.bosh/installations/46ddb006-01d3-4b6b-7791-640c97a2c533/tmp/rendered-jobs222717959/bin/experimental_downgrade_db', stdout: '', stderr: '/Users/iravid/.bosh/installations/46ddb006-01d3-4b6b-7791-640c97a2c533/tmp/erb-renderer070949781/erb-render.rb:189:in `rescue in render': Error filling in template '/Users/iravid/.bosh/installations/46ddb006-01d3-4b6b-7791-640c97a2c533/tmp/bosh-release-job764537757/templates/downgrade_db.erb' for atc/0 (line 61: #<NoMethodError: undefined method `esc' for #<TemplateEvaluationContext:0x00007f952a130378>>) (RuntimeError)
        from /Users/iravid/.bosh/installations/46ddb006-01d3-4b6b-7791-640c97a2c533/tmp/erb-renderer070949781/erb-render.rb:174:in `render'
        from /Users/iravid/.bosh/installations/46ddb006-01d3-4b6b-7791-640c97a2c533/tmp/erb-renderer070949781/erb-render.rb:200:in `<main>'
':
                exit status 1

Exit code 1
```

**Comment by vito** [comment]
We're not really supporting the BOSH Concourse Lite flow anymore so I'm gonna close this. The modern alternative is the Docker Compose "quick start" visible on our home page.
