### ISSUE TITLE
ATC dying with SIGSEGV in RetryStep.Succeeded()

### ISSUE THREAD

**Issue by ktchen14** [concourse/concourse#2095]
# Bug Report

* Concourse version: 3.9.2
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: vCloud Director
* Did this used to work? Yes it worked in Concourse 3.9.1 as far as I can tell

Our Concourse ATC is repeatedly dying with `SIGSEGV`:

```
Mar 16 20:10:00 ci 42b156964152[88218]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa21dca]
Mar 16 20:10:00 ci 42b156964152[88218]:
Mar 16 20:10:00 ci 42b156964152[88218]: goroutine 205 [running]:
Mar 16 20:10:00 ci 42b156964152[88218]: github.com/concourse/atc/exec.(*RetryStep).Succeeded(0xc420fd3d70, 0x1a3b580)
Mar 16 20:10:00 ci 42b156964152[88218]:         /tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/retry_step.go:47 +0x2a
Mar 16 20:10:00 ci 42b156964152[88218]: github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x1290dba0, 0xc420fd3d70, 0x12915b60, 0xc420fca1c0, 0xa1cf01)
Mar 16 20:10:00 ci 42b156964152[88218]:         /tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x31
Mar 16 20:10:00 ci 42b156964152[88218]: github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x1290dba0, 0xc420fd3f50, 0x12915b60, 0xc420fca9e0, 0x1)
Mar 16 20:10:00 ci 42b156964152[88218]:         /tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
Mar 16 20:10:00 ci 42b156964152[88218]: github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x12915920, 0xc420fcacc0, 0x12915b60, 0xc420fcac20, 0xc42163b480)
Mar 16 20:10:00 ci 42b156964152[88218]:         /tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
Mar 16 20:10:00 ci 42b156964152[88218]: github.com/concourse/atc/engine.(*execBuild).Resume(0xc42540e8c0, 0x12939a60, 0xc4211034a0)
Mar 16 20:10:00 ci 42b156964152[88218]:         /tmp/build/9674af12/concourse/src/github.com/concourse/atc/engine/exec_engine.go:152 +0x3a7
Mar 16 20:10:00 ci 42b156964152[88218]: github.com/concourse/atc/engine.(*dbBuild).Resume(0xc4211004c0, 0x12939a60, 0xc4211034a0)
Mar 16 20:10:00 ci 42b156964152[88218]:         /tmp/build/9674af12/concourse/src/github.com/concourse/atc/engine/db_engine.go:270 +0x8ab
Mar 16 20:10:00 ci 42b156964152[88218]: created by github.com/concourse/atc/builds.(*Tracker).Track
Mar 16 20:10:00 ci 42b156964152[88218]:         /tmp/build/9674af12/concourse/src/github.com/concourse/atc/builds/tracker.go:58 +0x581
Mar 16 20:10:02 ci af54ce7a5e4a[88218]: ERROR:  relation "migration_version" does not exist at character 21
Mar 16 20:10:02 ci af54ce7a5e4a[88218]: STATEMENT:  SELECT version FROM migration_version
Mar 16 20:10:02 ci af54ce7a5e4a[88218]: ERROR:  relation "migration_version" does not exist at character 21
Mar 16 20:10:02 ci af54ce7a5e4a[88218]: STATEMENT:  SELECT version FROM migration_version
```

This appears to be the code in `retry_step.go` that's failing:

```go
// Succeeded delegates to the last step that it ran.
func (step *RetryStep) Succeeded() bool {
	return step.LastAttempt.Succeeded()
}
```

**Comment by ktchen14** [comment]
This is happening once a day to us leaving our entire Concourse instance down until we restart the master.

**Comment by fkoclas** [comment]
What ends up happening for us is our ATC pod in kubernetes restarts, but then all of the workers's concourse processes just quit.

It happened again yesterday:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa21dca]

goroutine 105378108 [running]:
github.com/concourse/atc/exec.(*RetryStep).Succeeded(0xc42624aed0, 0x17f5d80)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/retry_step.go:47 +0x2a
github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x1290dba0, 0xc42624aed0, 0x12915a20, 0x1371dec8, 0xc42045c801)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x31
github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x12915a60, 0xc424f8cac0, 0x12915b60, 0xc424f8ca40, 0x17f5d01)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x12915b60, 0xc424f8cb60, 0x12915b60, 0xc424f8cae0, 0x1)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x12915b20, 0xc424f8cce0, 0x12915b60, 0xc424f8cb80, 0x1)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
github.com/concourse/atc/exec.AggregateStep.Succeeded(0xc424f8cf40, 0x2, 0x2, 0xc4204b39e0)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/aggregate.go:53 +0x4a
github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x12915920, 0xc424f8cf60, 0x12915a20, 0x1371dec8, 0xa1cf01)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x31
github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x12915a60, 0xc424f8d000, 0x12915b60, 0xc424f8cf80, 0x1)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x12915920, 0xc424f8d0c0, 0x12915b60, 0xc424f8d020, 0xc421fa1f50)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
github.com/concourse/atc/engine.(*execBuild).Resume(0xc421253cc0, 0x12939a60, 0xc4207bb3e0)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/engine/exec_engine.go:152 +0x3a7
github.com/concourse/atc/engine.(*dbBuild).Resume(0xc42108fd80, 0x12939a60, 0xc4207bb3e0)
	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/engine/db_engine.go:270 +0x8ab
```

**Comment by skazanskiy3** [comment]
Also experiencing this error after upgrading from 3.8.0 to 3.9.2

```concourse-web       | panic: runtime error: invalid memory address or nil pointer dereference
concourse-web       | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa21dca]
concourse-web       | 
concourse-web       | goroutine 200103 [running]:
concourse-web       | github.com/concourse/atc/exec.(*RetryStep).Succeeded(0xc424939020, 0x412719)
concourse-web       | 	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/retry_step.go:47 +0x2a
concourse-web       | github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x1290dba0, 0xc424939020, 0x12915b60, 0xc423eb4620, 0x1)
concourse-web       | 	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x31
concourse-web       | github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x1290dba0, 0xc4249391d0, 0x12915b60, 0xc423eb4a40, 0xc424903901)
concourse-web       | 	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
concourse-web       | github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x1290dba0, 0xc424939ad0, 0x12915b60, 0xc423eb4c00, 0x1)
concourse-web       | 	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
concourse-web       | github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x1290dba0, 0xc4248f0270, 0x12915b60, 0xc423eb4dc0, 0x1)
concourse-web       | 	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
concourse-web       | github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x1290dba0, 0xc4248f0870, 0x12915b60, 0xc423eb4f40, 0xc4212afc40)
concourse-web       | 	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
concourse-web       | github.com/concourse/atc/engine.(*execBuild).Resume(0xc420940000, 0x12939a60, 0xc420d1e120)
concourse-web       | 	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/engine/exec_engine.go:152 +0x3a7
concourse-web       | github.com/concourse/atc/engine.(*dbBuild).Resume(0xc424f34c00, 0x12939a60, 0xc420d1e120)
concourse-web       | 	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/engine/db_engine.go:270 +0x8ab
concourse-web       | created by github.com/concourse/atc/scheduler.(*buildStarter).tryStartNextPendingBuild
concourse-web       | 	/tmp/build/9674af12/concourse/src/github.com/concourse/atc/scheduler/buildstarter.go:196 +0xb6c
concourse-web exited with code 2

**Comment by DRuggeri** [comment]
Same. We were able to work around the problem temporarily by rerunning the BOSH deployment, but the "fix" did not last long. Deleting both VMs and having them recreated from scratch was the only consistent fix.

**Comment by vito** [comment]
Looking at this now!

**Comment by vito** [comment]
Does anyone have steps to repro this consistently by any chance? I mean, I can obviously see the line of code to fix, but I'm not quite sure how the code would get into that situation (of something calling .Succeeded before the step runs).

**Comment by vito** [comment]
Nevermind, got to the bottom of it. It happens when a retry step is preceded by a Task step which errors.

**Comment by simonjohansson** [comment]
We see this from time to time, on 5.7.. Any idea how to identify what worker/pipeline/job is causing this issue?

**Comment by simonjohansson** [comment]
The only thing that made our ATCs stop panicking was to recreate the workers.

Whats strange is that we could not find any reference[1] to `/tmp/build/1c3187db`[2][3] anywhere in the DB... Restarting the ATCs did nothing.


[1]
https://github.com/concourse/concourse/blob/v5.7.0/atc/engine/builder/step_factory.go#L127
[2]
```
concourse=> select * from volumes where path='/tmp/build/1c3187db';
(0 rows)
concourse=> select * from containers where meta_working_directory='/tmp/build/1c3187db';
(0 rows)
```
[3]
```

panic: runtime error: invalid memory address or nil pointer dereference[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb4a25a]goroutine 160772 [running]:github.com/concourse/concourse/atc/exec.(*RetryStep).Succeeded(0xc0205aaf30, 0xc02d54db30)	/tmp/build/1c3187db/concourse/atc/exec/retry_step.go:47 +0x2agithub.com/concourse/concourse/atc/exec.OnSuccessStep.Succeeded(0x2841da0, 0xc0205aaf30, 0x284a7e0, 0xc02d94fa00, 0x1)	/tmp/build/1c3187db/concourse/atc/exec/on_success.go:45 +0x31github.com/concourse/concourse/atc/exec.OnSuccessStep.Succeeded(0x2841e20, 0xc0205aaf60, 0x284a7e0, 0xc02d94fa60, 0xc01c0a1430)	/tmp/build/1c3187db/concourse/atc/exec/on_success.go:45 +0x5cgithub.com/concourse/concourse/atc/engine.(*engineBuild).Run(0xc020ec9b30, 0x2895fa0, 0xc006e21800)	/tmp/build/1c3187db/concourse/atc/engine/engine.go:215 +0x8cdcreated by github.com/concourse/concourse/atc/builds.(*Tracker).Track	/tmp/build/1c3187db/concourse/atc/builds/tracker.go:49 +0x425
--
 


```

**Comment by simonjohansson** [comment]
For anyone who is looking at this in the future, `/tmp/build/1c3187db` is a red herring. @vito explains "that path is just the source location from when the concourse binary itself was built (i.e. our own pipelines which build/publish concourse)"
