### ISSUE TITLE
ATC crashing with missing input mapping

### ISSUE THREAD

**Issue by lflux** [concourse/concourse#2145]
# Bug Report

* Concourse version: 3.9.2
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP/vSphere

We ran into a situation where atc would keep crashing due to a task missing an input.

The task YAML had an input section like:
```
inputs:
- name: environment-lock
- name: tile-repo
- name: dedicated-mysql-ci
```

We had missed an `input_mapping: {tile-repo: dedicated-mysql-tile}` in the job definition in the pipeline YAML.

ATC would continuously crash with the following log messages:

atc.stdout:

```
{"timestamp":"1523402567.021352291","source":"atc","message":"atc.build-tracker.track.finished","log_level":1,"data":{"build":15618,"exit-status":0,"job":"t
est-product-upgrade-previous-minor-us_2_0_srt","pipeline":"tile-2.4","session":"41.1"}}
{"timestamp":"1523402567.253593445","source":"atc","message":"atc.build-tracker.track.already-exited","log_level":1,"data":{"build":15618,"job":"test-produc
t-upgrade-previous-minor-us_2_0_srt","pipeline":"tile-2.4","session":"41.1","status":"0"}}
{"timestamp":"1523402567.847433805","source":"atc","message":"atc.build-tracker.track.already-exited","log_level":1,"data":{"build":15618,"job":"test-produc
t-upgrade-previous-minor-us_2_0_srt","pipeline":"tile-2.4","session":"41.1","status":"0"}}
{"timestamp":"1523402567.885409594","source":"atc","message":"atc.build-tracker.track.errored","log_level":1,"data":{"build":15618,"error":"missing inputs:
tile-repo","job":"test-product-upgrade-previous-minor-us_2_0_srt","pipeline":"tile-2.4","session":"41.1"}}
```

atc.stderr:

```
goroutine 226 [running]:
github.com/concourse/atc/exec.(*RetryStep).Succeeded(0xc420342ae0, 0x412049)
        /var/vcap/packages/atc/src/github.com/concourse/atc/exec/retry_step.go:47 +0x2a
github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x1938e00, 0xc420342ae0, 0x193f900, 0xc4206720e0, 0x1)
        /var/vcap/packages/atc/src/github.com/concourse/atc/exec/on_success.go:45 +0x31
github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x193f800, 0xc420672380, 0x193f900, 0xc420672300, 0x917e01)
        /var/vcap/packages/atc/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x193f800, 0xc420672480, 0x193f900, 0xc4206723a0, 0x914101)
        /var/vcap/packages/atc/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x193f800, 0xc420672520, 0x193f900, 0xc4206724a0, 0x1)
        /var/vcap/packages/atc/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
github.com/concourse/atc/exec.OnSuccessStep.Succeeded(0x193f6c0, 0xc420672780, 0x193f900, 0xc420672580, 0xc420402ea0)
        /var/vcap/packages/atc/src/github.com/concourse/atc/exec/on_success.go:45 +0x5e
github.com/concourse/atc/engine.(*execBuild).Resume(0xc420804b40, 0x195d800, 0xc42002a480)
        /var/vcap/packages/atc/src/github.com/concourse/atc/engine/exec_engine.go:152 +0x3a7
github.com/concourse/atc/engine.(*dbBuild).Resume(0xc4204d2a40, 0x195d800, 0xc42002a480)
        /var/vcap/packages/atc/src/github.com/concourse/atc/engine/db_engine.go:270 +0x8ab
created by github.com/concourse/atc/builds.(*Tracker).Track
        /var/vcap/packages/atc/src/github.com/concourse/atc/builds/tracker.go:58 +0x581
```

**Comment by vito** [comment]
This was fixed in [v3.10.0](https://concourse-ci.org/download.html#v3100) (sixth note) - it's actually due to the `attempts`, not the `input_mapping`.

Thanks for the report!
