### ISSUE TITLE
Bitbucket Server auth no longer working

### ISSUE THREAD

**Issue by olivercf** [concourse/concourse#2232]
I have concourse running in kubernetes, and upgraded from 3.9 to 3.13. After fixing the environmental variable for TSA to include the port, it runs and builds fine, but bitbucket server authentication is now broken. I haven't changed my authentication configuration. The page I get redirected to fails to load, and I get an exception in the logs:

```
2018/05/23 11:45:22 http2: panic serving 100.96.9.1:25497: runtime error: invalid memory address or nil pointer dereference
goroutine 41780 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc420b5e2a0, 0xc424a3ffaf, 0xc421478380)
        /usr/local/go/src/net/http/h2_bundle.go:5753 +0x190
panic(0x253c5a0, 0x1514d360)
        /usr/local/go/src/runtime/panic.go:502 +0x229
crypto/rsa.SignPKCS1v15(0x143d5120, 0xc4200dc270, 0x0, 0x3, 0xc424a3f5ac, 0x14, 0x14, 0x44, 0x54, 0xc420727e00, ...)
        /usr/local/go/src/crypto/rsa/pkcs1v15.go:235 +0x77
github.com/dghubble/oauth1.(*RSASigner).Sign(0xc420b5e318, 0x0, 0x0, 0xc420d6e000, 0x1bc, 0x244f3c0, 0x0, 0x2375d97, 0xe)
        /tmp/build/9674af12/concourse/src/github.com/dghubble/oauth1/signer.go:57 +0xde
github.com/dghubble/oauth1.(*auther).setRequestTokenAuthHeader(0xc424a3f6f0, 0xc420855500, 0xc420052a00, 0x44)
        /tmp/build/9674af12/concourse/src/github.com/dghubble/oauth1/auther.go:68 +0x13b
github.com/dghubble/oauth1.(*Config).RequestToken(0xc4202ee070, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/9674af12/concourse/src/github.com/dghubble/oauth1/config.go:67 +0xe8
github.com/concourse/skymarshal/bitbucket/server.(*Provider).AuthCodeURL(0xc420e32100, 0xc420052af0, 0x4a, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
        /tmp/build/9674af12/concourse/src/github.com/concourse/skymarshal/bitbucket/server/provider.go:20 +0x32
github.com/concourse/skymarshal/auth.(*OAuthBeginHandler).ServeHTTP(0xc420060600, 0x14409c20, 0xc420b5e2a0, 0xc420855400)
        /tmp/build/9674af12/concourse/src/github.com/concourse/skymarshal/auth/oauth_begin_handler.go:114 +0x3ef
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc4214692c0, 0x14409c20, 0xc420b5e2a0, 0xc420855400)
        /tmp/build/9674af12/concourse/src/github.com/bmizerany/pat/mux.go:117 +0x151
net/http.(*ServeMux).ServeHTTP(0xc4203cc030, 0x14409c20, 0xc420b5e2a0, 0xc420855400)
        /usr/local/go/src/net/http/server.go:2337 +0x130
net/http.(*ServeMux).ServeHTTP(0xc4207e02d0, 0x14409c20, 0xc420b5e2a0, 0xc420855400)
        /usr/local/go/src/net/http/server.go:2337 +0x130
github.com/concourse/atc/api/auth.CookieSetHandler.ServeHTTP(0x143d8900, 0xc4207e02d0, 0x14409c20, 0xc420b5e2a0, 0xc420855400)
        /tmp/build/9674af12/concourse/src/github.com/concourse/atc/api/auth/cookie_set_handler.go:23 +0x85
github.com/concourse/atc/wrappa.SecurityHandler.ServeHTTP(0x0, 0x0, 0x143da040, 0xc4204dab30, 0x14409c20, 0xc420b5e2a0, 0xc420855400)
        /tmp/build/9674af12/concourse/src/github.com/concourse/atc/wrappa/security_handler.go:17 +0x145
github.com/concourse/atc/wrappa.LoggerHandler.ServeHTTP(0x14420460, 0xc4200b2600, 0x143da660, 0xc4207bd400, 0x14409c20, 0xc420b5e2a0, 0xc420855300)
        /tmp/build/9674af12/concourse/src/github.com/concourse/atc/wrappa/logger_handler.go:20 +0x1e6
net/http.serverHandler.ServeHTTP(0xc420028ea0, 0x14409c20, 0xc420b5e2a0, 0xc420855300)
        /usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.initNPNRequest.ServeHTTP(0xc4201d7c00, 0xc420028ea0, 0x14409c20, 0xc420b5e2a0, 0xc420855300)
        /usr/local/go/src/net/http/server.go:3260 +0x9a
net/http.(Handler).ServeHTTP-fm(0x14409c20, 0xc420b5e2a0, 0xc420855300)
        /usr/local/go/src/net/http/h2_bundle.go:5475 +0x4d
net/http.(*http2serverConn).runHandler(0xc421478380, 0xc420b5e2a0, 0xc420855300, 0xc421027c40)
        /usr/local/go/src/net/http/h2_bundle.go:5760 +0x89
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:5494 +0x46b
```

**Comment by SHyx0rmZ** [comment]
Are you using it globally or just for some teams?

**Comment by SHyx0rmZ** [comment]
If it is the latter, this can be worked around by setting the auth for the team again.
