### ISSUE TITLE
fly login fails

### ISSUE THREAD

**Issue by caevv** [concourse/concourse#2331]
It's interesting, this doesn't happen with colleagues computer, just here. It maybe a coincidence I ran fly sync.

```
fly login -t ...
logging in to team 'all'

navigate to the following URL in your browser:

    ...?team_name=all&fly_local_port=52113

or enter token manually: panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/concourse/fly/rc.SaveTarget(0x7ffeefbffc95, 0x9, 0x7ffeefbffca9, 0x2b, 0x0, 0x7ffeefbffca2, 0x3, 0xc420335500, 0x0, 0x0, ...)
	/Users/pilot/Worker/workdir/volumes/live/a294f9c1-d4a7-450f-6a0b-208de996047b/volume/concourse/src/github.com/concourse/fly/rc/targets.go:86 +0x15a
github.com/concourse/fly/commands.(*LoginCommand).saveTarget(0x19fdaa0, 0x7ffeefbffca9, 0x2b, 0xc420061bc8, 0x0, 0x0, 0x45, 0x1726820)
	/Users/pilot/Worker/workdir/volumes/live/a294f9c1-d4a7-450f-6a0b-208de996047b/volume/concourse/src/github.com/concourse/fly/commands/login.go:316 +0xf3
github.com/concourse/fly/commands.(*LoginCommand).Execute(0x19fdaa0, 0xc42021a700, 0x0, 0x7, 0x19fdaa0, 0x1)
	/Users/pilot/Worker/workdir/volumes/live/a294f9c1-d4a7-450f-6a0b-208de996047b/volume/concourse/src/github.com/concourse/fly/commands/login.go:142 +0x6d3
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc420122ba0, 0xc4200aa010, 0x7, 0x7, 0x3, 0xc4200abe00, 0xc420131dd0, 0xc420122cc0, 0x7ffeefbffc88)
	/Users/pilot/Worker/workdir/volumes/live/a294f9c1-d4a7-450f-6a0b-208de996047b/volume/concourse/src/github.com/jessevdk/go-flags/parser.go:316 +0x80b
github.com/jessevdk/go-flags.(*Parser).Parse(0xc420122ba0, 0x19fda80, 0x2, 0xc420122cc0, 0xc4200b72b8, 0x0)
	/Users/pilot/Worker/workdir/volumes/live/a294f9c1-d4a7-450f-6a0b-208de996047b/volume/concourse/src/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
	/Users/pilot/Worker/workdir/volumes/live/a294f9c1-d4a7-450f-6a0b-208de996047b/volume/concourse/src/github.com/concourse/fly/main.go:51 +0x29a
```

* Infrastructure/IaaS: AWS
* Did this used to work? Yes
fly -v
3.14.1

**Comment by jama-pivotal** [comment]
Weird. @caevv can you verify that:
* the target you are trying to login against is also 3.14.1
* when you did a `fly sync` you actually did it against the target that's also 3.14.1

And does re-downloading the fly binary from Concourse (you can to it from the web UI and clicking on the OS icon in the bottom right hand corner) fixes things?

**Comment by caevv** [comment]
Thanks @jama-pivotal 
Yes, it is version: v3.14.1
The `fly sync` was against the target that is also on 3.14.1.
And yes, I did download it again and put on my local bin.

**Comment by caevv** [comment]
Found the problem, my `.flyrc` was broken.

**Comment by jama-pivotal** [comment]
Thanks for following up with the update!
