### ISSUE TITLE
Panic on misconfigured worker start

### ISSUE THREAD

**Issue by jdub** [concourse/concourse#2512]
Hi there,

I'm getting a nil dereference when starting a worker with the concourse 4.0.0 binary release. It fails the same way on restart.

The loopback volume is mounted, and all the assets appear to have unpacked correctly.

I'm starting the worker with: `concourse worker --work-dir=/var/lib/concourse/data`, with `CONCOURSE_TSA_HOST=elb.example.com:2222` and `CONCOURSE_LOG_LEVEL=debug`.

What else can I tell you about the environment?

```
Aug 21 07:28:29 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836509.525844812","source":"worker","message":"worker.setup.unpacking","log_level":1,"data":{"session":"1"}}
Aug 21 07:28:35 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836515.391672373","source":"worker","message":"worker.setup.done","log_level":1,"data":{"session":"1"}}
Aug 21 07:28:35 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836515.393445015","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"bosh-deployment","session":"2.1.1"}}
Aug 21 07:28:36 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836516.037477732","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"bosh-io-release","session":"2.1.2"}}
Aug 21 07:28:36 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836516.293032885","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"bosh-io-stemcell","session":"2.1.3"}}
Aug 21 07:28:36 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836516.804776192","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"cf","session":"2.1.4"}}
Aug 21 07:28:37 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836517.864204645","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"docker-image","session":"2.1.5"}}
Aug 21 07:28:41 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836521.185465336","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"git","session":"2.1.6"}}
Aug 21 07:28:42 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836522.072281599","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"github-release","session":"2.1.7"}}
Aug 21 07:28:42 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836522.804645777","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"hg","session":"2.1.8"}}
Aug 21 07:28:44 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836524.435416937","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"pool","session":"2.1.9"}}
Aug 21 07:28:45 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836525.628185511","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"s3","session":"2.1.10"}}
Aug 21 07:28:46 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836526.755576372","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"semver","session":"2.1.11"}}
Aug 21 07:28:48 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836528.194944143","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"time","session":"2.1.12"}}
Aug 21 07:28:48 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836528.674185991","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"tracker","session":"2.1.13"}}
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: {"timestamp":"1534836529.719893456","source":"baggageclaim","message":"baggageclaim.using-driver","log_level":1,"data":{"driver":"btrfs"}}
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25c8d66]
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: goroutine 1 [running]:
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: main.(*WorkerCommand).Runner(0xc420504718, 0xc42046b340, 0x0, 0x2, 0x2149481, 0xc420643b00, 0xc420791660, 0x21499d0)
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: /tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/worker.go:86 +0x396
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: main.(*WorkerCommand).Execute(0xc420504718, 0xc42046b340, 0x0, 0x2, 0x28b59a0, 0x2aa6580)
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: /tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/worker.go:47 +0x4d
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: github.com/vito/twentythousandtonnesofcrudeoil.installEnv.func2(0x7f5f0c974000, 0xc420504718, 0xc42046b340, 0x0, 0x2, 0x1, 0x0)
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: /tmp/build/9674af12/concourse/src/github.com/vito/twentythousandtonnesofcrudeoil/environment.go:40 +0x8a
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc420550a80, 0xc42004c100, 0x2, 0x2, 0xc420791840, 0x21492df, 0xc420550a80, 0x2bb0ae6, 0xa)
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: /tmp/build/9674af12/concourse/src/github.com/jessevdk/go-flags/parser.go:314 +0x7c7
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: github.com/jessevdk/go-flags.(*Parser).Parse(0xc420550a80, 0x2bb0ae6, 0xa, 0xc42060e880, 0x0, 0x0)
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: /tmp/build/9674af12/concourse/src/github.com/jessevdk/go-flags/parser.go:186 +0x71
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: main.main()
Aug 21 07:28:49 ip-10-101-147-238.ap-southeast-2.compute.internal concourse[1036]: /tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/main.go:33 +0x1a4
```

**Comment by jdub** [comment]
It was the absence of a TSA host key and/or worker key… perhaps this should be an error instead. 😄

**Comment by marco-m** [comment]
Related: #2152 (ATC crashes during worker registration when session key is not provided)

**Comment by eedwards-sk** [comment]
getting this on 4.2.2 as well

It's likely a mis-configuration on my end (although my only change was going from 4.2.1 to 4.2.2...)

but a proper error would still be nice :)

```
→ docker logs b398faa3922f
{"timestamp":"1544805843.106509924","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"keys expired, rotating","session":"5"}}
{"timestamp":"1544805843.283713102","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"keys rotated, next rotation: 2018-12-14 22:44:03.2775699 +0000 UTC m=+21603.302328901","session":"5"}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfe3485]

goroutine 1 [running]:
crypto/rsa.(*PrivateKey).Public(0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/rsa/rsa.go:100 +0x5
golang.org/x/crypto/ssh.NewSignerFromSigner(0x7fdd419e9208, 0xc00000e8d8, 0xc00000e8d8, 0x7fdd419e9208, 0xc00000e8d8, 0xe8af01)
	/tmp/build/9674af12/concourse/src/golang.org/x/crypto/ssh/keys.go:681 +0x35
golang.org/x/crypto/ssh.NewSignerFromKey(0x2a2ec40, 0xc00000e8d8, 0xe8afc8, 0x30, 0x2b17280, 0xc000c25408)
	/tmp/build/9674af12/concourse/src/golang.org/x/crypto/ssh/keys.go:656 +0x16a
github.com/concourse/tsa/tsacmd.(*TSACommand).configureSSHServer(0xc00047b080, 0xc0009a1b10, 0xc0006c7ea0, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc000170540, 0x7, ...)
	/tmp/build/9674af12/concourse/src/github.com/concourse/tsa/tsacmd/command.go:197 +0x167
github.com/concourse/tsa/tsacmd.(*TSACommand).Runner(0xc00047b080, 0xc000806ba0, 0x0, 0x2, 0x17dbf3e0, 0xc000aefb20, 0x0, 0x0)
	/tmp/build/9674af12/concourse/src/github.com/concourse/tsa/tsacmd/command.go:95 +0x249
main.(*WebCommand).Runner(0xc000412308, 0xc000806ba0, 0x0, 0x2, 0x2, 0x5, 0xc0006c7a20, 0xc000603480)
	/tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/web.go:67 +0x132
main.(*WebCommand).Execute(0xc000412308, 0xc000806ba0, 0x0, 0x2, 0x28fdf00, 0x2b849a0)
	/tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/web.go:42 +0x5c
github.com/vito/twentythousandtonnesofcrudeoil.installEnv.func2(0x7fdd41a79ad8, 0xc000412308, 0xc000806ba0, 0x0, 0x2, 0x1, 0x0)
	/tmp/build/9674af12/concourse/src/github.com/vito/twentythousandtonnesofcrudeoil/environment.go:40 +0x8a
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000155e60, 0xc0000c0070, 0x2, 0x2, 0xc000ae7880, 0x20fe7bf, 0xc000155e60, 0x2bc8113, 0xa)
	/tmp/build/9674af12/concourse/src/github.com/jessevdk/go-flags/parser.go:314 +0x7bc
github.com/jessevdk/go-flags.(*Parser).Parse(0xc000155e60, 0x2bc8113, 0xa, 0xc000536200, 0x0, 0x0)
	/tmp/build/9674af12/concourse/src/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
	/tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/main.go:33 +0x19e
```

**Comment by edtan** [comment]
It seems like this is happening on `master` now [here](https://github.com/concourse/concourse/blob/master/worker/tsa_config.go#L19) if you do not provide the `--tsa-worker-private-key`, due to #3766:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16b7cbf]

goroutine 1 [running]:
github.com/concourse/concourse/worker.TSAConfig.Client(...)
	/home/ed/src/concourse/worker/tsa_config.go:19
main.(*WorkerCommand).Runner(0xc000029b28, 0xc0003ab680, 0x0, 0x3, 0x2, 0x6, 0xc000369950, 0xc0004521c0)
	/home/ed/src/concourse/cmd/concourse/worker.go:95 +0x54f
main.(*WorkerCommand).Execute(0xc000029b28, 0xc0003ab680, 0x0, 0x3, 0x1986980, 0x1b2e800)
	/home/ed/src/concourse/cmd/concourse/worker.go:61 +0x5c
github.com/vito/twentythousandtonnesofcrudeoil.installEnv.func2(0x7f51b72efbb8, 0xc000029b28, 0xc0003ab680, 0x0, 0x3, 0x1, 0x0)
	/home/ed/go/pkg/mod/github.com/vito/twentythousandtonnesofcrudeoil@v0.0.0-20180305154709-3b21ad808fcb/environment.go:40 +0x8a
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000150f60, 0xc0000be050, 0x3, 0x3, 0xc000533b18, 0x16a1e6f, 0xc000150f60, 0x1bc508f, 0xa)
	/home/ed/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:314 +0x7c7
github.com/jessevdk/go-flags.(*Parser).Parse(0xc000150f60, 0x1bc508f, 0xa, 0xc000163900, 0xc0001446c0, 0x0)
	/home/ed/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186 +0x71
main.main()
	/home/ed/src/concourse/cmd/concourse/main.go:31 +0x1ac
```

**Comment by vito** [comment]
I think the root of this particular error is https://github.com/jessevdk/go-flags/issues/260

@edtan Submitted a PR to fix that here: https://github.com/concourse/concourse/pull/3864

**Comment by xtremerui** [comment]
it will show error `error: the required flag `--tsa-worker-private-key' was not specified` now.
