### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8ab5dd]

### ISSUE THREAD

**Issue by cperry169** [concourse/concourse#2590]
* Concourse version: v4.1.0
 * Deployment type (BOSH/Docker/binary): docker-compose, 
*  Docker Compose Version: docker-compose version 1.18.0, build 8dd22a9
* Docker Version:  Docker version 18.06.1-ce, build e68fc7a
*  Infrastructure/IaaS: Setup on Virtual Machines Ubuntu 16.04 
* Browser (if applicable): Chrome, FireFox, Safari
 * Did this used to work?  Previous version of CC worked. Version 3.9.0

# Feature Request

## What challenge are you facing?
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8ab5dd]

goroutine 1 [running]:
github.com/concourse/fly/commands.GetExpirationFromString(0xc00016ff40, 0xc0001b3410, 0xc00004bd60)
	/tmp/build/9674af12/concourse/src/github.com/concourse/fly/commands/targets.go:59 +0x7d
github.com/concourse/fly/commands.(*TargetsCommand).Execute(0xe049b0, 0xc0001c4140, 0x0, 0x1, 0xe049b0, 0x1)
	/tmp/build/9674af12/concourse/src/github.com/concourse/fly/commands/targets.go:33 +0x57f
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc00005ef00, 0xc00000a090, 0x1, 0x1, 0x90c580, 0xc0001a95b0, 0xc00004bf38, 0x8a9237, 0xc0001026c0)
	/tmp/build/9674af12/concourse/src/github.com/jessevdk/go-flags/parser.go:316 +0x800
github.com/jessevdk/go-flags.(*Parser).Parse(0xc00005ef00, 0x9d67d6, 0x8, 0xc0000fe780, 0x0, 0x0)
	/tmp/build/9674af12/concourse/src/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
	/tmp/build/9674af12/concourse/src/github.com/concourse/fly/main.go:24 +0x101

**Comment by ahaczewski** [comment]
Same here.

**Comment by ahaczewski** [comment]
Happens just after key rotated:
```concourse-web_1     | {"timestamp":"1537295512.434964895","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"keys expired, rotating","session":"5"}}
concourse-web_1     | {"timestamp":"1537295512.620816469","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"keys rotated, next rotation: 2018-09-19 00:31:52.618429464 +0000 UTC m=+21641.400663850","session":"5"}}
concourse-web_1     | panic: runtime error: invalid memory address or nil pointer dereference
concourse-web_1     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfe3485]
concourse-web_1     | 
```

**Comment by cperry169** [comment]
I created  new keys and upgrade to 4.2.1 and solved

Sincerely,

Chad Perry
CompTIA A+, Network+, Server+, Linux+ SME
cperry169@hotmail.com
512.961.0291

Linkedin: www.linkedin.com/in/chadbperry
GitHub: https://github.com/cperry169

________________________________

**Comment by luispabon** [comment]
Had this issue on keys generated as per @cperry169 comment above, but on mac os mojave. Re-generating them from linux fixed it up for me.

**Comment by kwladyka** [comment]
Why this issue is closed? Bug still exists with 4.2.2.

https://www.openssh.com/txt/release-7.8

concourse is not compatible with modern ssh-keygen.

**Comment by cperry169** [comment]
openssl genpkey -algorithm RSA -out session_signing_key -pkeyopt rsa_keygen_bits:2048
followed by

chmod 0400 session_signing_key
and finally

ssh-keygen -f session_signing_key -y > session_signing_key.pub

Sincerely,

Chad Perry
CompTIA A+, Network+, Server+, Linux+ SME
cperry169@hotmail.com
512.961.0291

Linkedin: www.linkedin.com/in/chadbperry
GitHub: https://github.com/cperry169

________________________________

**Comment by cperry169** [comment]
That’s a worker issue you need to power cycle your workers and use rebuild the key pairs

Sincerely,

Chad Perry
CompTIA A+, Network+, Server+, Linux+ SME
cperry169@hotmail.com
512.961.0291

Linkedin: www.linkedin.com/in/chadbperry
GitHub: https://github.com/cperry169

________________________________

**Comment by kwladyka** [comment]
I found much easier solution:
https://github.com/concourse/concourse-docker/blob/master/generate-keys.sh

Just add `-m PEM` to generate old style certs.

*But all this tricks are workarounds. Bug still exist and status should be open. It is not fixed - concourse doesn't work with modern key generation.*
