### ISSUE TITLE
Garden monit-stop doesn't stop all services

### ISSUE THREAD

**Issue by keithkroeger** [concourse/concourse#2632]
## Bug Report

We are finding that garden does not always stop the 'worker' services/threads when 'monit stop' is executed.  This causes a start to potentially fail.

## Steps to Reproduce

When completing a BOSH deployment, we often see messages such as:
```
Task 776002 | 10:13:10 | Updating instance dev-worker: dev-worker/87896566-0519-4122-894b-85c68ac582c0 (2) (00:07:38)
	
                      L Error: 'dev-worker/87896566-0519-4122-894b-85c68ac582c0 (2)' is not running after update. Review logs for failed jobs: garden
	
Task 776002 | 10:13:10 | Error: 'dev-worker/87896566-0519-4122-894b-85c68ac582c0 (2)' is not running after update. Review logs for failed jobs: garden
```

When we look further, we see that the attempt to start the job failed due to a conflicting port:
```
goroutine 14 [running]:
code.cloudfoundry.org/lager.(*logger).Fatal(0xc420090360, 0x10bedda, 0x16, 0x114f4a0, 0xc42019a690, 0x0, 0x0, 0x0)
        /var/vcap/packages/guardian/src/code.cloudfoundry.org/lager/logger.go:152 +0x4d2
code.cloudfoundry.org/guardian/guardiancmd.startServer.func1(0xc4200ef1e0, 0x1168840, 0xc420090360)
        /var/vcap/packages/guardian/src/code.cloudfoundry.org/guardian/guardiancmd/command.go:584 +0x88
created by code.cloudfoundry.org/guardian/guardiancmd.startServer
        /var/vcap/packages/guardian/src/code.cloudfoundry.org/guardian/guardiancmd/command.go:582 +0x2f9
panic: listen tcp 127.0.0.1:7777: bind: address already in use 
```
monit summary after stop:
```
dev-worker/87896566-0519-4122-894b-85c68ac582c0:/var/vcap/bosh_ssh/bosh_f0959e3fbcdc466# monit summary
The Monit daemon 5.2.5 uptime: 41m

Process 'beacon'                    not monitored
Process 'baggageclaim'              not monitored
Process 'garden'                    not monitored
Process 'blackbox'                  not monitored
Process 'telegraf'                  running
Process 'datadog-agent'             running
Process 'dd-agent-process-agent'    running
System 'system_localhost'           running
```
port use:
```
dev-worker/87896566-0519-4122-894b-85c68ac582c0:/var/vcap/bosh_ssh/bosh_f0959e3fbcdc466# lsof -i -P -n | grep LISTEN
rpcbind     763                 root    8u  IPv4  14834      0t0  TCP *:111 (LISTEN)
rpc.statd   807                statd    8u  IPv4   8318      0t0  TCP *:51146 (LISTEN)
bosh-agen  1248                 root    5u  IPv4  14199      0t0  TCP 127.0.0.1:2825 (LISTEN)
sshd       1758                 root    3u  IPv4  12628      0t0  TCP *:22 (LISTEN)
monit      2745                 root    5u  IPv4  48632      0t0  TCP 127.0.0.1:2822 (LISTEN)
gdn        9703                 root    9u  IPv4  26435      0t0  TCP 127.0.0.1:7777 (LISTEN)
agent     20198                 vcap    5u  IPv4  48738      0t0  TCP 127.0.0.1:15000 (LISTEN)
agent     20198                 vcap    6u  IPv4  45719      0t0  TCP 127.0.0.1:15001 (LISTEN)
process-a 20258                 vcap    6u  IPv4  50748      0t0  TCP 127.0.0.1:6062 (LISTEN) 
```

So, I had to kill all threads related to garden/worker, make sure port use was released, and then I could start the processes cleanly and complete a deployment without issue.

## Expected Results

processes to stop and ports to be released when a stop was issued

## Actual Results

Errors as shown above

## Version Info

* Concourse version: 3.13+
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Openstack
* Did this used to work? Yes and now intermittent

**Comment by xtremerui** [comment]
closing stale issue.
