### ISSUE TITLE
Index out of range when receiving wrong token

### ISSUE THREAD

**Issue by aepsil0n** [concourse/concourse#3028]
## Bug Report

For some reason (not sure which yet) I appear to get a broken token when logging in to my Concourse instance with fly.

## Steps to Reproduce

1. Try to login with fly: `fly -t something login -c http://yourserver:8080`
2. Get the server to answer with something invalid (again, don't know how I managed that).

## Expected Results

The fly CLI should give me an error message about an invalid token supplied by the server.

## Actual Results

The CLI crashes with this:

```
goroutine 1 [running]:
github.com/concourse/fly/commands.(*LoginCommand).authCodeGrant(0xca4900, 0xc042062100, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/var/vcap/data/worker/work/containers/00002i7nadb/tmp/build/734c03a2/concourse/src/github.com/concourse/fly/commands/login.go:203 +0x6c4
github.com/concourse/fly/commands.(*LoginCommand).Execute(0xca4900, 0xc0420a2e10, 0x0, 0x5, 0xca4900, 0x1)
        C:/var/vcap/data/worker/work/containers/00002i7nadb/tmp/build/734c03a2/concourse/src/github.com/concourse/fly/commands/login.go:120 +0x603
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc042104c00, 0xc04208c010, 0x5, 0x7, 0x8f31e0, 0xc0421a93f0, 0xc042081f28, 0x8902c6, 0xc04211a7e0)
        C:/var/vcap/data/worker/work/containers/00002i7nadb/tmp/build/734c03a2/concourse/src/github.com/jessevdk/go-flags/parser.go:316 +0x7e4
github.com/jessevdk/go-flags.(*Parser).Parse(0xc042104c00, 0x9c08dd, 0x8, 0xc04208c800, 0x0, 0xc0420595a0)
        C:/var/vcap/data/worker/work/containers/00002i7nadb/tmp/build/734c03a2/concourse/src/github.com/jessevdk/go-flags/parser.go:186 +0x78
main.main()
        C:/var/vcap/data/worker/work/containers/00002i7nadb/tmp/build/734c03a2/concourse/src/github.com/concourse/fly/main.go:24 +0x112
```

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Azure
* Browser (if applicable): Firefox
* Did this used to work? Not that I know of.

**Comment by aepsil0n** [comment]
I might have to add another bug, because I do not understand why the web instance gives me a token with no spaces in it, which on first glance seems to lead to the crash in commands/login.go:203. Nonetheless, I think the fly CLI should handle this more gracefully. There is a check for the command line input, but not for the message from the server.

**Comment by aepsil0n** [comment]
Upon further investigation, I managed to login semi-automatically. Apparently, on the first try, the browser automatically redirected me to a success page without prompting me for username and password.

**Comment by taylorsilva** [comment]
# Issue Bankruptcy

This issue is being closed as part of 2025's **Issue Bankruptcy** declaration. [See here for details](https://blog.concourse-ci.org/posts/2025-01-06-concourse-2024-review/)

If you think this issue still has merit then feel free to open a new issue and reference this one.
