### ISSUE TITLE
Segmentation fault when attempting to add a local user

### ISSUE THREAD

**Issue by nbraud** [concourse/concourse#3205]
## Bug Report

Attempting to use `concourse web --add-local-user` triggered a segfault.

## Steps to Reproduce

On a Concourse installation running under Docker:
```
$ docker exec -t concourse_concourse_1 concourse web --add-local-user test:bark
```

## Expected Results

User successfully added.

## Actual Results

```
$ docker exec -t concourse_concourse_1 concourse web --add-local-user test:bark
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfe3485]

goroutine 1 [running]:
crypto/rsa.(*PrivateKey).Public(0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/rsa/rsa.go:100 +0x5
golang.org/x/crypto/ssh.NewSignerFromSigner(0x7f39e8416410, 0xc00000e898, 0xc00000e898, 0x7f39e8416410, 0xc00000e898, 0xe8af01)
        /tmp/build/9674af12/concourse/src/golang.org/x/crypto/ssh/keys.go:681 +0x35
golang.org/x/crypto/ssh.NewSignerFromKey(0x2a2ec40, 0xc00000e898, 0xe8afc8, 0x30, 0x2b17280, 0xc00149f408)
        /tmp/build/9674af12/concourse/src/golang.org/x/crypto/ssh/keys.go:656 +0x16a
github.com/concourse/tsa/tsacmd.(*TSACommand).configureSSHServer(0xc000668f20, 0xc00030e7e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00012e8c0, 0x7, ...)
        /tmp/build/9674af12/concourse/src/github.com/concourse/tsa/tsacmd/command.go:197 +0x167
github.com/concourse/tsa/tsacmd.(*TSACommand).Runner(0xc000668f20, 0xc000cc57a0, 0x0, 0x3, 0x17dbf3e0, 0xc0076c6060, 0x0, 0x0)
        /tmp/build/9674af12/concourse/src/github.com/concourse/tsa/tsacmd/command.go:95 +0x249
main.(*WebCommand).Runner(0xc000840708, 0xc000cc57a0, 0x0, 0x3, 0x2, 0x5, 0xc000c7d750, 0xc0003c5e80)
        /tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/web.go:67 +0x132
main.(*WebCommand).Execute(0xc000840708, 0xc000cc57a0, 0x0, 0x3, 0x28fdf00, 0x2b849a0)
        /tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/web.go:42 +0x5c
github.com/vito/twentythousandtonnesofcrudeoil.installEnv.func2(0x7f39e8485900, 0xc000840708, 0xc000cc57a0, 0x0, 0x3, 0x1, 0x0)
        /tmp/build/9674af12/concourse/src/github.com/vito/twentythousandtonnesofcrudeoil/environment.go:40 +0x8a
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0005cae40, 0xc00004c0d0, 0x3, 0x3, 0xc000a6f880, 0x20fe7bf, 0xc0005cae40, 0x2bc8113, 0xa)
        /tmp/build/9674af12/concourse/src/github.com/jessevdk/go-flags/parser.go:314 +0x7bc
github.com/jessevdk/go-flags.(*Parser).Parse(0xc0005cae40, 0x2bc8113, 0xa, 0xc000361600, 0x0, 0x0)
        /tmp/build/9674af12/concourse/src/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
        /tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/main.go:33 +0x19e
```

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): Docker
* Did this used to work? Unknown

**Comment by cirocosta** [comment]
Hi @nbraud ,

Thanks for submitting the issue! Although there's the panic happening when running the binary, I think this is related to something else that is not particularly related to the addition of local users (but something more like https://github.com/concourse/concourse/issues/2526#issuecomment-447499597).

Were you trying to add a local user to a Concourse instance that was already running? If so, make sure you append the user you want to add to the list of arguments you pass at the first initialization of concourse.

For instance, to have two users:

```
concourse web --add-local-user foo:bar --add-local-user caz:baz
```

instead of

```
concourse web --add-local-user foo:bar
concourse web  --add-local-user caz:baz
```

If that's not the case, please let me know!

Hope it helps,
Thx!
