### ISSUE TITLE
Is there any way to deploy via docker-compose?

### ISSUE THREAD

**Issue by ndarilek** [concourse/concourse#329]
Found Concourse on the recent Hackernews thread so I went straight to the binary release referenced therein. I don't have a bunch of spare VM capacity, but what I do have is all managed via Docker so I really don't want to use another deployment system, cool though it may be.

I'm trying to create a Docker/Compose-based setup. Thus far I have this in my Dockerfile:

```
FROM debian:latest
ADD https://github.com/concourse/concourse/releases/download/v0.76.0/concourse_linux_amd64 /usr/local/bin/concourse
RUN chmod +x /usr/local/bin/concourse
ENTRYPOINT ["/usr/local/bin/concourse"]
```

And this in docker-compose.yml:

```
postgres:
  image: postgres:latest
  environment:
    POSTGRES_PASSWORD: password

tsa:
  build: .
  links:
    - postgres
  ports:
    - 8080:8080
  volumes:
    - .:/var/lib/concourse
  command: web --tsa-host-key /var/lib/concourse/host_key --tsa-authorized-keys /var/lib/concourse/authorized_worker_keys --session-signing-key /var/lib/concourse/session_signing_key --basic-auth-username user --basic-auth-password password --postgres-data-source postgres://postgres:password@postgres/postgres?sslmode=disable --external-url http://localhost:8080

worker:
  build: .
  links:
    - tsa
  volumes:
    - .:/var/lib/concourse
    - /var/run/docker.sock:/var/run/docker.sock
  privileged: true
  command: worker --tsa-public-key /var/lib/concourse/host_key.pub --tsa-worker-private-key /var/lib/concourse/worker_key  --tsa-host tsa --work-dir /srv
```

My hope was to give the worker container all privileges and bindmount the Docker socket on the host. I'm currently doing something similar for Jenkins, though it's much more complex than needs dictate since almost everything I build is Docker-based.

Unfortunately, I'm hitting the following error when running `docker-compose up`. I don't understand the bit about not getting a whole bunch of graph drivers. `docker info` claims my host is using the BTRFS driver. Seems like it should just defer to the host if I'm bindmounting the host's socket in. It would be nice if I could spin up builder VMs/servers with lots of CPU/RAM and simply delegate Concourse' Docker capability detection to those hosts:

```
Starting concourse_postgres_1
Starting concourse_tsa_1
Starting concourse_worker_1
Attaching to concourse_postgres_1, concourse_tsa_1, concourse_worker_1
[36mpostgres_1 | [0mLOG:  database system was shut down at 2016-03-27 01:59:03 UTC
[36mpostgres_1 | [0mLOG:  MultiXact member wraparound protections are now enabled
[36mpostgres_1 | [0mLOG:  database system is ready to accept connections
[36mpostgres_1 | [0mLOG:  autovacuum launcher started
[33mtsa_1      | [0m{"timestamp":"1459044271.055514812","source":"atc","message":"atc.db.migrations.migration-lock-acquired","log_level":1,"data":{"session":"1"}}
[33mtsa_1      | [0m{"timestamp":"1459044271.416863203","source":"tsa","message":"tsa.listening","log_level":1,"data":{}}
[33mtsa_1      | [0m{"timestamp":"1459044271.417348623","source":"atc","message":"atc.listening","log_level":1,"data":{"debug":"127.0.0.1:8079","web":"0.0.0.0:8080"}}
[32mworker_1   | [0m{"timestamp":"1459044286.023603678","source":"garden-linux","message":"garden-linux.failed-to-parse-pool-state","log_level":2,"data":{"error":"openning state file: open /srv/linux/state/port_pool.json: no such file or directory"}}
[32mworker_1   | [0m{"timestamp":"1459044286.024022102","source":"garden-linux","message":"garden-linux.unsupported-graph-driver","log_level":1,"data":{"name":"vfs"}}
[32mworker_1   | [0mtime="2016-03-27T02:04:46Z" level=error msg="Failed to GetDriver graph btrfs /srv/linux/graph" 
[32mworker_1   | [0mtime="2016-03-27T02:04:46Z" level=error msg="Failed to GetDriver graph zfs /srv/linux/graph" 
[32mworker_1   | [0mtime="2016-03-27T02:04:46Z" level=error msg="Failed to GetDriver graph devicemapper /srv/linux/graph" 
[32mworker_1   | [0mtime="2016-03-27T02:04:46Z" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded." 
[32mworker_1   | [0m{"timestamp":"1459044286.024624586","source":"garden-linux","message":"garden-linux.retain.starting","log_level":1,"data":{"session":"10"}}
[32mworker_1   | [0m{"timestamp":"1459044286.024943590","source":"garden-linux","message":"garden-linux.retain.retained","log_level":1,"data":{"session":"10"}}
[32mworker_1   | [0m{"timestamp":"1459044287.595874548","source":"baggageclaim","message":"baggageclaim.listening","log_level":1,"data":{"addr":"0.0.0.0:7788"}}
[32mworker_1   | [0m{"timestamp":"1459044287.864905119","source":"garden-linux","message":"garden-linux.failed-to-set-up-backend","log_level":3,"data":{"error":"exit status 127","trace":"goroutine 1 [running, locked to thread]:\ngithub.com/pivotal-golang/lager.(*logger).Fatal(0xc82000ec60, 0xc1d160, 0x18, 0x7f7ee3934328, 0xc82021a780, 0x0, 0x0, 0x0)\n\t/tmp/build/9674af12/garden-linux-release/src/github.com/pivotal-golang/lager/logger.go:131 +0xc5\nmain.main()\n\t/tmp/build/9674af12/garden-linux-release/src/github.com/cloudfoundry-incubator/garden-linux/main.go:507 +0x3b14\n"}}
[32mworker_1   | [0mpanic: exit status 127
[32mworker_1   | [0m
[32mworker_1   | [0mgoroutine 1 [running, locked to thread]:
[32mworker_1   | [0mpanic(0xb57560, 0xc82021a780)
[32mworker_1   | [0m	/usr/local/go/src/runtime/panic.go:464 +0x3e6
[32mworker_1   | [0mgithub.com/pivotal-golang/lager.(*logger).Fatal(0xc82000ec60, 0xc1d160, 0x18, 0x7f7ee3934328, 0xc82021a780, 0x0, 0x0, 0x0)
[32mworker_1   | [0m	/tmp/build/9674af12/garden-linux-release/src/github.com/pivotal-golang/lager/logger.go:152 +0x698
[32mworker_1   | [0mmain.main()
[32mworker_1   | [0m	/tmp/build/9674af12/garden-linux-release/src/github.com/cloudfoundry-incubator/garden-linux/main.go:507 +0x3b14
[33mtsa_1      | [0m{"timestamp":"1459044287.916075468","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"session":"1","type":"keepalive"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.916302443","source":"tsa","message":"tsa.connection.channel-request","log_level":1,"data":{"session":"1","type":"exec"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.916809559","source":"tsa","message":"tsa.connection.tcpip-forward.forwarding-tcpip","log_level":1,"data":{"requested-bind-addr":"0.0.0.0:7777","session":"1.2"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.916914940","source":"tsa","message":"tsa.connection.forward-worker.forwarded-tcpip","log_level":1,"data":{"bound-port":37455,"session":"1.1"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.917042255","source":"tsa","message":"tsa.connection.tcpip-forward.forwarding-tcpip","log_level":1,"data":{"requested-bind-addr":"0.0.0.0:7788","session":"1.3"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.917137384","source":"tsa","message":"tsa.connection.forward-worker.forwarded-tcpip","log_level":1,"data":{"bound-port":38986,"session":"1.1"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.917503834","source":"tsa","message":"tsa.connection.forward-worker.register.start","log_level":1,"data":{"session":"1.1.4","worker-address":"127.0.0.1:37455","worker-platform":"linux","worker-tags":""}}
[32mworker_1   | [0m{"timestamp":"1459044287.917503834","source":"tsa","message":"tsa.connection.forward-worker.register.start","log_level":1,"data":{"session":"1.1.4","worker-address":"127.0.0.1:37455","worker-platform":"linux","worker-tags":""}}
[33mtsa_1      | [0m{"timestamp":"1459044287.918128490","source":"tsa","message":"tsa.connection.tcpip-forward.failed-to-open-channel","log_level":2,"data":{"error":"ssh: unexpected packet in response to channel open: \u003cnil\u003e","session":"1.2"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.918167353","source":"tsa","message":"tsa.connection.forward-worker.connection-closed","log_level":2,"data":{"error":"EOF","session":"1.1"}}
[32mworker_1   | [0mExit trace for group:
[32mworker_1   | [0mgarden exited with error: exit status 2
[32mworker_1   | [0mbaggageclaim exited with nil
[32mworker_1   | [0mbeacon exited with nil
[32mworker_1   | [0m
[33mtsa_1      | [0m{"timestamp":"1459044287.918196917","source":"tsa","message":"tsa.connection.cleanup.interrupting","log_level":0,"data":{"session":"1.4"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.918217897","source":"tsa","message":"tsa.connection.cleanup.interrupting","log_level":0,"data":{"session":"1.4"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.918234348","source":"tsa","message":"tsa.connection.forward-worker.register.failed-to-fetch-containers","log_level":2,"data":{"error":"Get http://api/containers: read tcp 127.0.0.1:43456-\u003e127.0.0.1:37455: read: connection reset by peer","session":"1.1.4"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.918259859","source":"tsa","message":"tsa.connection.forward-worker.register.done","log_level":1,"data":{"session":"1.1.4","worker-address":"127.0.0.1:37455","worker-platform":"linux","worker-tags":""}}
[33mtsa_1      | [0m{"timestamp":"1459044287.918238640","source":"tsa","message":"tsa.connection.cleanup.interrupting","log_level":0,"data":{"session":"1.4"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.918277979","source":"tsa","message":"tsa.connection.tcpip-forward.failed-to-accept","log_level":2,"data":{"error":"accept tcp [::]:38986: use of closed network connection","session":"1.3"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.918318748","source":"tsa","message":"tsa.connection.tcpip-forward.failed-to-accept","log_level":2,"data":{"error":"accept tcp [::]:37455: use of closed network connection","session":"1.2"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.918364763","source":"tsa","message":"tsa.connection.cleanup.process-exited-successfully","log_level":0,"data":{"session":"1.4"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.918384314","source":"tsa","message":"tsa.connection.cleanup.process-exited-successfully","log_level":0,"data":{"session":"1.4"}}
[33mtsa_1      | [0m{"timestamp":"1459044287.918402195","source":"tsa","message":"tsa.connection.cleanup.process-exited-successfully","log_level":0,"data":{"session":"1.4"}}
[32mconcourse_worker_1 exited with code 1
[0m[33mtsa_1      | [0m{"timestamp":"1459044301.417274714","source":"atc","message":"atc.lost-and-found.lease-invalidate-cache.tick","log_level":1,"data":{"session":"6.1"}}
[33mtsa_1      | [0m{"timestamp":"1459044301.426344633","source":"atc","message":"atc.lost-and-found.lease-invalidate-cache.collecting-baggage","log_level":1,"data":{"session":"6.1"}}
[33mtsa_1      | [0m{"timestamp":"1459044301.426389933","source":"atc","message":"atc.baggage-collector.collect","log_level":1,"data":{"session":"7"}}
[33mtsa_1      | [0m{"timestamp":"1459044331.417405128","source":"atc","message":"atc.lost-and-found.lease-invalidate-cache.tick","log_level":1,"data":{"session":"6.2"}}
[33mtsa_1      | [0m{"timestamp":"1459044331.431194782","source":"atc","message":"atc.lost-and-found.lease-invalidate-cache.collecting-baggage","log_level":1,"data":{"session":"6.2"}}
[33mtsa_1      | [0m{"timestamp":"1459044331.431253195","source":"atc","message":"atc.baggage-collector.collect","log_level":1,"data":{"session":"7"}}
[33mtsa_1      | [0m{"timestamp":"1459044361.417612076","source":"atc","message":"atc.lost-and-found.lease-invalidate-cache.tick","log_level":1,"data":{"session":"6.3"}}
Stopping concourse_tsa_1 ... 
Stopping concourse_postgres_1 ... 
[2A[2K
Stopping concourse_tsa_1 ... done
[2B[1A[2K
Stopping concourse_postgres_1 ... done
[1BGracefully stopping... (press Ctrl+C again to force)
```

Is there just no way to run this within Docker, even with `--privileged` and bindmounting the Docker socket from the host? I suppose I could give it its own VM if absolutely needed, but I like the idea of just scaling up worker nodes in containers via my existing Rancher-based setup, which makes that incredibly easy.

Thanks.

**Comment by vito** [comment]
Hey, thanks for trying Concourse out and spending some time to get a Docker setup going. At some point we'll start publishing Docker images ourselves, but for now with our limited resources we've just opted for the binaries.

One critical point of clarification is that Concourse doesn't talk to a Docker daemon for containerization: it talks to [Garden](https://github.com/cloudfoundry-incubator/garden), or more specifically in this case, [Garden Linux](https://github.com/cloudfoundry-incubator/garden-linux). So there won't be a way to just reuse the host's Docker.

Running Garden Linux in Docker is possible, but I think it'll take a bit more investigation to get things up to speed, which I'll check out pretty soon.

One question I have: which Linux distro and kernel version are you running? Both of these factors determine which graph drivers will be supported. Garden Linux is battle-hardened with `aufs` but should support `overlay`. Unfortunately it's not currently built with `btrfs` support, but I may just fix that myself (it's just a matter of importing the Docker graph package for it and building it with the headers available).

**Comment by ndarilek** [comment]
Cool, thanks for the heads-up. Where can I follow this progress? Would 
this issue be the best place or is there another?

My laptop is currently on Fedora 23 with a BTRFS root filesystem 
Production VMs are Ubuntu 14.04 with aufs. BTRFS isn't essential, I just 
hit it because I was trying to get a worker running and bindmounted the 
Docker socket. Sounds like since that isn't used I should remove it. In 
any case, for local use I can probably stick with Vagrant. Just wanted 
to get Concourse running on my Rancher-based installation and compose is 
a good way to jumpstart that.

**Comment by ndarilek** [comment]
Sorry, saw you also asked for my kernel version:

Linux nolan-helix 4.4.6-300.fc23.x86_64 #1 SMP Wed Mar 16 22:10:37 UTC 
2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by holstvoogd** [comment]
I've been trying to get concourse to run in kubernetes and ran into an issue that seems related:

The atc/tsa starts up fine, no issues there. And the worker does start, but then crashes:

```
{"timestamp":"1464183080.524900675","source":"garden-linux","message":"garden-linux.failed-to-parse-pool-state","log_level":2,"data":{"error":"openning state file: open /opt/concourse/worker/linux/state/port_pool.json: no such file or directory"}}
ERRO[0000] Failed to GetDriver graph btrfs /opt/concourse/worker/linux/graph
ERRO[0000] Failed to GetDriver graph zfs /opt/concourse/worker/linux/graph
ERRO[0000] Failed to GetDriver graph devicemapper /opt/concourse/worker/linux/graph
{"timestamp":"1464183080.527908802","source":"garden-linux","message":"garden-linux.unsupported-graph-driver","log_level":1,"data":{"name":"overlay"}}
{"timestamp":"1464183080.536214828","source":"garden-linux","message":"garden-linux.retain.starting","log_level":1,"data":{"session":"10"}}
{"timestamp":"1464183080.536463499","source":"garden-linux","message":"garden-linux.retain.retained","log_level":1,"data":{"session":"10"}}
{"timestamp":"1464183080.589316130","source":"baggageclaim","message":"baggageclaim.listening","log_level":1,"data":{"addr":"0.0.0.0:7788"}}
{"timestamp":"1464183080.632028103","source":"tsa","message":"tsa.connection.forward-worker.register.start","log_level":1,"data":{"session":"24.1.4","worker-address":"127.0.0.1:38579","worker-platform":"linux","worker-tags":""}}
2016/05/25 13:31:20 failed to forward remote connection: dial tcp 0.0.0.0:7777: getsockopt: connection refused
{"timestamp":"1464183080.636219978","source":"tsa","message":"tsa.connection.forward-worker.register.failed-to-fetch-containers","log_level":2,"data":{"error":"Get http://api/containers: EOF","session":"24.1.4"}}
{"timestamp":"1464183080.636786222","source":"tsa","message":"tsa.connection.forward-worker.register.done","log_level":1,"data":{"session":"24.1.4","worker-address":"127.0.0.1:38579","worker-platform":"linux","worker-tags":""}}
{"timestamp":"1464183080.661351919","source":"garden-linux","message":"garden-linux.failed-to-set-up-backend","log_level":3,"data":{"error":"exit status 32","trace":"goroutine 1 [running, locked to thread]:\ngithub.com/pivotal-golang/lager.(*logger).Fatal(0xc8201ca1e0, 0xc1d180, 0x18, 0x7fe0700fdcd8, 0xc8202401a0, 0x
0, 0x0, 0x0)\n\t/tmp/build/9674af12/garden-linux-release/src/github.com/pivotal-golang/lager/logger.go:131 +0xc5\nmain.main()\n\t/tmp/build/9674af12/garden-linux-release/src/github.com/cloudfoundry-incubator/garden-linux/main.go:507 +0x3b53\n"}}
panic: exit status 32

goroutine 1 [running, locked to thread]:
panic(0xb57520, 0xc8202401a0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/pivotal-golang/lager.(*logger).Fatal(0xc8201ca1e0, 0xc1d180, 0x18, 0x7fe0700fdcd8, 0xc8202401a0, 0x0, 0x0, 0x0)
	/tmp/build/9674af12/garden-linux-release/src/github.com/pivotal-golang/lager/logger.go:152 +0x698
main.main()
	/tmp/build/9674af12/garden-linux-release/src/github.com/cloudfoundry-incubator/garden-linux/main.go:507 +0x3b53
Exit trace for group:
garden exited with error: exit status 2
baggageclaim exited with nil
beacon exited with nil
```
It get weird though when I spin up the container with a tty & bash and manually try to start the worker. It consistently starts the third time and every time after that. I've tried this about 8 times now with a new container, doesn't matter if I do it fast or slow, the first two tries consistently fail with a garden-linux.failed-to-set-up-backend (same as your compose run).

I'm still investigating what is changing between runs, there must be some change of state between the runs...

**Comment by overdrive3000** [comment]
I'm having exactly the  same issue as @holstvoogd.

I'm using CoreOS stable 1010.5.0
Kernel: 4.5.0-coreos-r1

**Comment by holstvoogd** [comment]
I've switched to a v1.3.0 release candidate, that doesn't seem to have this issue & starts up fine.

**Comment by overdrive3000** [comment]
@holstvoogd I did the same. It started find fine, but when I try to execute a Job it throw “volume graph is disabled”.

Was you able to run a job with version 1.3?

By the way. What distro are you using ?

**Comment by vito** [comment]
@overdrive3000 make sure you're using `image_resource` and not `image: docker:///...`

**Comment by overdrive3000** [comment]
Hello @vito 

Yes. I'm using image_resource. Indeed I'm using a sample pipeline configuration from the concourse tutorial.

```
---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
- name: resource-gist
  type: git
  source:
    branch: master
    uri: {{gist-url}}
    private_key: {{github-private-key}}

jobs:
- name: job-bump-date
  serial: true
  plan:
  - get: resource-tutorial
  - get: resource-gist
  - task: bump-timestamp-file
    file: resource-tutorial/12_publishing_outputs/bump-timestamp-file.yml
  - put: resource-gist
    params: {repository: updated-gist}

- name: job-show-date
  plan:
  - get: resource-tutorial
  - get: resource-gist
    passed: [job-bump-date]
    trigger: true
  - task: show-date
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
        - name: resource-gist
      run:
        path: cat
        args: [resource-gist/bumpme]
```

**Comment by vito** [comment]
@overdrive3000 Which job has the issue? Can you run `fly get-pipeline` and confirm that `image_resource` is present? If so, can you paste the logs from the `concourse worker` process?

**Comment by overdrive3000** [comment]
@vito In my previous test I was running the concourse ATC/TSA container with version 1.2 and the concourse worker container with version v1.3.0-rc.83.

I've tried running everything on version v1.3.0-rc.83 and seems to be working fine. I've just reproduced several jobs from the tutorial and all of them worked just fine.

Thanks.

**Comment by vito** [comment]
Ah that makes sense then. Yeah, the versions have to be in sync.

**Comment by mike0004** [comment]
I have the same error but running on Amazon Linux AMI. Concourse 1.2.0. 
Followed installation doc [here](https://concourse.ci/binaries.html).
Is the only solution to build the 1.3.0 rc? 
```
$ sudo /opt/concourse/concourse_linux_amd64 worker \
  --work-dir /opt/concourse/worker \
  --tsa-host 127.0.0.1 \
  --tsa-public-key /opt/concourse/host_key.pub \
  --tsa-worker-private-key /opt/concourse/worker_key

{"timestamp":"1465303496.879024744","source":"baggageclaim","message":"baggageclaim.listening","log_level":1,"data":{"addr":"0.0.0.0:7788"}}
{"timestamp":"1465303496.894922495","source":"garden-linux","message":"garden-linux.failed-to-parse-pool-state","log_level":2,"data":{"error":"openning state file: open /opt/concourse/worker/linux/state/port_pool.json: no such file or directory"}}
{"timestamp":"1465303496.896860361","source":"tsa","message":"tsa.connection.forward-worker.register.start","log_level":1,"data":{"session":"6.1.4","worker-address":"127.0.0.1:43650","worker-platform":"linux","worker-tags":""}}
2016/06/07 12:44:56 failed to forward remote connection: dial tcp 0.0.0.0:7777: getsockopt: connection refused
{"timestamp":"1465303496.897750616","source":"tsa","message":"tsa.connection.forward-worker.register.failed-to-fetch-containers","log_level":2,"data":{"error":"Get http://api/containers: EOF","session":"6.1.4"}}
{"timestamp":"1465303496.897830248","source":"tsa","message":"tsa.connection.forward-worker.register.done","log_level":1,"data":{"session":"6.1.4","worker-address":"127.0.0.1:43650","worker-platform":"linux","worker-tags":""}}
{"timestamp":"1465303496.898233891","source":"garden-linux","message":"garden-linux.unsupported-graph-driver","log_level":1,"data":{"name":"overlay"}}
{"timestamp":"1465303496.898746967","source":"garden-linux","message":"garden-linux.retain.starting","log_level":1,"data":{"session":"10"}}
{"timestamp":"1465303496.898826122","source":"garden-linux","message":"garden-linux.retain.retained","log_level":1,"data":{"session":"10"}}
{"timestamp":"1465303496.920161724","source":"garden-linux","message":"garden-linux.failed-to-set-up-backend","log_level":3,"data":{"error":"exit status 2","trace":"goroutine 1 [running, locked to thread]:\ngithub.com/pivotal-golang/lager.(*logger).Fatal(0xc820016c60, 0xc1d180, 0x18, 0x7fa537e71d68, 0xc8201faa20, 0x0, 0x0, 0x0)\n\t/tmp/build/9674af12/garden-linux-release/src/github.com/pivotal-golang/lager/logger.go:131 +0xc5\nmain.main()\n\t/tmp/build/9674af12/garden-linux-release/src/github.com/cloudfoundry-incubator/garden-linux/main.go:507 +0x3b53\n"}}
panic: exit status 2

goroutine 1 [running, locked to thread]:
panic(0xb57520, 0xc8201faa20)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/pivotal-golang/lager.(*logger).Fatal(0xc820016c60, 0xc1d180, 0x18, 0x7fa537e71d68, 0xc8201faa20, 0x0, 0x0, 0x0)
	/tmp/build/9674af12/garden-linux-release/src/github.com/pivotal-golang/lager/logger.go:152 +0x698
main.main()
	/tmp/build/9674af12/garden-linux-release/src/github.com/cloudfoundry-incubator/garden-linux/main.go:507 +0x3b53
Exit trace for group:
garden exited with error: exit status 2
baggageclaim exited with nil
beacon exited with nil

```

**Comment by vito** [comment]
Yes, you should use the 1.3 RCs. We'll have it shipped as soon as we can (we're still waiting on another team).
