### ISSUE TITLE
ATC segfaults until `web` job restarted

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [concourse/concourse#3519]
## Bug Report

All concourse jobs were stuck in `pending` state. 
`web.stderr.log` contains:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x8cc6bd]

goroutine 347 [running]:
github.com/concourse/concourse/atc/db.(*build).SaveOutput(0xc000cb7400, 0x264a1c0, 0xc003f05500, 0xc000a2fee0, 0x4, 0xc001165770, 0xc000968580, 0x3, 0x4, 0xc0024acab0, ...)
	/tmp/build/70f2e240/concourse/atc/db/build.go:819 +0x10ad
github.com/concourse/concourse/atc/exec.(*PutStep).Run(0xc00095e700, 0x262a520, 0xc000953800, 0x2644580, 0xc00096a340, 0x501, 0x1899c76)
	/tmp/build/70f2e240/concourse/atc/exec/put_step.go:175 +0xf13
github.com/concourse/concourse/atc/exec.LogErrorStep.Run(0x2601060, 0xc00095e700, 0x7f9028707088, 0xc00096c040, 0x262a520, 0xc000953800, 0x2644580, 0xc00096a340, 0x1929100, 0xc000cb2ce0)
	/tmp/build/70f2e240/concourse/atc/exec/log_error_step.go:30 +0xf3
github.com/concourse/concourse/atc/exec.OnSuccessStep.Run(0x2608f60, 0xc00096a0a0, 0x2608f60, 0xc00096a0e0, 0x262a520, 0xc000953800, 0x2644580, 0xc00096a340, 0xc000ca1ca0, 0x4)
	/tmp/build/70f2e240/concourse/atc/exec/on_success.go:29 +0x60
github.com/concourse/concourse/atc/exec.AggregateStep.Run.func1(0xc000966ae0, 0x2609020, 0xc00096a100, 0x262a520, 0xc000953800, 0x2644580, 0xc00096a340)
	/tmp/build/70f2e240/concourse/atc/exec/aggregate.go:25 +0x63
created by github.com/concourse/concourse/atc/exec.AggregateStep.Run
	/tmp/build/70f2e240/concourse/atc/exec/aggregate.go:24 +0xf6
```
Restarting atc resolved the issue.

## Version Info

* Concourse version: 5.0.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP

**Comment by vito** [comment]
Same as #3582
