### ISSUE TITLE
concourse web crashes with SIGSEGV every 15 seconds

### ISSUE THREAD

**Issue by odormond** [concourse/concourse#3582]
## Bug Report

The concourse web suddenly crashed with a segmentation violation and continued to do so with every restart after ~15 seconds until workers were removed by force.

Here is the first traceback logged:
```
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x8cc6bd]
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: goroutine 34486795 [running]:
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: github.com/concourse/concourse/atc/db.(*build).SaveOutput(0xc006003b80, 0x264a220, 0x3801988, 0xc003623c88, 0x4, 0xc0082d5290, 0xc0025e0100, 0x5, 0x8, 0xc005aa8810, ...)
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: #011/tmp/build/70f2e240/concourse/atc/db/build.go:819 +0x10ad
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: github.com/concourse/concourse/atc/exec.(*PutStep).Run(0xc008bcca80, 0x262a4a0, 0xc000040038, 0x2644580, 0xc005cbf2c0, 0x100, 0xc007957dc8)
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: #011/tmp/build/70f2e240/concourse/atc/exec/put_step.go:175 +0xf13
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: github.com/concourse/concourse/atc/exec.LogErrorStep.Run(0x2601060, 0xc008bcca80, 0x7f8598146168, 0xc00685be00, 0x262a4a0, 0xc000040038, 0x2644580, 0xc005cbf2c0, 0xc0023636c0, 0xc007957e78)
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: #011/tmp/build/70f2e240/concourse/atc/exec/log_error_step.go:30 +0xf3
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: github.com/concourse/concourse/atc/exec.OnSuccessStep.Run(0x2608f60, 0xc005cbf1e0, 0x2608f60, 0xc005cbf240, 0x262a4a0, 0xc000040038, 0x2644580, 0xc005cbf2c0, 0x25ec4c0, 0xc0000481f0)
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: #011/tmp/build/70f2e240/concourse/atc/exec/on_success.go:29 +0x60
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: github.com/concourse/concourse/atc/exec.EnsureStep.Run(0x2609020, 0xc005cbf160, 0x2609020, 0xc005cbf260, 0x262a520, 0xc0087dc600, 0x2644580, 0xc005cbf2c0, 0xc0000481f0, 0x0)
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: #011/tmp/build/70f2e240/concourse/atc/exec/ensure_step.go:44 +0xfa
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: github.com/concourse/concourse/atc/engine.(*execBuild).Resume.func1(0xc001eef080, 0x2608e60, 0xc005cbf280, 0x262a520, 0xc0087dc600, 0x2644580, 0xc005cbf2c0)
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: #011/tmp/build/70f2e240/concourse/atc/engine/exec_engine.go:158 +0x63
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: created by github.com/concourse/concourse/atc/engine.(*execBuild).Resume
Mar 22 12:14:49 ip-10-43-2-39 concourse[31806]: #011/tmp/build/70f2e240/concourse/atc/engine/exec_engine.go:157 +0x223
Mar 22 12:14:49 ip-10-43-2-39 systemd[1]: concourse-web.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 22 12:14:49 ip-10-43-2-39 systemd[1]: concourse-web.service: Failed with result 'exit-code'.
Mar 22 12:14:49 ip-10-43-2-39 systemd[1]: concourse-web.service: Service hold-off time over, scheduling restart.
Mar 22 12:14:49 ip-10-43-2-39 systemd[1]: concourse-web.service: Scheduled restart job, restart counter is at 1.
Mar 22 12:14:49 ip-10-43-2-39 systemd[1]: Stopped concourse web.
Mar 22 12:14:49 ip-10-43-2-39 systemd[1]: Started concourse web.
```
Then the subsequent tracebacks are slightly longer then the first but they are all identical. I'm just coping the first two here:
```
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x8cc6bd]
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: goroutine 2050 [running]:
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: github.com/concourse/concourse/atc/db.(*build).SaveOutput(0xc000ab2140, 0x264a1c0, 0xc001f0a1e0, 0xc002821d88, 0x4, 0xc006634e10, 0xc001b9b180, 0x5, 0x8, 0xc006635830, ...)
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: #011/tmp/build/70f2e240/concourse/atc/db/build.go:819 +0x10ad
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: github.com/concourse/concourse/atc/exec.(*PutStep).Run(0xc000669500, 0x262a520, 0xc002a31dd0, 0x2644580, 0xc0023dea60, 0xc0026c9001, 0xc000dbb200)
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: #011/tmp/build/70f2e240/concourse/atc/exec/put_step.go:175 +0xf13
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: github.com/concourse/concourse/atc/exec.LogErrorStep.Run(0x2601060, 0xc000669500, 0x7f4be99a0908, 0xc002727bc0, 0x262a520, 0xc002a31dd0, 0x2644580, 0xc0023dea60, 0x8, 0xc0019c2420)
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: #011/tmp/build/70f2e240/concourse/atc/exec/log_error_step.go:30 +0xf3
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: github.com/concourse/concourse/atc/exec.OnSuccessStep.Run(0x2608f60, 0xc0023de420, 0x2608f60, 0xc0023de480, 0x262a520, 0xc002a31dd0, 0x2644580, 0xc0023dea60, 0xc0019c2510, 0x0)
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: #011/tmp/build/70f2e240/concourse/atc/exec/on_success.go:29 +0x60
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: github.com/concourse/concourse/atc/exec.OnSuccessStep.Run(0x2609020, 0xc0023de4a0, 0x2609020, 0xc0023de3a0, 0x262a520, 0xc002a31dd0, 0x2644580, 0xc0023dea60, 0x2, 0x2)
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: #011/tmp/build/70f2e240/concourse/atc/exec/on_success.go:29 +0x60
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: github.com/concourse/concourse/atc/exec.OnFailureStep.Run(0x2609020, 0xc0023de4c0, 0x2609020, 0xc0023de780, 0x262a520, 0xc002a31dd0, 0x2644580, 0xc0023dea60, 0xc00083a288, 0xc0019c26bc)
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: #011/tmp/build/70f2e240/concourse/atc/exec/on_failure.go:29 +0x60
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: github.com/concourse/concourse/atc/exec.OnSuccessStep.Run(0x2608fe0, 0xc0023de7a0, 0x2609020, 0xc0023de8a0, 0x262a520, 0xc002a31dd0, 0x2644580, 0xc0023dea60, 0x264a1c0, 0xc00229f380)
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: #011/tmp/build/70f2e240/concourse/atc/exec/on_success.go:29 +0x60
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: github.com/concourse/concourse/atc/exec.EnsureStep.Run(0x2609020, 0xc0023de900, 0x2609020, 0xc0023dea00, 0x262a520, 0xc002a31dd0, 0x2644580, 0xc0023dea60, 0xa7b0cd, 0xc0020e6e00)
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: #011/tmp/build/70f2e240/concourse/atc/exec/ensure_step.go:33 +0x69
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: github.com/concourse/concourse/atc/engine.(*execBuild).Resume.func1(0xc0023d1140, 0x2608e60, 0xc0023dea20, 0x262a520, 0xc002a31dd0, 0x2644580, 0xc0023dea60)
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: #011/tmp/build/70f2e240/concourse/atc/engine/exec_engine.go:158 +0x63
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: created by github.com/concourse/concourse/atc/engine.(*execBuild).Resume
Mar 22 12:15:01 ip-10-43-2-39 concourse[8684]: #011/tmp/build/70f2e240/concourse/atc/engine/exec_engine.go:157 +0x223
Mar 22 12:15:01 ip-10-43-2-39 systemd[1]: concourse-web.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```
```
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x8cc6bd]
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: goroutine 29201 [running]:
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: github.com/concourse/concourse/atc/db.(*build).SaveOutput(0xc00080fe00, 0x264a1c0, 0xc0071f8480, 0xc0085a1178, 0x4, 0xc0092b2870, 0xc0090d2100, 0x5, 0x8, 0xc0092b32c0, ...)
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: #011/tmp/build/70f2e240/concourse/atc/db/build.go:819 +0x10ad
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: github.com/concourse/concourse/atc/exec.(*PutStep).Run(0xc003d62c40, 0x262a520, 0xc008f9ddd0, 0x2644580, 0xc0037aa660, 0x1, 0x0)
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: #011/tmp/build/70f2e240/concourse/atc/exec/put_step.go:175 +0xf13
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: github.com/concourse/concourse/atc/exec.LogErrorStep.Run(0x2601060, 0xc003d62c40, 0x7f4c5402ba08, 0xc0090824c0, 0x262a520, 0xc008f9ddd0, 0x2644580, 0xc0037aa660, 0x1000, 0x0)
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: #011/tmp/build/70f2e240/concourse/atc/exec/log_error_step.go:30 +0xf3
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: github.com/concourse/concourse/atc/exec.OnSuccessStep.Run(0x2608f60, 0xc0037aa080, 0x2608f60, 0xc0037aa0e0, 0x262a520, 0xc008f9ddd0, 0x2644580, 0xc0037aa660, 0xc004581488, 0x568dcf)
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: #011/tmp/build/70f2e240/concourse/atc/exec/on_success.go:29 +0x60
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: github.com/concourse/concourse/atc/exec.OnSuccessStep.Run(0x2609020, 0xc0037aa100, 0x2609020, 0xc003755fe0, 0x262a520, 0xc008f9ddd0, 0x2644580, 0xc0037aa660, 0x6f1c5c, 0x0)
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: #011/tmp/build/70f2e240/concourse/atc/exec/on_success.go:29 +0x60
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: github.com/concourse/concourse/atc/exec.OnFailureStep.Run(0x2609020, 0xc0037aa120, 0x2609020, 0xc0037aa380, 0x262a520, 0xc008f9ddd0, 0x2644580, 0xc0037aa660, 0xc005b167e0, 0xc004581588)
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: #011/tmp/build/70f2e240/concourse/atc/exec/on_failure.go:29 +0x60
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: github.com/concourse/concourse/atc/exec.OnSuccessStep.Run(0x2608fe0, 0xc0037aa3a0, 0x2609020, 0xc0037aa4a0, 0x262a520, 0xc008f9ddd0, 0x2644580, 0xc0037aa660, 0xc0045816b0, 0x3)
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: #011/tmp/build/70f2e240/concourse/atc/exec/on_success.go:29 +0x60
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: github.com/concourse/concourse/atc/exec.EnsureStep.Run(0x2609020, 0xc0037aa4c0, 0x2609020, 0xc0037aa5e0, 0x262a520, 0xc008f9ddd0, 0x2644580, 0xc0037aa660, 0xc0015649c0, 0xc00583aa20)
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: #011/tmp/build/70f2e240/concourse/atc/exec/ensure_step.go:33 +0x69
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: github.com/concourse/concourse/atc/engine.(*execBuild).Resume.func1(0xc0090dcc00, 0x2608e60, 0xc0037aa620, 0x262a520, 0xc008f9ddd0, 0x2644580, 0xc0037aa660)
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: #011/tmp/build/70f2e240/concourse/atc/engine/exec_engine.go:158 +0x63
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: created by github.com/concourse/concourse/atc/engine.(*execBuild).Resume
Mar 22 12:15:19 ip-10-43-2-39 concourse[8731]: #011/tmp/build/70f2e240/concourse/atc/engine/exec_engine.go:157 +0x223
Mar 22 12:15:19 ip-10-43-2-39 systemd[1]: concourse-web.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

## Steps to Reproduce

I wish I could provide one but I have no clue why it happened.

## Expected Results

Continuous normal operation.

## Actual Results

Concourse web crashed and was restarted by systemd in a loop. The continuous restart had the effect to heavily load the database due to repeated startup and rollbacked transactions (as the crash cut the connection to the db while transactions were open, on average 6 of them each time).

From an outside point of view, the system almost stopped making progress.

## Additional Context

At the time of the first crash the system was in cruise mode. It had only 30 builds in flight at that time while it happily handled 45 an hour before. It had 49 workers running (19 Linux, 14 Windows, 16 macOS). The Linux and Windows nodes are handled by AWS ASGs whose behaviour during the incident can been seen on the following graph:
![image](https://user-images.githubusercontent.com/6637092/54909445-84de8480-4eea-11e9-8ed8-3cce4b8d1f6f.png)

The following screenshot shows the cpu usage of the database in orange and concourse web in cyan:
![image](https://user-images.githubusercontent.com/6637092/54902482-d7fc0b80-4ed9-11e9-82ee-6a4d6279d6ee.png)

Concourse web was paused a few minutes to see if it changed anything (it didn't) and to enable debug logs. These can be found in this file: [concourse-debug.log.gz](https://github.com/concourse/concourse/files/3002678/concourse-debug.log.gz). It was reverted to normal logging after a few crashes. Then all pipelines were paused until the system was pushed back into a stable state. This was magically achieved by removing workers by force. The removal started at 13:59 and all worker were gone by 14:08. Concourse last crashed at 13:59:12. So it looks like some of the early worker going away fixed the problem but I couldn't pin-point one from the logs. After all workers were gone, concourse web was restarted at 14:12 and fresh new workers started. You can find the full logs around the first and last crash in the following file: [concourse-crashes-beginning-and-end.log.gz](https://github.com/concourse/concourse/files/3002656/concourse-crashes-beginning-and-end.log.gz)

There is a surprising 5 minutes windows starting at 13:05:21 in which no crash occurred. You can find the logs in this file: [concourse-recovery.log.gz](https://github.com/concourse/concourse/files/3002094/concourse-recovery.log.gz). During that time, 11 builds succeeded and 4 failed as can be seen in this graph:
![image](https://user-images.githubusercontent.com/6637092/54906216-1ba74300-4ee3-11e9-823d-dccae72fb772.png)

## Version Info

* Concourse version: 5.0.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS + on-premise mac minis.
* Browser (if applicable):
* Did this used to work? yes

## Cc

@marco-m: This is the bug report from last Friday incident.

**Comment by vito** [comment]
Confirmed, looks like a bug in the code - I'll prioritize this for 5.1.0.

https://github.com/concourse/concourse/blob/v5.0.0/atc/db/build.go#L819

It should just use `resourceName` instead of `resource.Name()`.

**Comment by vito** [comment]
This also brings up a general notion that we should make it more difficult for errors like this to bring down the whole Concourse process - similar to how Go's `net/http` recovers from panics in HTTP handlers. I'll open an issue for that.

**Comment by marco-m** [comment]
thanks!

**Comment by odormond** [comment]
Thanks a lot Vito!
