### ISSUE TITLE
events api returns empty line breaking the http stream protocol 

### ISSUE THREAD

**Issue by mgsolid** [concourse/concourse#4067]
## Bug Report

events api returns empty line breaking the http stream protocol 

## Steps to Reproduce

https:// .... /api/v1/builds/347528/events

## Expected Results

event api should return streamed event data normally 

## Actual Results

traceback is from **client side.** used python to demonstrate the issue:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 554, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 311, in _error_catcher
    yield
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 610, in read_chunked
    self._update_chunk_length()
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 559, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 441, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 638, in read_chunked
    self._original_response.close()
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 329, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

## Additional Context

Intermittent, it's not stably reproduced every time.
The key problem is in stream, there is a byte which is b'', (empty) which expected as a hex value to indicate the chunk length:
 self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''
So, it breaks the http stream protocol here. 

## Version Info

* Concourse version: 5.2.0
* Deployment type (BOSH/Docker/binary): K8S
* Infrastructure/IaaS: IaaS
* Browser (if applicable): n/a
* Did this used to work?  No.

**Comment by pivotal-jamie-klassen** [comment]
Don't want to scope creep too much, but we might get a chance to look at this when approaching #3879. Just in case the API team doesn't.

**Comment by mgsolid** [comment]
thanks for your heads up. i can take a look at api side codes as well.
and i believe it's not from business logic layer. it's should be from lower layer. 
it obviously will cause issues at UI side (hang, retry...)

**Comment by pivotal-jamie-klassen** [comment]
@mgsolid if you're taking a look and you think it's a transport-level issue, I'm fairly sure we're counting on https://github.com/vito/go-sse

**Comment by mgsolid** [comment]
thanks. @vito could you guide me on that library, which will lead client from reading out empty line from server?

**Comment by vito** [comment]
I'm having a hard time figuring this issue out. Where exactly is the broken protocol usage? What do you mean by HTTP streaming? Chunked responses? Server-sent events? Can you give an example of a broken response payload and point out where the error is?

**Comment by mgsolid** [comment]
build event api.

im guessing: 
1. rows/table of even data are locked 
2. event api reads those rows
3. then db timed out 

i will take a look when im available

**Comment by mgsolid** [comment]
I haven't ran any real debug at server side. 
from code: 
https://github.com/concourse/concourse/blob/master/atc/api/buildserver/eventhandler.go#L36 
it sets  "Content-Type: text/event-stream" w/o any condition, and 
https://github.com/concourse/concourse/blob/master/atc/api/buildserver/eventhandler.go#L61
returns a server error, which is not an event. 

not sure, if it will lead such an issue

**Comment by simonjohansson** [comment]
We are seeing an issue with `events` as well, the payload is transferred like expected but it always errors.

```
$ fly -t TARGET curl /api/v1/builds/631068/events --verbose
2019/07/03 14:22:40 GET /api/v1/info HTTP/1.1
Host: concourse.superSecret.io
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2019/07/03 14:22:40 HTTP/1.1 200 OK
Content-Length: 116
Connection: keep-alive
Content-Type: application/json
Date: Wed, 03 Jul 2019 12:22:40 GMT
Server: nginx/1.15.10
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Concourse-Version: 5.3.0
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block

{"version":"5.3.0","worker_version":"2.1","external_url":"https://concourse.superSecret.io","cluster_name":"Halfpipe"}

id: 0
event: event
data: {"data":{"status":"started","time":1562137295},"event":"status","version":"1.0"}
....
....

id: 243
event: event
data: {"data":{"status":"succeeded","time":1562137405},"event":"status","version":"1.0"}

id: 244
event: end
data

# One minute passes

curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
error: exit status 92
```

<img width="975" alt="Screenshot 2019-07-03 at 14 34 30" src="https://user-images.githubusercontent.com/736248/60591895-b98e9180-9d9f-11e9-91ab-05f487f07e87.png">

**Comment by vito** [comment]
@simonjohansson Could that just be a load balancer idle timeout? The connection has to stay open otherwise the client-side considers it an error and just keeps re-attaching.

**Comment by simonjohansson** [comment]
> @simonjohansson Could that just be a load balancer idle timeout? The connection has to stay open otherwise the client-side considers it an error and just keeps re-attaching.

Ah good thinking, could very well be. I'll try to talk directly to 127.0.0.1 on test.

**Comment by ygbourhis** [comment]
Hi,

This is not closed for me, I can reproduce the issue
curl gives me the following error:
```
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```
And python requests gives me this error:
```
ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```
It is strictly impossible to retrieve any events on concourse.

Is it possible to reopen this issue?

**Comment by ygbourhis** [comment]
Currently, I manage to get the data in python this way:
After a
```bash
pip install sseclient-py
```
(see https://github.com/mpetazzoni/sseclient )
I do:
```python
import json
from pprint import pprint
import requests
from sseclient import SSEClient

url = 'https://my_concourse_url/api/v1/builds/%i/events' % some_build_id_number_here
resp = requests.get(url, headers={'Authorization': 'Bearer my_token_here'}, stream=True)

client = SSEClient(resp)

for event in client.events():
    if event.event == 'end':
        client.close()
        break
    pprint(json.loads(event.data))
```
More info in this merge request for the python client:
https://github.com/arwineap/concoursepy/pull/2/files

However, the server should cleanly close the connection when the end is reached, otherwise you leave stalled open sockets till timeouts which is really not clean and makes curl or tons of other clients fail.
I really do not know how to handle this without python...

**Comment by vito** [comment]
I'm not seeing any errors testing with a local `docker-compose up` instance. If I `curl` the API it dutifully [prints all the output](https://gist.github.com/vito/7f6f7a075deb3a19bae03bd957269e0e) and then sits there with the connection still active, but nothing being returned by the API.

The API endpoint has to remain active indefinitely even after the last event is received; if the connection is closed the browser will treat that as an error and re-connect. If you are seeing the connection being closed it may be due to the routing tier timing out the connection or mucking with the payload in some way. The SSE protocol is a fairly simple chunked text protocol with fairly primitive browser support so I'm having a hard time seeing where we're doing something wrong. 🤔

**Comment by taylorsilva** [comment]
# Issue Bankruptcy

This issue is being closed as part of 2025's **Issue Bankruptcy** declaration. [See here for details](https://blog.concourse-ci.org/posts/2025-01-06-concourse-2024-review/)

If you think this issue still has merit then feel free to open a new issue and reference this one.
