### ISSUE TITLE
Resource interaction fails with "failed to create new OS thread"

### ISSUE THREAD

**Issue by ljfranklin** [concourse/concourse#411]
We're seeing the following error intermittently on one of our vSphere workers. So far this has popped up when doing puts and gets from the s3 resource, but other users in slack reported seeing this on other Go resources. I don't think we saw this error before the upgrade to Concourse 1.0, but that could be a coincidence.

```
runtime: failed to create new OS thread (have 5 already; errno=11)
fatal error: newosproc
runtime: failed to create new OS thread (have 6 already; errno=11)
fatal error: newosproc

runtime stack:
runtime.throw(0x860800, 0x9)
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/panic.go:530 +0x90
runtime.newosproc(0xc820029000, 0xc8200d9fc0)
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/os1_linux.go:149 +0x18c
runtime.newm(0x0, 0xc820016000)
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/proc.go:1513 +0x135
runtime.startm(0xc820016000, 0x435400)
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/proc.go:1583 +0x122
runtime.handoffp(0xc820016000)
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/proc.go:1610 +0x313
runtime.entersyscallblock_handoff()
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/proc.go:2403 +0x53
runtime.systemstack(0xc820017500)
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/proc.go:1048

goroutine 5 [syscall]:
runtime.notetsleepg(0xa84e80, 0xffffffffffffffff, 0x1)
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/lock_futex.go:205 +0x4e fp=0xc820023f40 sp=0xc820023f18
os/signal.signal_recv(0x0)
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/sigqueue.go:116 +0x132 fp=0xc820023f78 sp=0xc820023f40
os/signal.loop()
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/os/signal/signal_unix.go:22 +0x18 fp=0xc820023fc0 sp=0xc820023f78
runtime.goexit()
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820023fc8 sp=0xc820023fc0
created by os/signal.init.1
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/os/signal/signal_unix.go:28 +0x37

goroutine 1 [running, locked to thread]:
goroutine running on other thread; stack unavailable

runtime stack:
runtime.throw(0x860800, 0x9)
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/panic.go:530 +0x90
runtime.newosproc(0xc8200dc000, 0xc8200d5fc0)
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/os1_linux.go:149 +0x18c
runtime.newm(0x90c2e8, 0xc82001a000)
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/proc.go:1513 +0x135
runtime.startm(0xc82001a000, 0x100000001)
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/proc.go:1583 +0x122
runtime.wakep()
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/proc.go:1664 +0x59
runtime.resetspinning()
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/proc.go:1991 +0xcf
runtime.schedule()
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/proc.go:2079 +0x27b
runtime.park_m(0xc820000a80)
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/proc.go:2137 +0x18b
runtime.mcall(0x0)
/var/vcap/data/packages/golang_1.6/0e84947d2c2122ef936e107ba76a3730760ea5e4-d0f990ec8337a7a594a8bcef646d7ce3d870aeea/src/runtime/asm_amd64.s:233 +0x5b
```

**Comment by mariash** [comment]
@ljfranklin what kernel version is on your vsphere worker? and what concourse worker version is there?

also

```
cat /proc/sys/kernel/threads-max
```

and

```
ulimit -u
```

**Comment by ljfranklin** [comment]
Hey @mariash,

Concourse deployment and external workers are on 1.0.0. Garden version is 0.335.0. Bosh stemcell is Ubuntu 3215.

```
# uname -r
3.19.0-56-generic

# lsb_release -d
Description:	Ubuntu 14.04.4 LTS

# cat /proc/sys/kernel/threads-max
31453

# ulimit -u
15726
```

Thanks for looking into this, let me know if you need any more info.

**Comment by ljfranklin** [comment]
Also those values are when the worker was basically idle, only 8 check containers where running.

**Comment by cjcjameson** [comment]
Adding myself and teammates @edespino @jmcatamney because we're seeing the same thing.

Concourse v1.2.0
AWS workers

**Comment by zaksoup** [comment]
To chime in with our detailed info on the worker VM:

```

**Comment by voelzmo** [comment]
Seeing this on our remote OpenStack workers as well:

```
# uname -r
3.19.0-51-generic

# lsb_release -d
Description:	Ubuntu 14.04.4 LTS

# cat /var/vcap/bosh/etc/stemcell_version
3202

# cat /proc/sys/kernel/threads-max
63709
```

**Comment by mariash** [comment]
Hey everyone, we are running this build in a loop, on a worker that CPI team shared with us and can't reproduce this. We suspect that it might be happening due to some external issues, like networking or s3. Could you please write the times when the builds were failing for you?

**Comment by vito** [comment]
We've switched to garden-runc, which should either fix this or change its characteristics; the stack was coming from garden-linux. Let us know if you see it again post-1.3!
