### ISSUE TITLE
concourse-worker: failed with "worker.baggageclaim.fs.run-command.failed"

### ISSUE THREAD

**Issue by DenisIzmaylov** [concourse/concourse#467]
Dear, thank you for this project.
I've configured Concourse in Docker, added "Hello-world" example and tried to create job. But got errors in UI that no workers found. When I tried to run `docker ps -a` I've found worker's container has been exited with the following logs:

```
failed to set up volumes filesystem: exit status 1
# I've formatted this output:
{
  "timestamp": "1465449257.592437983",
  "source": "worker",
  "message": "worker.baggageclaim.fs.run-command.failed",
  "log_level": 2,
  "data": {
    "args": [
      "bash",
      "-e",
      "-x",
      "-c",
      "\n\t\tif [ ! -e $IMAGE_PATH ] || [ \"$(stat --printf=\"%s\" $IMAGE_PATH)\" != \"$SIZE_IN_BYTES\" ]; then\n\t\t\ttouch $IMAGE_PATH\n\t\t\ttruncate -s ${SIZE_IN_BYTES} $IMAGE_PATH\n\t\tfi\n\n\t\tlo=\"$(losetup -j $IMAGE_PATH | cut -d':' -f1)\"\n\t\tif [ -z \"$lo\" ]; then\n\t\t\tlo=\"$(losetup -f --show $IMAGE_PATH)\"\n\t\tfi\n\n\t\tif ! file $IMAGE_PATH | grep BTRFS; then\n\t\t\tmkfs.btrfs --nodiscard $IMAGE_PATH\n\t\tfi\n\n\t\tmkdir -p $MOUNT_PATH\n\n\t\tif ! mountpoint -q $MOUNT_PATH; then\n\t\t\tmount -t btrfs $lo $MOUNT_PATH\n\t\tfi\n\t"
    ],
    "command": "/bin/bash",
    "env": [
      "PATH=/opt/concourse/worker/linux/btrfs:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "MOUNT_PATH=/opt/concourse/worker/volumes",
      "IMAGE_PATH=/opt/concourse/worker/volumes.img",
      "SIZE_IN_BYTES=502138003456"
    ],
    "error": "exit status 1",
    "session": "2.1.1",
    "stderr": "+ '[' '!' -e /opt/concourse/worker/volumes.img ']'\n+ touch /opt/concourse/worker/volumes.img\n+ truncate -s 502138003456 /opt/concourse/worker/volumes.img\n++ losetup -j /opt/concourse/worker/volumes.img\n++ cut -d: -f1\n+ lo=\n+ '[' -z '' ']'\n++ losetup -f --show /opt/concourse/worker/volumes.img\nlosetup: cannot find an unused loop device\n+ lo=\n",
    "stdout": ""
  }
}
```

Looks like #402.

**Comment by georgehaidar** [comment]
Is your worker container running with privileged flag? i.e. `docker run --privileged ...`

**Comment by DenisIzmaylov** [comment]
Thank you. It was not configured with privileged flag. I did it and something changed but still doesn't work and failures with the following log:
```
2016-06-09T08:33:12.996089922Z Wait for TSA on 172.17.0.4:2222...
2016-06-09T08:33:12.996119459Z done. Launch concourse-worker...
2016-06-09T08:33:12.996255058Z wait-for-it.sh: waiting 15 seconds for 172.17.0.4:2222
2016-06-09T08:33:12.996274577Z wait-for-it.sh: 172.17.0.4:2222 is available after 0 seconds
2016-06-09T08:33:22.886298840Z {"timestamp":"1465461202.886138678","source":"baggageclaim","message":"baggageclaim.listening","log_level":1,"data":{"addr":"0.0.0.0:7788"}}
2016-06-09T08:33:22.893604128Z {"timestamp":"1465461202.893489599","source":"garden-linux","message":"garden-linux.failed-to-parse-pool-state","log_level":2,"data":{"error":"openning state file: open /opt/concourse/worker/linux/state/port_pool.json: no such file or directory"}}
2016-06-09T08:33:22.893847406Z time="2016-06-09T08:33:22Z" level=error msg="Failed to GetDriver graph btrfs /opt/concourse/worker/linux/graph" 
2016-06-09T08:33:22.893871809Z time="2016-06-09T08:33:22Z" level=error msg="Failed to GetDriver graph zfs /opt/concourse/worker/linux/graph" 
2016-06-09T08:33:22.893882029Z time="2016-06-09T08:33:22Z" level=error msg="Failed to GetDriver graph devicemapper /opt/concourse/worker/linux/graph" 
2016-06-09T08:33:22.893896814Z time="2016-06-09T08:33:22Z" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded." 
2016-06-09T08:33:22.893928604Z {"timestamp":"1465461202.893896818","source":"garden-linux","message":"garden-linux.unsupported-graph-driver","log_level":1,"data":{"name":"vfs"}}
2016-06-09T08:33:22.894653135Z {"timestamp":"1465461202.894575834","source":"garden-linux","message":"garden-linux.retain.starting","log_level":1,"data":{"session":"10"}}
2016-06-09T08:33:22.894665813Z {"timestamp":"1465461202.894631863","source":"garden-linux","message":"garden-linux.retain.retained","log_level":1,"data":{"session":"10"}}
2016-06-09T08:33:22.899220217Z {"timestamp":"1465461202.899040222","source":"tsa","message":"tsa.connection.forward-worker.register.start","log_level":1,"data":{"session":"5.1.4","worker-address":"127.0.0.1:37860","worker-platform":"linux","worker-tags":""}}
2016-06-09T08:33:22.899609672Z 2016/06/09 08:33:22 failed to forward remote connection: dial tcp 0.0.0.0:7777: getsockopt: connection refused
2016-06-09T08:33:22.899890022Z {"timestamp":"1465461202.899751902","source":"tsa","message":"tsa.connection.forward-worker.register.failed-to-fetch-containers","log_level":2,"data":{"error":"Get http://api/containers: EOF","session":"5.1.4"}}
2016-06-09T08:33:22.899949102Z {"timestamp":"1465461202.899818182","source":"tsa","message":"tsa.connection.forward-worker.register.done","log_level":1,"data":{"session":"5.1.4","worker-address":"127.0.0.1:37860","worker-platform":"linux","worker-tags":""}}
2016-06-09T08:33:22.951619561Z {"timestamp":"1465461202.951481819","source":"garden-linux","message":"garden-linux.failed-to-set-up-backend","log_level":3,"data":{"error":"exit status 127","trace":"goroutine 1 [running, locked to thread]:\ngithub.com/pivotal-golang/lager.(*logger).Fatal(0xc82005ec60, 0xc1d180, 0x18, 0x7fe71f0f3378, 0xc82021e760, 0x0, 0x0, 0x0)\n\t/tmp/build/9674af12/garden-linux-release/src/github.com/pivotal-golang/lager/logger.go:131 +0xc5\nmain.main()\n\t/tmp/build/9674af12/garden-linux-release/src/github.com/cloudfoundry-incubator/garden-linux/main.go:507 +0x3b53\n"}}
2016-06-09T08:33:22.953708965Z panic: exit status 127
2016-06-09T08:33:22.953730084Z 
2016-06-09T08:33:22.953736960Z goroutine 1 [running, locked to thread]:
2016-06-09T08:33:22.953742471Z panic(0xb57520, 0xc82021e760)
2016-06-09T08:33:22.953747878Z 	/usr/local/go/src/runtime/panic.go:481 +0x3e6
2016-06-09T08:33:22.953754530Z github.com/pivotal-golang/lager.(*logger).Fatal(0xc82005ec60, 0xc1d180, 0x18, 0x7fe71f0f3378, 0xc82021e760, 0x0, 0x0, 0x0)
2016-06-09T08:33:22.953763480Z 	/tmp/build/9674af12/garden-linux-release/src/github.com/pivotal-golang/lager/logger.go:152 +0x698
2016-06-09T08:33:22.953770499Z main.main()
2016-06-09T08:33:22.953775257Z 	/tmp/build/9674af12/garden-linux-release/src/github.com/cloudfoundry-incubator/garden-linux/main.go:507 +0x3b53
2016-06-09T08:33:22.954782758Z Exit trace for group:
2016-06-09T08:33:22.954798890Z garden exited with error: exit status 2
2016-06-09T08:33:22.954806453Z baggageclaim exited with nil
2016-06-09T08:33:22.954810785Z beacon exited with nil
2016-06-09T08:33:22.954814852Z 
```

**Comment by DenisIzmaylov** [comment]
How I run it:
```
sudo docker run -e TSA_HOST=$(sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' concourse-web) -e TSA_PORT=2222 -d --privileged --name concourse-worker concourse-worker
```

**Comment by DenisIzmaylov** [comment]
Up!
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
```

**Comment by vito** [comment]
You may want to try the 1.3 release candidates:

https://github.com/concourse/bin/releases/tag/v1.3.0-rc.91

**Comment by DenisIzmaylov** [comment]
@vito could you please tell when 1.3 will be stable according to your estimation?

**Comment by DenisIzmaylov** [comment]
Up!

**Comment by DenisIzmaylov** [comment]
I've updated to 1.3 but there is still error messages:
```
Wait for TSA on 172.17.0.4:2222...
wait-for-it.sh: waiting 15 seconds for 172.17.0.4:2222
wait-for-it.sh: 172.17.0.4:2222 is available after 5 seconds
done. Launch concourse-worker...
{"timestamp":"1466952439.907162905","source":"worker","message":"worker.garden.unpack-assets.unpacking","log_level":1,"data":{"session":"1.1"}}
{"timestamp":"1466952444.096965313","source":"worker","message":"worker.garden.unpack-assets.done","log_level":1,"data":{"session":"1.1"}}
{"timestamp":"1466952444.097323179","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"archive","session":"1.2.1"}}
{"timestamp":"1466952444.367864370","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"bosh-deployment","session":"1.2.2"}}
{"timestamp":"1466952444.769415140","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"bosh-io-release","session":"1.2.3"}}
{"timestamp":"1466952444.969101906","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"bosh-io-stemcell","session":"1.2.4"}}
{"timestamp":"1466952445.166532278","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"cf","session":"1.2.5"}}
{"timestamp":"1466952445.676125526","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"docker-image","session":"1.2.6"}}
{"timestamp":"1466952446.414131880","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"git","session":"1.2.7"}}
{"timestamp":"1466952446.749912739","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"github-release","session":"1.2.8"}}
{"timestamp":"1466952447.113833427","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"hg","session":"1.2.9"}}
{"timestamp":"1466952447.495459557","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"pool","session":"1.2.10"}}
{"timestamp":"1466952447.771534920","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"s3","session":"1.2.11"}}
{"timestamp":"1466952448.166301727","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"semver","session":"1.2.12"}}
{"timestamp":"1466952448.598269939","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"time","session":"1.2.13"}}
{"timestamp":"1466952448.838871479","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"tracker","session":"1.2.14"}}
{"timestamp":"1466952449.230470419","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"vagrant-cloud","session":"1.2.15"}}
{"timestamp":"1466952449.437945604","source":"worker","message":"worker.baggageclaim.fs.run-command.failed","log_level":2,"data":{"args":["bash","-e","-x","-c","\n\t\tif [ ! -e $IMAGE_PATH ] || [ \"$(stat --printf=\"%s\" $IMAGE_PATH)\" != \"$SIZE_IN_BYTES\" ]; then\n\t\t\ttouch $IMAGE_PATH\n\t\t\ttruncate -s ${SIZE_IN_BYTES} $IMAGE_PATH\n\t\tfi\n\n\t\tlo=\"$(losetup -j $IMAGE_PATH | cut -d':' -f1)\"\n\t\tif [ -z \"$lo\" ]; then\n\t\t\tlo=\"$(losetup -f --show $IMAGE_PATH)\"\n\t\tfi\n\n\t\tif ! file $IMAGE_PATH | grep BTRFS; then\n\t\t\tmkfs.btrfs --nodiscard $IMAGE_PATH\n\t\tfi\n\n\t\tmkdir -p $MOUNT_PATH\n\n\t\tif ! mountpoint -q $MOUNT_PATH; then\n\t\t\tmount -t btrfs $lo $MOUNT_PATH\n\t\tfi\n\t"],"command":"/bin/bash","env":["PATH=/opt/concourse/worker/1.3.1/linux/btrfs:/opt/concourse/worker/1.3.1/linux/iptables/sbin:/opt/concourse/worker/1.3.1/linux/iptables/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","MOUNT_PATH=/opt/concourse/worker/volumes","IMAGE_PATH=/opt/concourse/worker/volumes.img","SIZE_IN_BYTES=502138003456"],"error":"exit status 1","session":"2.1.1","stderr":"+ '[' '!' -e /opt/concourse/worker/volumes.img ']'\n+ touch /opt/concourse/worker/volumes.img\n+ truncate -s 502138003456 /opt/concourse/worker/volumes.img\n++ losetup -j /opt/concourse/worker/volumes.img\n++ cut -d: -f1\n+ lo=\n+ '[' -z '' ']'\n++ losetup -f --show /opt/concourse/worker/volumes.img\nlosetup: cannot find an unused loop device\n+ lo=\n","stdout":""}}
{"timestamp":"1466952449.438011408","source":"worker","message":"worker.baggageclaim.falling-back-on-naive-driver","log_level":2,"data":{"error":"exit status 1","session":"2"}}
{"timestamp":"1466952449.438519955","source":"guardian","message":"guardian.failed-to-parse-port-pool-properties","log_level":2,"data":{"error":"openning state file: open : no such file or directory"}}
# ...a lot of other errors
```

**Comment by DenisIzmaylov** [comment]
When I run worker outside of Docker container I got that:
```
{"timestamp":"1466956229.609600544","source":"guardian","message":"guardian.iptables-runner.command.failed","log_level":2,"data":{"argv":["iptables","-w","-L","w--input"],"error":"exit status 1","exit-status":1,"session":"1.1","stderr":"iptables: No chain/target/match by that name.\n","stdout":"","took":"1.609426ms"}}
{"timestamp":"1466956229.609590530","source":"tsa","message":"tsa.connection.forward-worker.register.start","log_level":1,"data":{"remote":"172.17.0.1:48324","session":"4.1.4","worker-address":"127.0.0.1:33881","worker-platform":"linux","worker-tags":""}}
2016/06/26 17:50:29 failed to forward remote connection: dial tcp 0.0.0.0:7777: getsockopt: connection refused
{"timestamp":"1466956229.611327887","source":"tsa","message":"tsa.connection.forward-worker.register.failed-to-fetch-containers","log_level":2,"data":{"error":"Get http://api/containers: EOF","remote":"172.17.0.1:48324","session":"4.1.4"}}
```

**Comment by vito** [comment]
Looks like you need more loopback devices created. The rest of the logs don't look fatal - just noisy.

**Comment by DenisIzmaylov** [comment]
Thank you for response. I've solved a lot of issues which has been caused by `ufw` rules.
