### ISSUE TITLE
Unable to test tasks with `fly execute`

### ISSUE THREAD

**Issue by ipsi** [concourse/concourse#53]
I've been trying to use `fly execute` to test out some tasks that I'm working on, connecting to a simple Concourse instance deployed on AWS via BOSH, as it suggests in the docs. However, that functionality seems to be completely broken (And I'm not sure if it's Fly or ATC or BOSH or what have you that's the problem, hence raising this against the Concourse Release).

When attempting to use the following command:
```
# fly -k -t https://<user>:<pass>@<blah>.elb.amazonaws.com execute -i <input>=`pwd`/ -c ci/deploy-to-aws.yml
```
I get the following output:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:01 --:--:--     02015/06/01 12:35:42 bad response when uploading bits: &{504 GATEWAY_TIMEOUT 504 HTTP/1.1 1 1 map[Content-Length:[0] Connection:[keep-alive]] 0x2087c4040 0 [] false map[] 0x2087a0410 0x20874c580}
HTTP/1.1 504 GATEWAY_TIMEOUT
Content-Length: 0
Connection: keep-alive
```
Which is not ideal. I've looked at AWS, and I have the `Idle Timeout` set to 3600 seconds in the Elastic Load Balance configuration, and it still consistently times out after a minute.

If I fiddle with the AWS configuration slightly and talk to ATC directly, I get the following:
```
# fly -k -t http://<user>:<pass>@<elastic_ip>:8080 execute -i <input>=`pwd`/ -c ci/deploy-to-aws.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:06 --:--:--     0curl: (7) Failed to connect to <eip> port 8080: Connection timed out
gunzip: invalid magic
tar: short read
exit status 1
resource script '/opt/resource/in [/tmp/build/get]' failed: exit status 1
errored
```
Note how there is no movement in any of the numbers, either, so I'm not even sure if it's uploading.

Having a look with `cURL`, I get the following:
```
curl -k -v -X PUT http://<eip>:8080/api/v1/pipes/f2f65bc5-31cf-45a9-6c3b-8eb1fb4baf3f -u <user:pass> --data-binary @tmp.tgz > out
* About to connect() to <eip> port 8080 (#0)
*   Trying <eip>...
* Adding handle: conn: 0x7fc81c00aa00
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fc81c00aa00) send_pipe: 1, recv_pipe: 0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to <eip> (<eip>) port 8080 (#0)
* Server auth using Basic with user '<user>'
> PUT /api/v1/pipes/f2f65bc5-31cf-45a9-6c3b-8eb1fb4baf3f HTTP/1.1
> Authorization: Basic <auth>
> User-Agent: curl/7.30.0
> Host: <eip>:8080
> Accept: */*
> Content-Length: 56823313
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
  0 54.1M    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0< HTTP/1.1 100 Continue
} [data not shown]
 22 54.1M    0     0   22 11.9M      0   6746  2:20:23  0:30:55  1:49:28     0
```
This time, we can see that it actually uploaded about 12M, and then stopped. Nothing else happened (running `cURL` against the ELB rather than the Elastic IP also produced a 504).

A smaller file set (<12MB) uploaded OK with `cURL`, but not with `fly` - `fly execute` still responded with the same `gunzip: invalid magic`, and did not appear to actually send any data (though tcpdump + WireShark suggests it should have).

Any idea what's going on? Any configuration I'm likely to be missing?

EDIT: This seems to occur when deploying to BOSH Lite as well, using the latest concourse + garden release combination (from https://github.com/concourse/concourse/releases)

**Comment by vito** [comment]
Shot in the dark, but make sure your elb is set up with TCP or SSL listeners and not http or https. Even if that doesn't fix it you'll want to keep it that way so hijack can work.

**Comment by ipsi** [comment]
Huh - I don't recall seeing that mentioned anywhere. Anyway, I've updated my ELB so it's now using an SSL socket on 443 -> a TCP socket on 8080, which means I now get the following error:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:02 --:--:--     02015/06/01 16:37:37 request failed: Put https://<...>.elb.amazonaws.com/api/v1/pipes/ced4b0da-1257-472e-47f7-b20f53e7ac83: EOF
```
I can still access Concourse either via the web or by using `fly l`, however.

**Comment by vito** [comment]
Yeah, the docs skimp on that detail, sorry.

Not sure what's going on here. Maybe try with a smaller payload? Switching to SSL shouldn't inherently cause problems but may result in different failures from the same issue.

**Comment by ipsi** [comment]
Even with a (much) smaller payload of about 300KB, still get the same issue.

**Comment by ipsi** [comment]
Issue was ultimately caused by the following:

I had a subnet `private-sn` and another subnet `public-sn`.

My BOSH and Concourse VMs were all in `private-sn`, and I had a NAT VM in `public-sn`. When I created the load balancer, I'd specified the `Availability Zones` as `private-sn`. As per [this thread](https://forums.aws.amazon.com/message.jspa?messageID=478035), that's a bad idea. The ELB must be placed in the same subnet as the NAT box.

Very strange, but not actually a Concourse problem.

**Comment by tscolari** [comment]
We are having a similar issue when using the cloudformation scripts.
It creates 3 subnets:
* LoadBalancer
* Bosh (NAT)
* Internal

It then places the LoadBalancer on the `LoadBalancer` subnet.
When trying to run `fly execute` we get:

```
executing build 82
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0    485      0 --:--:-- --:--:-- --:--:--  4666
gunzip: invalid magic
tar: short read
exit status 1
failed
```

When we tried to move the ELB to the same subnet of NAT (Bosh) the concourse/Web was out of reach. We added the ELB to both, `BOSH` and `internal` subnets, and we could access concourse again through it. But still having issues with `fly execute`:

```
executing build 84
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0upload request failed: Put http://admin:look74Beer@concourse-execute-test-3-527300689.eu-west-1.elb.amazonaws.com/api/v1/pipes/bf1f428c-0e93-4abf-46ba-57d016dcd053: EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x884dd]

goroutine 14 [running]:
github.com/concourse/fly/commands.upload(0x7fff5fbff665, 0x16, 0x7fff5fbff67c, 0x30, 0x8208be360, 0x24, 0x0, 0x0, 0x0, 0x0, ...)
        /var/vcap/packages/fly/src/github.com/concourse/fly/commands/execute.go:348 +0xb0d
github.com/concourse/fly/commands.(*ExecuteCommand).Execute.func1(0x8208fc120, 0x1, 0x1, 0x8820951000, 0x82088e1b0)
        /var/vcap/packages/fly/src/github.com/concourse/fly/commands/execute.go:82 +0xf1
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
        /var/vcap/packages/fly/src/github.com/concourse/fly/commands/execute.go:85 +0xa2e

goroutine 1 [IO wait]:
net.runtime_pollWait(0x8820957048, 0x72, 0x8207ae1f0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x820885cd0, 0x72, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0x820885cd0, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0x820885c70, 0x8208f0000, 0x1000, 0x1000, 0x0, 0x8820951050, 0x8207ae1f0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0x8207d2288, 0x8208f0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x88209572d8, 0x8207d2288, 0x8208a0058, 0x8208f0000, 0x1000, 0x1000, 0x14, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0x8208ee0a0, 0x8208f0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0x8207b9140)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0x8207b9140, 0x8208a440a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/bufio/bufio.go:328 +0x21a
net/http/internal.readLine(0x8207b9140, 0x0, 0x0, 0x0, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/http/internal/chunked.go:110 +0x4b
net/http/internal.(*chunkedReader).beginChunk(0x8208d0600)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/http/internal/chunked.go:47 +0x39
net/http/internal.(*chunkedReader).Read(0x8208d0600, 0x820973000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/http/internal/chunked.go:77 +0xb7
net/http.(*body).readLocked(0x8208d4540, 0x820973000, 0x1000, 0x1000, 0x8209dce70, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/http/transfer.go:632 +0x98
net/http.(*body).Read(0x8208d4540, 0x820973000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/http/transfer.go:624 +0x110
bufio.(*Reader).fill(0x8209700c0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadByte(0x8209700c0, 0x100, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/bufio/bufio.go:229 +0x7a
compress/flate.(*decompressor).moreBits(0x820974000, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/compress/flate/inflate.go:699 +0x4d
compress/flate.(*decompressor).nextBlock(0x820974000)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/compress/flate/inflate.go:308 +0x20e
compress/flate.(*decompressor).Read(0x820974000, 0x820972000, 0x1000, 0x1000, 0x5db46, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/compress/flate/inflate.go:349 +0x1ae
compress/gzip.(*Reader).Read(0x82096e2c0, 0x820972000, 0x1000, 0x1000, 0xffffffff, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/compress/gzip/gunzip.go:250 +0xef
net/http.(*gzipReader).Read(0x8208d2240, 0x820972000, 0x1000, 0x1000, 0x5e671, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/http/transport.go:1346 +0x14a
net/http.(*bodyEOFSignal).Read(0x8208d4580, 0x820972000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/http/transport.go:1296 +0x26a
bufio.(*Reader).fill(0x820970060)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0x820970060, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0x820970060, 0x0, 0x0, 0x0, 0x393800, 0x0, 0x0)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/bufio/bufio.go:357 +0x53
github.com/vito/go-sse/sse.(*ReadCloser).Next(0x8208d0630, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /var/vcap/packages/fly/src/github.com/vito/go-sse/sse/read_closer.go:51 +0x130
github.com/vito/go-sse/sse.(*EventSource).Next(0x8207b6d20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /var/vcap/packages/fly/src/github.com/vito/go-sse/sse/event_source.go:86 +0x1a9
github.com/concourse/fly/atcclient/eventstream.(*SSEEventStream).NextEvent(0x820950008, 0x0, 0x0, 0x0, 0x0)
        /var/vcap/packages/fly/src/github.com/concourse/fly/atcclient/eventstream/stream.go:29 +0x57
github.com/concourse/fly/atcclient/eventstream.Render(0x88209551e8, 0x8207d2010, 0x88209911e0, 0x820950008, 0x820950008)
        /var/vcap/packages/fly/src/github.com/concourse/fly/atcclient/eventstream/render.go:18 +0x99
github.com/concourse/fly/commands.(*ExecuteCommand).Execute(0x700cb8, 0x820885340, 0x0, 0x7, 0x0, 0x0)
        /var/vcap/packages/fly/src/github.com/concourse/fly/commands/execute.go:94 +0xd6e
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0x8207b6820, 0x8207aa090, 0x7, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
        /var/vcap/packages/fly/src/github.com/jessevdk/go-flags/parser.go:278 +0x8ed
github.com/jessevdk/go-flags.(*Parser).Parse(0x8207b6820, 0x0, 0x0, 0x0, 0x0, 0x0)
        /var/vcap/packages/fly/src/github.com/jessevdk/go-flags/parser.go:154 +0x9b
main.main()
        /var/vcap/packages/fly/src/github.com/concourse/fly/main.go:14 +0x62

goroutine 5 [syscall]:
os/signal.loop()
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/os/signal/signal_unix.go:28 +0x37

goroutine 12 [chan receive]:
github.com/concourse/fly/commands.abortOnSignal(0x8820955ea0, 0x82088e1a0, 0x8207b92c0, 0x54, 0x82088ec80, 0x2, 0x82088ec90, 0x7, 0x0, 0x0, ...)
        /var/vcap/packages/fly/src/github.com/concourse/fly/commands/execute.go:293 +0x45
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
        /var/vcap/packages/fly/src/github.com/concourse/fly/commands/execute.go:75 +0x846

goroutine 10 [select]:
net/http.(*persistConn).readLoop(0x8208a0000)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/http/transport.go:685 +0xc78

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0x8208a0000)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/net/http/transport.go:686 +0xc9d

goroutine 13 [select, locked to thread]:
runtime.gopark(0x591150, 0x8207ca728, 0x4cac18, 0x6, 0x18, 0x2)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0x8207ca728, 0x0, 0x18)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/runtime/select.go:392 +0xa64
runtime.selectgo(0x8207ca728)
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
        /var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4.1-6be815d214c4619026487c0f716b4b2216357f4a/src/runtime/asm_amd64.s:1696 +0x1
```

Note that, in this configuration, the stack error happens most of the time, but some times it fails with the `invalid magic` message too.

**Comment by tscolari** [comment]
We found a solution for our `fly execute` problem:

When you login to concourse targeting with httpauth credentials:

```
fly -t https://user:pass@concourse login
```

It creates a .flyrc with the "https://user:pass@concourse" as the alias:

```
targets:
  https://user:pass@concourse:
    api: https://user:pass@concourse
    token:
      type: Bearer
      value: my-token
```

But then, when you use the same url as target for the execute, it fails.
Probably because it's resolving it as an concourse url instead of looking up
at the .flyrc for the target. Renaming the target name in the .flyrc to `london`
and using it as the target of the execute, fixed the issue.

```
targets:
  london:
    api: https://user:pass@concourse
    token:
      type: Bearer
      value: my-token
```

**Comment by bramswenson** [comment]
I had this issue, it was my firewall blocking ports when accessed from my vpn clients. Not a bug.
