### ISSUE TITLE
SIGSEGV at startup (concourse web)

### ISSUE THREAD

**Issue by kirillt** [concourse/concourse#5592]
## Summary
I have just installed Concourse and Postgresql 10 on fresh CentOS 8 server.
Following documentation, I generated keys, created a Postgresql user (with my own name and password), created Postgresql database. Modified `peer` to `md5` in `pg_hba.conf` to make it possible to connect via unix sockets. When I run `concourse web`, I am getting segmentation fault.

## Steps to reproduce
```
[kirill@centos-2gb-fsn1-2 ~]$ cat concourse/env 
#!/bin/bash
export CONCOURSE_ADD_LOCAL_USER=root:********
export CONCOURSE_MAIN_TEAM_LOCAL_USER=root

export CONCOURSE_SESSION_SIGNING_KEY="$CONCOURSE/session_signing_key"
export CONCOURSE_TSA_HOST_KEY="$CONCOURSE/tsa_host_key"
export CONCOURSE_TSA_AUTHORIZED_KEYS="$CONCOURSE/authorized_worker_keys"

export CONCOURSE_POSTGRES_SOCKET=/var/run/postgresql
export CONCOURSE_POSTGRES_DATABASE=concourse_db
export CONCOURSE_POSTGRES_USER=concourse
export CONCOURSE_POSTGRES_PASSWORD=********
[kirill@centos-2gb-fsn1-2 ~]$ source concourse/env
[kirill@centos-2gb-fsn1-2 ~]$ concourse web
{"timestamp":"2020-05-12T22:43:02.435099484Z","level":"info","source":"atc","message":"atc.cmd.start","data":{"session":"1"}}
{"timestamp":"2020-05-12T22:43:03.115334066Z","level":"info","source":"atc","message":"atc.cmd.finish","data":{"duration":256799,"session":"1"}}
{"timestamp":"2020-05-12T22:43:03.115448850Z","level":"info","source":"tsa","message":"tsa.starting-tsa-without-authorized-keys","data":{}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1107dc5]

goroutine 1 [running]:
crypto/rsa.(*PrivateKey).Public(0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/rsa/rsa.go:100 +0x5
golang.org/x/crypto/ssh.NewSignerFromSigner(0x7f171c076820, 0xc0000106b8, 0xc0000106b8, 0x7f171c076820, 0xc0000106b8, 0xeb3e01)
	/tmp/build/8cf986d9/gopath/pkg/mod/golang.org/x/crypto@v0.0.0-20200220183623-bac4c82f6975/ssh/keys.go:951 +0x35
golang.org/x/crypto/ssh.NewSignerFromKey(0x2ba8420, 0xc0000106b8, 0xc00132f080, 0xeb309c, 0x7f16f2348198, 0x7f)
	/tmp/build/8cf986d9/gopath/pkg/mod/golang.org/x/crypto@v0.0.0-20200220183623-bac4c82f6975/ssh/keys.go:926 +0x167
github.com/concourse/concourse/tsa/tsacmd.(*TSACommand).configureSSHServer(0xc0010ec360, 0xc0010ff320, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x13, 0xc000056048, ...)
	/tmp/build/8cf986d9/concourse/tsa/tsacmd/command.go:238 +0x2d1
github.com/concourse/concourse/tsa/tsacmd.(*TSACommand).Runner(0xc0010ec360, 0xc000f1fb70, 0x0, 0x1, 0x38984e0, 0xc00135c930, 0x0, 0x0)
	/tmp/build/8cf986d9/concourse/tsa/tsacmd/command.go:114 +0x27a
main.(*WebCommand).Runner(0xc0010fa008, 0xc000f1fb70, 0x0, 0x1, 0x7, 0x6, 0xc000f1f9e0, 0xc000099a00)
	/tmp/build/8cf986d9/concourse/cmd/concourse/web.go:67 +0x107
main.(*WebCommand).Execute(0xc0010fa008, 0xc000f1fb70, 0x0, 0x1, 0x2a82ba0, 0x2d32fa0)
	/tmp/build/8cf986d9/concourse/cmd/concourse/web.go:44 +0x61
github.com/vito/twentythousandtonnesofcrudeoil.installEnv.func2(0x7f171c051ee0, 0xc0010fa008, 0xc000f1fb70, 0x0, 0x1, 0x1, 0x0)
	/tmp/build/8cf986d9/gopath/pkg/mod/github.com/vito/twentythousandtonnesofcrudeoil@v0.0.0-20180305154709-3b21ad808fcb/environment.go:40 +0x8a
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc00009af00, 0xc000126030, 0x1, 0x1, 0xc0010ec360, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/8cf986d9/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:314 +0x880
github.com/jessevdk/go-flags.(*Parser).Parse(...)
	/tmp/build/8cf986d9/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
main.main()
	/tmp/build/8cf986d9/concourse/cmd/concourse/main.go:30 +0x1f2
```

## Expected results
Concourse runs

## Actual results
Segmentation fault

## Additional context
This is a fresh CentOS 8 server with connection to Postgresql via unix sockets.

## Triaging info

* Concourse version:
6.1.0
* Browser (if applicable):
not applicable
* Did this used to work?
no

**Comment by Sulstice** [comment]
Hi @kirillt 

So here is what we did to fix this in our stack.

```

[goroutine 1 [running]:
crypto/rsa.(*PrivateKey).Public(0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/rsa/rsa.go:100 +0x5](url)

```

When you generated your TSA host key it creates two files and you need both private and public for the concourse web. So verify that this file is in your environment. 

```
“${CONCOURSE_TSA_HOST_KEY}.pub” 

```

**Comment by kirillt** [comment]
Hi @Sulstice, thanks for your time to look at this issue. So, it seems to be not a bug but just a lack of documentation then... I will read about TSA keys, they are just mentioned first time in docs later than a moment when user runs Concourse CI for first time.
