### ISSUE TITLE
running `concourse web` without all required parameters just crashes it

### ISSUE THREAD

**Issue by flokli** [concourse/concourse#5613]
## Summary

After experimenting with Concourse a bit, I tried to get `concourse web` to run manually.

## Steps to reproduce
 - Follow https://concourse-ci.org/concourse-generate-key.html to generate keys
 - Run concourse web (6.1.0) like this: `CONCOURSE_ADD_LOCAL_USER=myuser:mypass CONCOURSE_MAIN_TEAM_LOCAL_USER=myuser CONCOURSE_SESSION_SIGNING_KEY=./session_signing_key CONCOURSE_TSA_HOST_KEY=./tsa_host_key CONCOURSE_TSA_AUTHORIZED_KEYS=./worker_key.pub CONCOURSE_LOG_LEVEL=debug result/bin/concourse web`
 - I get a not very helpful panic.

## Expected results
I get an error message that tells me what I missed to configure - or if this is an actual connection problem to the database, a more meaningful error message than just a panic with pointers.

## Actual results
```
{"timestamp":"2020-05-15T19:59:02.474222528Z","level":"info","source":"atc","message":"atc.cmd.start","data":{"session":"1"}}
{"timestamp":"2020-05-15T19:59:02.474449974Z","level":"debug","source":"atc","message":"atc.metrics.metric-initialize","data":{"attributes":{},"buffer-size":1000,"host":"tp.flokli.de","session":"2"}}
{"timestamp":"2020-05-15T19:59:02.474638709Z","level":"info","source":"atc","message":"atc.cmd.finish","data":{"duration":98814,"session":"1"}}
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/concourse/concourse/atc/db/migration.(*migrator).Up(0xc0002d6280, 0x3240d60, 0xc00044c8c0)
	/build/source/atc/db/migration/migration.go:370 +0xa7
github.com/concourse/concourse/atc/db/migration.(*OpenHelper).Open(0xc0005beca8, 0x0, 0x0, 0x0)
	/build/source/atc/db/migration/migration.go:63 +0xb0
github.com/concourse/concourse/atc/db.Open(0x32c4420, 0xc0002054a0, 0x2e57dc3, 0x1d, 0xc0000584b0, 0x4f, 0x0, 0x0, 0x2e1e03f, 0x3, ...)
	/build/source/atc/db/open.go:76 +0x152
github.com/concourse/concourse/atc/atccmd.(*RunCommand).constructDBConn(0xc0005c6480, 0x2e57dc3, 0x1d, 0x32c4420, 0xc000205080, 0xa, 0x2e1e03f, 0x3, 0x3240d60, 0xc00044c8c0, ...)
	/build/source/atc/atccmd/command.go:1416 +0x1c7
github.com/concourse/concourse/atc/atccmd.(*RunCommand).Runner(0xc0005c6480, 0xc000219fb0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0)
	/build/source/atc/atccmd/command.go:475 +0x6ba
main.(*WebCommand).Runner(0xc0005c6008, 0xc000219fb0, 0x0, 0x1, 0x7, 0x6, 0xc000219e20, 0xc0001cd2c0)
	/build/source/cmd/concourse/web.go:62 +0xa1
main.(*WebCommand).Execute(0xc0005c6008, 0xc000219fb0, 0x0, 0x1, 0x2b3b460, 0x2deb860)
	/build/source/cmd/concourse/web.go:44 +0x61
github.com/vito/twentythousandtonnesofcrudeoil.installEnv.func2(0x7f379dd11b50, 0xc0005c6008, 0xc000219fb0, 0x0, 0x1, 0x1, 0x0)
	/build/source/vendor/github.com/vito/twentythousandtonnesofcrudeoil/environment.go:40 +0x8a
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0002046c0, 0xc00000e0b0, 0x1, 0x1, 0xc000523560, 0x0, 0x0, 0x0, 0x0)
	/build/source/vendor/github.com/jessevdk/go-flags/parser.go:314 +0x880
github.com/jessevdk/go-flags.(*Parser).Parse(...)
	/build/source/vendor/github.com/jessevdk/go-flags/parser.go:186
main.main()
	/build/source/cmd/concourse/main.go:30 +0x1f2
```

## Triaging info

* Concourse version: 6.1.0
* Browser (if applicable):
* Did this used to work?

**Comment by jamieklassen** [comment]
It sure seems like a problem, but I'm having trouble reproducing it on macOS with a `brew services`-managed postgres. Can you describe a little bit more about your operating system and your postgres setup?

When I tried to run on macOS the web UI would break, unable to find asset files. The stack trace you provided mentions migrations -- I wonder if something's gone wrong with `packr`.

**Comment by flokli** [comment]
It indeed looks like it doesn't have much to do with the postgresql connection parameters - even when setting all of them as described in the docs, it crashes. Postgresql itself is just coming from a `postgres:latest` docker container, so nothing special here:
```
docker run -p 5432:5432  -e POSTGRES_PASSWORD=password -e POSTGRES_DB=atc -e POSTGRES_USER=atc postgres
```

`packr`/ `go generate` not being run during build indeed looks like being the culprit here - I built concourse via Nix, and the tooling doesn't automatically invoke packr, as the go code still builds without it - I wonder if concourse can notice this in a more graceful way.

**Comment by jamieklassen** [comment]
Apparently the authors of `packr` have made a new thing, `pkger` that we're encourage to migrate to: https://blog.gobuffalo.io/introducing-pkger-static-file-embedding-in-go-1ce76dc79c65. Another item for the tech debt pile.

**Comment by flokli** [comment]
yay, another way to embed assets in go binaries :-D

Anyways, thanks for the quick reply - Running `packr` during the build got me past the panic.
I assume things will look different  with `pkger`, so I'll leave it to you on whether to keep this issue open or not :-)

**Comment by jamieklassen** [comment]
Before you go, can you tell me a bit more about

> I built concourse via Nix

? I have heard of Nix but never used it. Were you using some published packaging formula?

**Comment by flokli** [comment]
I was using the generic [`buildGoModule`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/go-modules/generic/default.nix) function, which can build most go packages. nixpkgs already contains `fly`, and I wanted to get whole `concourse` built.

It's a bit more work, as obviously the frontend code also needs to be built, but I can highlight you once I get to this on the PR adding it.

**Comment by flokli** [comment]
So, it turns out the `elm` parts also require [their own bundling mechanism](https://blog.hercules-ci.com/elm/2019/01/03/elm2nix-0.1/) to get things to build in the sandboxed/offline scenario…

@jamieklassen any chance for `concourse` to publish the (trans|com)piled, uglified and tree-shaked `web/public` folder contents in some release artifact as well?

That way, we could just treat the web interface as an external artifact, and pass it in while still building the rest.

**Comment by rudolphfroger-ds** [comment]
I think the FreeBSD Concourse port has the same issue.

**Comment by taylorsilva** [comment]
# Issue Bankruptcy

This issue is being closed as part of 2025's **Issue Bankruptcy** declaration. [See here for details](https://blog.concourse-ci.org/posts/2025-01-06-concourse-2024-review/)

If you think this issue still has merit then feel free to open a new issue and reference this one.
