### ISSUE TITLE
generate-key crashes on macos

### ISSUE THREAD

**Issue by tvon** [concourse/concourse#5647]
## Summary

Running `concourse generate-key -t ssh -f ./tsa_host_key` crashes.

## Steps to reproduce

```console
$ concourse generate-key -t ssh -f ./tsa_host_key
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
reflect.(*rtype).In(0x59145c0, 0x0, 0x193, 0x64aba60)
        /usr/local/go/src/reflect/type.go:960 +0xa8
github.com/jessevdk/go-flags.(*Option).call(0xc001015d40, 0xc000fa73b0, 0x193, 0x64aba60)
        /Users/DX261/work-dir/volumes/live/b484d963-563c-4d62-676b-ad163e8caeae/volume/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/option.go:384 +0x90
github.com/jessevdk/go-flags.(*Option).set(0xc001015d40, 0xc000fa73b0, 0xc0000562f2, 0x5)
        /Users/DX261/work-dir/volumes/live/b484d963-563c-4d62-676b-ad163e8caeae/volume/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/option.go:224 +0x252
github.com/jessevdk/go-flags.(*Option).clearDefault(0xc001015d40)
        /Users/DX261/work-dir/volumes/live/b484d963-563c-4d62-676b-ad163e8caeae/volume/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/option.go:280 +0xc1
github.com/jessevdk/go-flags.(*Parser).ParseArgs.func2(0xc000156080, 0xc0002faea0, 0xc001015d40)
        /Users/DX261/work-dir/volumes/live/b484d963-563c-4d62-676b-ad163e8caeae/volume/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:300 +0x3e
github.com/jessevdk/go-flags.(*Command).eachOption.func1.1(0xc0002faea0)
        /Users/DX261/work-dir/volumes/live/b484d963-563c-4d62-676b-ad163e8caeae/volume/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/command.go:281 +0x6a
github.com/jessevdk/go-flags.(*Group).eachGroup(0xc0002faea0, 0xc000fa74c8)
        /Users/DX261/work-dir/volumes/live/b484d963-563c-4d62-676b-ad163e8caeae/volume/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/group.go:169 +0x30
github.com/jessevdk/go-flags.(*Group).eachGroup(0xc0002fae10, 0xc000fa74c8)
        /Users/DX261/work-dir/volumes/live/b484d963-563c-4d62-676b-ad163e8caeae/volume/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/group.go:172 +0x67
github.com/jessevdk/go-flags.(*Command).eachOption.func1(0xc000156080)
        /Users/DX261/work-dir/volumes/live/b484d963-563c-4d62-676b-ad163e8caeae/volume/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/command.go:279 +0x63
github.com/jessevdk/go-flags.(*Command).eachCommand(0xc000156080, 0xc000fa7548, 0x1)
        /Users/DX261/work-dir/volumes/live/b484d963-563c-4d62-676b-ad163e8caeae/volume/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/command.go:288 +0x34
github.com/jessevdk/go-flags.(*Command).eachOption(0xc000156080, 0x6101730)
        /Users/DX261/work-dir/volumes/live/b484d963-563c-4d62-676b-ad163e8caeae/volume/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/command.go:278 +0x58
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0005768a0, 0xc00004e190, 0x5, 0x5, 0xc000485560, 0x0, 0x0, 0x0, 0x0)
        /Users/DX261/work-dir/volumes/live/b484d963-563c-4d62-676b-ad163e8caeae/volume/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:295 +0x992
github.com/jessevdk/go-flags.(*Parser).Parse(...)
        /Users/DX261/work-dir/volumes/live/b484d963-563c-4d62-676b-ad163e8caeae/volume/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
main.main()
        /Users/DX261/work-dir/volumes/live/b484d963-563c-4d62-676b-ad163e8caeae/volume/concourse/cmd/concourse/main.go:30 +0x20f
```

## Expected results

Not that

## Actual results

Aforementioned crash.

## Additional context

None.

## Triaging info

* Concourse version: 6.1.0
* Browser (if applicable): n/a
* Did this used to work? Totally.

**Comment by tvon** [comment]
I get the same result with 6.0.0

**Comment by tvon** [comment]
Well, I tried 5.8.1 and 5.8.0 and I get the same result, but I know this used to work because I stood up a Concourse cluster with 5.8.0 a few months ago.  I think it's a local problem, no clue what it could be though.

Leaving this open for now but pretty sure it is not a Concourse issue.

**Comment by tvon** [comment]
Turns out this was because I had `CONCOURSE_VERSION` set in the environment (for other things).  Unsetting that var allows the command to run.

Looking around some more I see this has been filed before: https://github.com/concourse/concourse/issues/1018
