### ISSUE TITLE
Docker Repository binary fails with missing /proc/self/uid_map

### ISSUE THREAD

**Issue by TimJones** [concourse/concourse#584]
I was going to update my Concourse cluster from the unofficial [meteogroup/concourse-ci](https://hub.docker.com/r/meteogroup/concourse-ci/) to the official [concourse/concourse](https://hub.docker.com/r/concourse/concourse/) but I always get the following error when launching the container
```
$ docker run -v secrets:/concourse-keys concourse/concourse:1.6.0 web
panic: open /proc/self/uid_map: no such file or directory

goroutine 1 [running]:
panic(0xf4cee0, 0xc820284ab0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/cloudfoundry-incubator/guardian/sysinfo.must(0x0, 0x7f38b797e9b8, 0xc820284ab0, 0x7f38b797e9b8)
	/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/sysinfo/max_valid_uid.go:69 +0x4b
github.com/cloudfoundry-incubator/guardian/sysinfo.MustGetMaxValidUID(0x0)
	/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/sysinfo/max_valid_uid.go:15 +0x58
github.com/cloudfoundry-incubator/guardian/guardiancmd.init.1()
	/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/guardiancmd/command.go:214 +0x3b
github.com/cloudfoundry-incubator/guardian/guardiancmd.init()
	/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/guardiancmd/seccomp.go:1597 +0x27e
main.init()
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/cmd/concourse/worker_unix.go:23 +0xd8
```

Even trying to launch the binary directly from within the container fails
```
$ docker run -v secrets:/concourse-keys --entrypoint=/bin/bash concourse/concourse:1.6.0
root@5450e80b036d:/# /usr/local/bin/concourse web --help
panic: open /proc/self/uid_map: no such file or directory

goroutine 1 [running]:
panic(0xf4cee0, 0xc820250810)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/cloudfoundry-incubator/guardian/sysinfo.must(0x0, 0x7fd7ea0a90e0, 0xc820250810, 0x7fd7ea0a90e0)
	/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/sysinfo/max_valid_uid.go:69 +0x4b
github.com/cloudfoundry-incubator/guardian/sysinfo.MustGetMaxValidUID(0x0)
	/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/sysinfo/max_valid_uid.go:15 +0x58
github.com/cloudfoundry-incubator/guardian/guardiancmd.init.1()
	/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/guardiancmd/command.go:214 +0x3b
github.com/cloudfoundry-incubator/guardian/guardiancmd.init()
	/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/guardiancmd/seccomp.go:1597 +0x27e
main.init()
	/tmp/build/9674af12/gopath/src/github.com/concourse/bin/cmd/concourse/worker_unix.go:23 +0xd8
root@5450e80b036d:/# exit
```

**Comment by vito** [comment]
Looks like the environment doesn't have user namespaces enabled. That's the only thing I can think of that would lead to that directory not existing; it's entirely set up by the host kernel.

**Comment by hwmrocker** [comment]
is there a workaround?

**Comment by kyrias** [comment]
If you're going to require user namespaces, this should really be documented clearly.  Currently the only way to find out is to google the error and find tickets that imply that they're required.

**Comment by vito** [comment]
done; https://github.com/concourse/concourse/commit/e3ab389cc5907f3a0d849a4d622b4cb17e36cf0a

**Comment by Nepoxx** [comment]
I'd suggest documenting it here as well: http://concourse.ci/docker-repository.html

FYI this means that Concourse will not work on Arch linux by default.

**Comment by cviebig** [comment]
I have exactly this problem. I found a mailing list thread that might be an interesting read here and gives reasons why ArchLinux does not ship a kernel with user namespaces enabled: https://lists.archlinux.org/pipermail/arch-general/2017-February/043066.html
