### ISSUE TITLE
Setting a modifier step without a base step causes (non-fatal) panic

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5869]
## Summary

Setting a pipeline where a job step has a modifier step field (e.g. `attempts`, `on_success`, etc.) but no base step (e.g. `get`, `task`, etc.) causes the ATC to panic (which gets `recover`ed, fortunately).

## Steps to reproduce

```
$ cat pipeline.yml
jobs:
- name: job
  plan:
  - attempts: 1
$ fly -t dev sp -p hope-this-doesnt-panic -c pipeline.yml
jobs:
  job job has been added:
+ name: job
+ plan:
+ - null

apply configuration? [yN]: y
could not reach the Concourse server called dev:

    Put "http://localhost:8080/api/v1/teams/main/pipelines/bad/config": EOF

is the targeted Concourse running? better go catch it lol
```

## Expected results

It fails to set pipeline with a better error message

## Actual results

(in the logs)
```
web_1     | 2020/07/10 13:16:11 http: panic serving 172.23.0.1:33606: runtime error: invalid memory address or nil pointer dereference
web_1     | goroutine 215562 [running]:
web_1     | net/http.(*conn).serve.func1(0xc0007348c0)
web_1     | 	/usr/local/go/src/net/http/server.go:1772 +0x149
web_1     | panic(0x34b4fe0, 0x50ecc90)
web_1     | 	/usr/local/go/src/runtime/panic.go:975 +0x41b
web_1     | github.com/concourse/concourse/atc.StepRecursor.VisitRetry(0x0, 0xc00026b500, 0xc00026b510, 0x0, 0x0, 0xc0007e6680, 0x0, 0x0)
web_1     | 	/src/atc/step_recursor.go:120 +0x6e
web_1     | github.com/concourse/concourse/atc.(*RetryStep).Visit(0xc0007e6680, 0x3e832e0, 0xc0004cb560, 0x0, 0x0)
web_1     | 	/src/atc/steps.go:489 +0x45
web_1     | github.com/concourse/concourse/atc.StepRecursor.VisitDo(0x0, 0xc00026b500, 0xc00026b510, 0x0, 0x0, 0xc0007e66c0, 0x0, 0x0)
web_1     | 	/src/atc/step_recursor.go:80 +0x15a
web_1     | github.com/concourse/concourse/atc.(*DoStep).Visit(0xc0007e66c0, 0x3e832e0, 0xc0004cb530, 0x0, 0x0)
web_1     | 	/src/atc/steps.go:399 +0x45
web_1     | github.com/concourse/concourse/atc/configvalidate.usedResources(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
web_1     | 	/src/atc/configvalidate/validate.go:201 +0x2dd
web_1     | github.com/concourse/concourse/atc/configvalidate.validateResourcesUnused(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
web_1     | 	/src/atc/configvalidate/validate.go:184 +0x7a
web_1     | github.com/concourse/concourse/atc/configvalidate.validateResources(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
web_1     | 	/src/atc/configvalidate/validate.go:144 +0x74a
web_1     | github.com/concourse/concourse/atc/configvalidate.Validate(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
web_1     | 	/src/atc/configvalidate/validate.go:33 +0x1e5
web_1     | github.com/concourse/concourse/atc/api/configserver.(*Server).SaveConfig(0xc0007165a0, 0x3e52ea0, 0xc000950730, 0xc000ca5700)
web_1     | 	/src/atc/api/configserver/save.go:64 +0xe68
web_1     | net/http.HandlerFunc.ServeHTTP(0xc0004c3930, 0x3e52ea0, 0xc000950730, 0xc000ca5700)
web_1     | 	/usr/local/go/src/net/http/server.go:2012 +0x44
web_1     | github.com/felixge/httpsnoop.CaptureMetrics.func1(0x3e52ea0, 0xc000950730)
web_1     | 	/go/pkg/mod/github.com/felixge/httpsnoop@v1.0.0/capture_metrics.go:30 +0x67
web_1     | github.com/felixge/httpsnoop.CaptureMetricsFn(0x3e518e0, 0xc000431dc0, 0xc0005d69d0, 0x0, 0x0, 0x0)
web_1     | 	/go/pkg/mod/github.com/felixge/httpsnoop@v1.0.0/capture_metrics.go:81 +0x3d2
web_1     | github.com/felixge/httpsnoop.CaptureMetrics(0x3dfc3c0, 0xc0004c3930, 0x3e518e0, 0xc000431dc0, 0xc000ca5700, 0x0, 0x0, 0x0)
web_1     | 	/go/pkg/mod/github.com/felixge/httpsnoop@v1.0.0/capture_metrics.go:29 +0xb3
web_1     | github.com/concourse/concourse/atc/metric.MetricsHandler.ServeHTTP(0x3e6fac0, 0xc00048cea0, 0x37d72c1, 0xa, 0x3dfc3c0, 0xc0004c3930, 0x3e518e0, 0xc000431dc0, 0xc000ca5700)
web_1     | 	/src/atc/metric/http.go:25 +0x74
web_1     | github.com/concourse/concourse/atc/api/policychecker.policyCheckingHandler.ServeHTTP(0x3e6fac0, 0xc00048cea0, 0x3dfade0, 0xc000716d20, 0x37d72c1, 0xa, 0x0, 0x0, 0x3e518e0, 0xc000431dc0, ...)
web_1     | 	/src/atc/api/policychecker/handler.go:50 +0x316
web_1     | github.com/concourse/concourse/atc/api/auth.checkAuthorizationHandler.ServeHTTP(0x3dfa9e0, 0xc00007c540, 0x3e189a0, 0x5262ef0, 0x3e518e0, 0xc000431dc0, 0xc000ca5700)
web_1     | 	/src/atc/api/auth/check_authorization_handler.go:39 +0x136
web_1     | github.com/concourse/concourse/atc/wrappa.VersionedHandler.ServeHTTP(0x37d487b, 0x9, 0x3dfa8e0, 0xc000301480, 0x3e518e0, 0xc000431dc0, 0xc000ca5700)
web_1     | 	/src/atc/wrappa/versioned_handler.go:14 +0xa7
web_1     | github.com/concourse/concourse/atc/api/accessor.(*accessorHandler).ServeHTTP(0xc00064bcb0, 0x3e518e0, 0xc000431dc0, 0xc000ca5600)
web_1     | 	/src/atc/api/accessor/handler.go:109 +0x690
web_1     | github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x3e514a0, 0xc00014b420, 0xc000ca5600)
web_1     | 	/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x2ba
web_1     | net/http.HandlerFunc.ServeHTTP(0xc0000373b0, 0x3e514a0, 0xc00014b420, 0xc000ca5600)
web_1     | 	/usr/local/go/src/net/http/server.go:2012 +0x44
web_1     | github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc000434f40, 0x3e514a0, 0xc00014b420, 0xc000ca5600)
web_1     | 	/go/pkg/mod/github.com/bmizerany/pat@v0.0.0-20170815010413-6226ea591a40/mux.go:117 +0x313
web_1     | github.com/concourse/concourse/atc/api/auth.csrfValidationHandler.ServeHTTP(0x3df5940, 0xc000434f40, 0x3e765a0, 0xc0004249a8, 0x3e514a0, 0xc00014b420, 0xc000ca5600)
web_1     | 	/src/atc/api/auth/csrf_validation_handler.go:60 +0x60b
web_1     | net/http.(*ServeMux).ServeHTTP(0xc000314840, 0x3e514a0, 0xc00014b420, 0xc000ca5600)
web_1     | 	/usr/local/go/src/net/http/server.go:2387 +0x1a6
web_1     | github.com/concourse/concourse/atc/api/auth.WebAuthHandler.ServeHTTP(0x3df9520, 0xc000314840, 0x3e765a0, 0xc0004249a8, 0x3e514a0, 0xc00014b420, 0xc000ca5600)
web_1     | 	/src/atc/api/auth/web_auth_handler.go:55 +0x300
web_1     | github.com/concourse/concourse/atc/wrappa.SecurityHandler.ServeHTTP(0x34f0fb2, 0x4, 0x3dfa860, 0xc0003e6880, 0x3e514a0, 0xc00014b420, 0xc000ca5600)
web_1     | 	/src/atc/wrappa/security_handler.go:17 +0x1af
web_1     | github.com/concourse/concourse/atc/wrappa.LoggerHandler.ServeHTTP(0x3e6fac0, 0xc00048cea0, 0x3dfb000, 0xc0003e68a0, 0x3e514a0, 0xc00014b420, 0xc000ca5500)
web_1     | 	/src/atc/wrappa/logger_handler.go:20 +0x2fb
web_1     | net/http.serverHandler.ServeHTTP(0xc00034c380, 0x3e514a0, 0xc00014b420, 0xc000ca5500)
web_1     | 	/usr/local/go/src/net/http/server.go:2807 +0x20f
web_1     | net/http.(*conn).serve(0xc0007348c0, 0x3e596e0, 0xc00058ab40)
web_1     | 	/usr/local/go/src/net/http/server.go:1895 +0x1716
web_1     | created by net/http.(*Server).Serve
web_1     | 	/usr/local/go/src/net/http/server.go:2933 +0x931
```

## Additional context

I suspect this was introduced by #5504, but maybe it was like this before

Also, it's worth noting the panic isn't fatal (i.e. doesn't take down the ATC), since Go recovers from panics in HTTP handlers

## Triaging info

* Concourse version: 6.4.0
* Did this used to work? Probably

**Comment by aoldershaw** [comment]
Now I'm thinking this could be a fatal panic if run in the `set_pipeline` step

**Comment by xtreme-sameer-vohra** [comment]
@aoldershaw chatted about this at standup and decided to triage it for 6.5 release.
