### ISSUE TITLE
Running a set_pipeline step against a file containing unexpected pipeline YML crashes ATC

### ISSUE THREAD

**Issue by mdb** [concourse/concourse#6111]
## Summary

In at least version 6.4.1, Concourse ATCs crash when a [set_pipeline](https://concourse-ci.org/jobs.html#schema.step.set-pipeline-step.set_pipeline) step is provided a YML file containing unexpected pipeline YML, such as a YML file containing a [task definition](https://concourse-ci.org/tasks.html), or even a YML file with no content.

**Update**: It appears this does not crash the ATC in versions >= 6.5.0. So far, I have only reproduced the ATC crash in version 6.4.1. However, in versions greater than 6.5.0, the job still errors and a `runtime error: invalid memory address or nil pointer dereference` is logged. For example, here is output from a `docker-compose up` performed in `master` (at commit `b5584f13bfe700b1c663a97f2e76afc9d406cd4a`):

```
web_1     | {"timestamp":"2020-10-04T11:13:46.010601527Z","level":"debug","source":"atc","message":"atc.tracker.notify.run.set-pipeline-step.starting","data":{"build":1,"job":"update-pipeline
-with-task-yml","job-id":1,"pipeline":"concourse-set-pipeline-dos","session":"24.24.2.4","step-name":"bad-pipeline"}}
web_1     | {"timestamp":"2020-10-04T11:13:46.011899176Z","level":"debug","source":"atc","message":"atc.tracker.notify.run.set-pipeline-step.no-diff","data":{"build":1,"job":"update-pipeline-
with-task-yml","job-id":1,"pipeline":"concourse-set-pipeline-dos","session":"24.24.2.4","step-name":"bad-pipeline"}}
web_1     | {"timestamp":"2020-10-04T11:13:46.014093778Z","level":"error","source":"atc","message":"atc.tracker.notify.run.panic-in-engine-build-step-run","data":{"build":1,"error":"panic in
engine build step run map[pipeline_name:concourse-set-pipeline-dos team_name:main]: runtime error: invalid memory address or nil pointer dereference","job":"update-pipeline-with-task-yml","pi
peline":"concourse-set-pipeline-dos","session":"24.24.2"}}
web_1     | {"timestamp":"2020-10-04T11:13:46.014280798Z","level":"debug","source":"atc","message":"atc.tracker.notify.run.engine-build-done","data":{"build":1,"job":"update-pipeline-with-tas
k-yml","pipeline":"concourse-set-pipeline-dos","session":"24.24.2"}}
web_1     | panic in engine build step run map[pipeline_name:concourse-set-pipeline-dos team_name:main]: runtime error: invalid memory address or nil pointer dereference
web_1     |  goroutine 2213 [running]:
web_1     | runtime/debug.Stack(0x0, 0x0, 0x0)
web_1     |     /usr/local/go/src/runtime/debug/stack.go:24 +0xa5
web_1     | github.com/concourse/concourse/atc/engine.(*engineBuild).Run.func2.1(0xc000320c80, 0xc000d70400, 0x3ba1680, 0xc000c30360, 0xc000736720)
web_1     |     /src/atc/engine/engine.go:224 +0x34c
web_1     | panic(0x35aeba0, 0x49efba0)
web_1     |     /usr/local/go/src/runtime/panic.go:975 +0x414
web_1     | github.com/concourse/concourse/atc/exec.(*SetPipelineStep).run(0xc0008c1040, 0x3b90340, 0xc00083c450, 0x3b75d80, 0xc000d70a10, 0x0, 0x0)
web_1     |     /src/atc/exec/set_pipeline_step.go:211 +0x2258
web_1     | github.com/concourse/concourse/atc/exec.(*SetPipelineStep).Run(0xc0008c1040, 0x3b90340, 0xc00083c450, 0x3b75d80, 0xc000d70a10, 0x0, 0x0)
web_1     |     /src/atc/exec/set_pipeline_step.go:70 +0x508
web_1     | github.com/concourse/concourse/atc/exec.LogErrorStep.Run(0x3b49340, 0xc0008c1040, 0x7f09001174d0, 0xc000c30660, 0x3b90340, 0xc00083c450, 0x3b75d80, 0xc000d70a10, 0x0, 0x0)
web_1     |     /src/atc/exec/log_error_step.go:34 +0xbf
web_1     | github.com/concourse/concourse/atc/exec.OnSuccessStep.Run(0x3b52c00, 0xc0009da880, 0x3b52b40, 0x4b6beb8, 0x3b90340, 0xc00083c450, 0x3b75d80, 0xc000d70a10, 0x0, 0x0)
web_1     |     /src/atc/exec/on_success.go:29 +0x76
web_1     | github.com/concourse/concourse/atc/exec.OnSuccessStep.Run(0x3b52c00, 0xc0009da8c0, 0x3b52d00, 0xc0009da8a0, 0x3b90340, 0xc00083c450, 0x3b75d80, 0xc000d70a10, 0x0, 0x0)
web_1     |     /src/atc/exec/on_success.go:39 +0x122
web_1     | github.com/concourse/concourse/atc/engine.(*engineBuild).Run.func2(0xc000320c80, 0xc000d70400, 0x3ba1680, 0xc000c30360, 0xc000736720, 0x3b90280, 0xc000095180, 0x3b52d00, 0xc0009da
8e0, 0x3b75d80, ...)
web_1     |     /src/atc/engine/engine.go:233 +0x22f
web_1     | created by github.com/concourse/concourse/atc/engine.(*engineBuild).Run
web_1     |     /src/atc/engine/engine.go:216 +0x1485
web_1     |
web_1     | {"timestamp":"2020-10-04T11:13:46.028126751Z","level":"info","source":"atc","message":"atc.tracker.notify.run.finish.errored","data":{"build":1,"error":"panic in engine build step
 run map[pipeline_name:concourse-set-pipeline-dos team_name:main]: runtime error: invalid memory address or nil pointer dereference","job":"update-pipeline-with-task-yml","pipeline":"concours
e-set-pipeline-dos","session":"24.24.2.5"}}
web_1     | {"timestamp":"2020-10-04T11:13:46.031699729Z","level":"debug","source":"atc","message":"atc.tracker.notify.run.lock.release.released","data":{"build":1,"build_id":1,"id":[1,1],"jo
b":"update-pipeline-with-task-yml","pipeline":"concourse-set-pipeline-dos","session":"24.24.2.1.2"}}
```

## Steps to reproduce

To reproduce the hard-ATC-crash in version 6.4.1 (to reproduce the slightly-different-behavior in versions `>= 6.5.0`, modify the `docker-compose.yml`'s `image: concourse/concourse:${VERSION}` accordingly)...

1. Use `docker-compose` to start a local Concourse:
    ```yaml
    version: '3'

    services:
      concourse-db:
        image: postgres
        environment:
          POSTGRES_DB: concourse
          POSTGRES_PASSWORD: concourse_pass
          POSTGRES_USER: concourse_user
          PGDATA: /database

      concourse:
        image: concourse/concourse:6.4.1
        command: quickstart
        privileged: true
        depends_on: [concourse-db]
        ports: ["8080:8080"]
        environment:
          CONCOURSE_POSTGRES_HOST: concourse-db
          CONCOURSE_POSTGRES_USER: concourse_user
          CONCOURSE_POSTGRES_PASSWORD: concourse_pass
          CONCOURSE_POSTGRES_DATABASE: concourse
          CONCOURSE_EXTERNAL_URL: http://localhost:8080
          CONCOURSE_ADD_LOCAL_USER: test:test
          CONCOURSE_MAIN_TEAM_LOCAL_USER: test
          CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
          CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
          CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
    ```

    Start Concourse on `http://localhost:8080`:

    ```
    docker-compose up -d
    ```

2. Create a `pipeline.yml` file whose `update-pipeline-with-task-yml` job attempts to `set_pipeline` a `bad-pipeline` with [this task.yml file](https://gist.github.com/mdb/ac6ae0980b268ae5ff2449fef3ab87c5), which is not expected pipeline YML:
    ```yaml
    resources:

    - name: gist
      type: git
      source:
        uri: https://gist.github.com/mdb/ac6ae0980b268ae5ff2449fef3ab87c5

    jobs:

    - name: update-pipeline-with-task-yml
      plan:
      - get: gist
      - set_pipeline: bad-pipeline
        file: gist/task.yml
    ```

3. Download `fly` from your localhost Concourse:

    ```bash
    wget \
      -O fly \
      "http://localhost:8080/api/v1/cli?arch=amd64&platform=darwin"

    chmod +x fly
    ```

4. Use your downloaded `fly` to configure and unpause a `test` pipeline:

    ```bash
    ./fly \
      --target local \
      login \
        --concourse-url http://localhost:8080 \
        --username test \
        --password test

    ./fly \
      --target local \
      set-pipeline \
        --pipeline test \
        --config pipeline.yml

    ./fly \
      --target local \
      unpause-pipeline \
        --pipeline test
    ```

5. Trigger the `test` pipeline's `update-pipeline-with-task-yml` job:

    ```bash
    ./fly \
      --target local \
      trigger-job \
        --job test/update-pipeline-with-task-yml
    ```

6. Observe that the `update-pipeline-with-task-yml` job runs for a bit but that the Concourse ATC ultimately crashes, emitting this log output:

    ```
    concourse_1     | {"timestamp":"2020-10-02T16:22:49.878856300Z","level":"info","source":"atc","message":"atc.tracker.notify.run.set-pipeline-step.initializing","data":{"build":1,"job":"update-pipeline-with-task-yml","job-id":1,"pipeline":"test","session":"23.12.2.4","step-name":"bad-pipeline"}}
    concourse_1     | panic: runtime error: invalid memory address or nil pointer dereference
    concourse_1     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x148 pc=0x18172c2]
    concourse_1     |
    concourse_1     | goroutine 1692 [running]:
    concourse_1     | github.com/concourse/concourse/atc/exec.(*SetPipelineStep).run(0xc000fcd040, 0x3965f00, 0xc000ef79e0, 0x3948a80, 0xc0011eeaf0, 0x0, 0x0)
    concourse_1     |       /tmp/build/8cf986d9/concourse/atc/exec/set_pipeline_step.go:200 +0x1362
    concourse_1     | github.com/concourse/concourse/atc/exec.(*SetPipelineStep).Run(0xc000fcd040, 0x3965f00, 0xc000ef79e0, 0x3948a80, 0xc0011eeaf0, 0x1, 0xc000e8f480)
    concourse_1     |       /tmp/build/8cf986d9/concourse/atc/exec/set_pipeline_step.go:70 +0x3ff
    concourse_1     | github.com/concourse/concourse/atc/exec.LogErrorStep.Run(0x3918c00, 0xc000fcd040, 0x7ff454744fb8, 0xc001047ce0, 0x3965f00, 0xc000ef79e0, 0x3948a80, 0xc0011eeaf0, 0xc0011eeaf0, 0x0)
    concourse_1     |       /tmp/build/8cf986d9/concourse/atc/exec/log_error_step.go:34 +0xe4
    concourse_1     | github.com/concourse/concourse/atc/exec.OnSuccessStep.Run(0x3922080, 0xc0001331e0, 0x3921fc0, 0x4d1ff38, 0x3965f00, 0xc000ef79e0, 0x3948a80, 0xc0011eeaf0, 0xc0012ef680, 0x1)
    concourse_1     |       /tmp/build/8cf986d9/concourse/atc/exec/on_success.go:29 +0x60
    concourse_1     | github.com/concourse/concourse/atc/exec.OnSuccessStep.Run(0x3922080, 0xc000133220, 0x3922180, 0xc000133200, 0x3965f00, 0xc000ef79e0, 0x3948a80, 0xc0011eeaf0, 0x3965f00, 0xc000ef79b0)
    concourse_1     |       /tmp/build/8cf986d9/concourse/atc/exec/on_success.go:39 +0xcd
    concourse_1     | github.com/concourse/concourse/atc/engine.(*engineBuild).Run.func2(0x3965e40, 0xc0005391c0, 0x3980a40, 0xc001022900, 0xc00131db80, 0xc000e96120, 0x3922180, 0xc000133240, 0x3948a80, 0xc0011eeaf0)
    concourse_1     |       /tmp/build/8cf986d9/concourse/atc/engine/engine.go:217 +0x162
    concourse_1     | created by github.com/concourse/concourse/atc/engine.(*engineBuild).Run
    concourse_1     |       /tmp/build/8cf986d9/concourse/atc/engine/engine.go:214 +0xca5
    concourse-db_1  | 2020-10-02 16:22:50.002 UTC [98] LOG:  could not receive data from client: Connection reset by peer
    concourse-db_1  | 2020-10-02 16:22:50.002 UTC [98] LOG:  unexpected EOF on client connection with an open transaction
    concourse-set-pipeline-dos_concourse_1 exited with code 2
    ```

Note, however, that when testing in versions `>= 6.5.0` on MacOS via the above-described `docker-compose up` method, it's necessary to employ the `git-resource` workaround described [in issue 6038](https://github.com/concourse/concourse/issues/6038) such that `gist.github.com` can be resolved

## Expected results

I would expect Concourse to appropriately message the user about the disliked pipeline YML. I would also expect the Concourse ATC would not crash (as occurs in only version 6.4.1) and perhaps would not log a `runtime error: invalid memory address or nil pointer dereference`.

## Actual results

The user receives no meaningful message, the job errors, and a `runtime error: invalid memory address or nil pointer dereference` is logged. In version 6.4.1, the ATC crashes.

Furthermore, when testing against `master` (I tested at commit `b5584f13bfe700b1c663a97f2e76afc9d406cd4a` using the [docker-compose.yml found in the Concourse repository](https://github.com/concourse/concourse/blob/master/docker-compose.yml)), I observed a _third_ flavor of behavior: in this scenario, the job step errors, but prints no output to the web UI and remains in the following visual state:

![image](https://user-images.githubusercontent.com/184109/95014475-216fff80-0615-11eb-8221-4049755bf59a.png)

## Additional context

My team currently runs a large Concourse installation servicing thousands of users in appoximately 450+ teams. Because of the size of our user base, we're unable to vet and trust the YML fed to `set_pipeline` across all jobs, which makes our Concourse -- and our users -- particularly vulnerable.

We did see this in production on two separate clusters, where the parent pipeline build appeared to be printing "no diff found" roughly every 10 seconds, and ATCs were continually crashing. That indicates that the NPE brings down a machine, and another one tries to schedule the build in the same way, but gets no further. Then, they are all crashing. In our case, this caused a complete outage of the ATCs.

This can _also_ be reproduced by attempting to `set_pipeline` a `file` with _no_ content.

## Triaging info

* Concourse version: I've reproduced the ATC crash with 6.4.1 but cannot reproduce the ATC crash in versions >= 6.5.0. I've reproduced the `runtime error: invalid memory address or nil pointer dereference` in version 6.6.0, as well as `master`.
* Browser (if applicable): N/A
* Did this used to work? I'm not sure, though I suspect not.

**Update**: It should be noted that in version >= 6.5.0, this appears to _not_ crash the ATC, the the job errors and the `set_pipeline` step prints the following to the web UI:

```
WARNING: the set_pipeline step is experimental and subject to change!

follow RFC #31 for updates: https://github.com/concourse/rfcs/pull/31

no diff found.
```

The following is logged:

```
web_1     | {"timestamp":"2020-10-04T11:13:46.010601527Z","level":"debug","source":"atc","message":"atc.tracker.notify.run.set-pipeline-step.starting","data":{"build":1,"job":"update-pipeline
-with-task-yml","job-id":1,"pipeline":"concourse-set-pipeline-dos","session":"24.24.2.4","step-name":"bad-pipeline"}}
web_1     | {"timestamp":"2020-10-04T11:13:46.011899176Z","level":"debug","source":"atc","message":"atc.tracker.notify.run.set-pipeline-step.no-diff","data":{"build":1,"job":"update-pipeline-
with-task-yml","job-id":1,"pipeline":"concourse-set-pipeline-dos","session":"24.24.2.4","step-name":"bad-pipeline"}}
web_1     | {"timestamp":"2020-10-04T11:13:46.014093778Z","level":"error","source":"atc","message":"atc.tracker.notify.run.panic-in-engine-build-step-run","data":{"build":1,"error":"panic in
engine build step run map[pipeline_name:concourse-set-pipeline-dos team_name:main]: runtime error: invalid memory address or nil pointer dereference","job":"update-pipeline-with-task-yml","pi
peline":"concourse-set-pipeline-dos","session":"24.24.2"}}
web_1     | {"timestamp":"2020-10-04T11:13:46.014280798Z","level":"debug","source":"atc","message":"atc.tracker.notify.run.engine-build-done","data":{"build":1,"job":"update-pipeline-with-tas
k-yml","pipeline":"concourse-set-pipeline-dos","session":"24.24.2"}}
web_1     | panic in engine build step run map[pipeline_name:concourse-set-pipeline-dos team_name:main]: runtime error: invalid memory address or nil pointer dereference
web_1     |  goroutine 2213 [running]:
web_1     | runtime/debug.Stack(0x0, 0x0, 0x0)
web_1     |     /usr/local/go/src/runtime/debug/stack.go:24 +0xa5
web_1     | github.com/concourse/concourse/atc/engine.(*engineBuild).Run.func2.1(0xc000320c80, 0xc000d70400, 0x3ba1680, 0xc000c30360, 0xc000736720)
web_1     |     /src/atc/engine/engine.go:224 +0x34c
web_1     | panic(0x35aeba0, 0x49efba0)
web_1     |     /usr/local/go/src/runtime/panic.go:975 +0x414
web_1     | github.com/concourse/concourse/atc/exec.(*SetPipelineStep).run(0xc0008c1040, 0x3b90340, 0xc00083c450, 0x3b75d80, 0xc000d70a10, 0x0, 0x0)
web_1     |     /src/atc/exec/set_pipeline_step.go:211 +0x2258
web_1     | github.com/concourse/concourse/atc/exec.(*SetPipelineStep).Run(0xc0008c1040, 0x3b90340, 0xc00083c450, 0x3b75d80, 0xc000d70a10, 0x0, 0x0)
web_1     |     /src/atc/exec/set_pipeline_step.go:70 +0x508
web_1     | github.com/concourse/concourse/atc/exec.LogErrorStep.Run(0x3b49340, 0xc0008c1040, 0x7f09001174d0, 0xc000c30660, 0x3b90340, 0xc00083c450, 0x3b75d80, 0xc000d70a10, 0x0, 0x0)
web_1     |     /src/atc/exec/log_error_step.go:34 +0xbf
web_1     | github.com/concourse/concourse/atc/exec.OnSuccessStep.Run(0x3b52c00, 0xc0009da880, 0x3b52b40, 0x4b6beb8, 0x3b90340, 0xc00083c450, 0x3b75d80, 0xc000d70a10, 0x0, 0x0)
web_1     |     /src/atc/exec/on_success.go:29 +0x76
web_1     | github.com/concourse/concourse/atc/exec.OnSuccessStep.Run(0x3b52c00, 0xc0009da8c0, 0x3b52d00, 0xc0009da8a0, 0x3b90340, 0xc00083c450, 0x3b75d80, 0xc000d70a10, 0x0, 0x0)
web_1     |     /src/atc/exec/on_success.go:39 +0x122
web_1     | github.com/concourse/concourse/atc/engine.(*engineBuild).Run.func2(0xc000320c80, 0xc000d70400, 0x3ba1680, 0xc000c30360, 0xc000736720, 0x3b90280, 0xc000095180, 0x3b52d00, 0xc0009da
8e0, 0x3b75d80, ...)
web_1     |     /src/atc/engine/engine.go:233 +0x22f
web_1     | created by github.com/concourse/concourse/atc/engine.(*engineBuild).Run
web_1     |     /src/atc/engine/engine.go:216 +0x1485
web_1     |
web_1     | {"timestamp":"2020-10-04T11:13:46.028126751Z","level":"info","source":"atc","message":"atc.tracker.notify.run.finish.errored","data":{"build":1,"error":"panic in engine build step
 run map[pipeline_name:concourse-set-pipeline-dos team_name:main]: runtime error: invalid memory address or nil pointer dereference","job":"update-pipeline-with-task-yml","pipeline":"concours
e-set-pipeline-dos","session":"24.24.2.5"}}
web_1     | {"timestamp":"2020-10-04T11:13:46.031699729Z","level":"debug","source":"atc","message":"atc.tracker.notify.run.lock.release.released","data":{"build":1,"build_id":1,"id":[1,1],"jo
b":"update-pipeline-with-task-yml","pipeline":"concourse-set-pipeline-dos","session":"24.24.2.1.2"}}
```

**Comment by taylorsilva** [comment]
I'm going to close this now. I think we can consider this fixed based on your PR.
