### ISSUE TITLE
panic: unaligned 64-bit atomic operation when running on raspberry pi 4

### ISSUE THREAD

**Issue by kristianpaul** [concourse/concourse#7149]
## Summary

After compiling concourse on Raspberry Pi 4 
## Steps to reproduce
```
git clone https://github.com/concourse/concourse.git
cd concourse
go build -gcflags=all="-N -l" -o $HOME/bin/concourse ./cmd/concourse
cd ..
source concourse_var
concourse web
```
## Expected results

Access to concourse web interface via browser

## Actual results

```
source concourse_var
concourse web
{"timestamp":"2021-06-09T20:35:54.681265784Z","level":"info","source":"atc","message":"atc.cmd.start","data":{"session":"1"}}
{"timestamp":"2021-06-09T20:35:56.012363451Z","level":"info","source":"atc","message":"atc.cmd.finish","data":{"duration":462441,"session":"1"}}
{"timestamp":"2021-06-09T20:35:56.015135023Z","level":"info","source":"tsa","message":"tsa.listening","data":{}}
{"timestamp":"2021-06-09T20:35:56.018756496Z","level":"info","source":"atc","message":"atc.listening","data":{"debug":"127.0.0.1:8079","http":"0.0.0.0:7070"}}
{"timestamp":"2021-06-09T20:35:59.652855844Z","level":"error","source":"atc","message":"atc.index.failed-to-build-template","data":{"error":"template: index.html:8:63: executing \"index.html\" at \u003casset \"main.css\"\u003e: error calling asset: open main.css: file does not exist","session":"38"}}
2021/06/09 21:35:59 http: superfluous response.WriteHeader call from github.com/felixge/httpsnoop.CaptureMetricsFn.func1.1 (capture_metrics.go:45)
{"timestamp":"2021-06-09T20:35:59.776631527Z","level":"error","source":"atc","message":"atc.index.failed-to-build-template","data":{"error":"template: index.html:8:63: executing \"index.html\" at \u003casset \"main.css\"\u003e: error calling asset: open main.css: file does not exist","session":"41"}}
2021/06/09 21:35:59 http: superfluous response.WriteHeader call from github.com/felixge/httpsnoop.CaptureMetricsFn.func1.1 (capture_metrics.go:45)
{"timestamp":"2021-06-09T20:36:02.912179708Z","level":"error","source":"atc","message":"atc.index.failed-to-build-template","data":{"error":"template: index.html:8:63: executing \"index.html\" at \u003casset \"main.css\"\u003e: error calling asset: open main.css: file does not exist","session":"44"}}
2021/06/09 21:36:02 http: superfluous response.WriteHeader call from github.com/felixge/httpsnoop.CaptureMetricsFn.func1.1 (capture_metrics.go:45)
{"timestamp":"2021-06-09T20:36:02.970671601Z","level":"error","source":"atc","message":"atc.index.failed-to-build-template","data":{"error":"template: index.html:8:63: executing \"index.html\" at \u003casset \"main.css\"\u003e: error calling asset: open main.css: file does not exist","session":"47"}}
2021/06/09 21:36:02 http: superfluous response.WriteHeader call from github.com/felixge/httpsnoop.CaptureMetricsFn.func1.1 (capture_metrics.go:45)
panic: unaligned 64-bit atomic operation

goroutine 167 [running]:
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xchg64(0x487a9dc, 0x0, 0x0, 0x2, 0x2565088)
        /usr/local/go/src/runtime/internal/atomic/asm_arm.s:248 +0x14
github.com/concourse/concourse/atc/metric.(*Counter).Delta(0x487a9dc, 0x0, 0x0)
        /mnt/home/pi/concourse/atc/metric/counter.go:18 +0x40
github.com/concourse/concourse/atc/metric.tick(0x2e95578, 0x4a1e5a0, 0x487a900)
        /mnt/home/pi/concourse/atc/metric/periodic.go:74 +0x5f8
github.com/concourse/concourse/atc/metric.PeriodicallyEmit.func1(0x4ca1b00, 0x4ca1b40, 0x0, 0x0)
        /mnt/home/pi/concourse/atc/metric/periodic.go:24 +0x1a0
github.com/tedsuo/ifrit.RunFunc.Run(0x4907668, 0x4ca1b00, 0x4ca1b40, 0x0, 0x0)
        /mnt/home/pi/go/pkg/mod/github.com/tedsuo/ifrit@v0.0.0-20180802180643-bea94bb476cc/runner.go:36 +0x3c
github.com/tedsuo/ifrit.(*process).run(0x44ef380)
        /mnt/home/pi/go/pkg/mod/github.com/tedsuo/ifrit@v0.0.0-20180802180643-bea94bb476cc/process.go:71 +0x5c
created by github.com/tedsuo/ifrit.Background
        /mnt/home/pi/go/pkg/mod/github.com/tedsuo/ifrit@v0.0.0-20180802180643-bea94bb476cc/process.go:49 +0x54
2 pi@rpi0:~$ uname -a
Linux rpi0 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux
pi@rpi0:~$ go version
go version go1.16.5 linux/arm
pi@rpi0:~$
```

## Additional context

```

cat concourse_var
export CONCOURSE_ADD_LOCAL_USER=myuser:XXXX
export CONCOURSE_MAIN_TEAM_LOCAL_USER=myuser
export CONCOURSE_SESSION_SIGNING_KEY=/mnt/home/pi/session_signing_key
export CONCOURSE_TSA_HOST_KEY=/mnt/home/pi/tsa_host_key
export CONCOURSE_TSA_AUTHORIZED_KEYS=/mnt/home/pi/authorized_worker_keys
export CONCOURSE_POSTGRES_HOST=127.0.0.1 # default
export CONCOURSE_POSTGRES_PORT=5432      # default
export CONCOURSE_POSTGRES_DATABASE=atc   # default
export CONCOURSE_POSTGRES_USER=pi
export CONCOURSE_POSTGRES_PASSWORD=XXX
export CONCOURSE_POSTGRES_SOCKET=/var/run/postgresql
export CONCOURSE_BIND_PORT=7070
```

## Triaging info

* Concourse version: 7.3.1
* Browser (if applicable):
* Did this used to work? No idea

**Comment by kristianpaul** [comment]
Seems to be related with https://github.com/golang/go/issues/36606

**Comment by mxplusb** [comment]
Have you tried using a 64-bit version of the RPi OS? https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/

**Comment by jvidalg** [comment]
Hi @kristianpaul were you able to figure it out?
Thanks

**Comment by taylorsilva** [comment]
# Issue Bankruptcy

This issue is being closed as part of 2025's **Issue Bankruptcy** declaration. [See here for details](https://blog.concourse-ci.org/posts/2025-01-06-concourse-2024-review/)

If you think this issue still has merit then feel free to open a new issue and reference this one.
