### ISSUE TITLE
fly execute crashes when using output flag

### ISSUE THREAD

**Issue by arwineap** [concourse/concourse#812]
* Concourse version: 2.5
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: aws
* Browser (if applicable): chromium (n/a)
* Did this used to work?: I *think* so

Reproduction steps:
Make a task file named `test-task.yml` with an output. I don't think the specifics of the task matter, so here is an example task
```
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest

inputs:
- name: fly-output-bug

outputs:
- name: result

run:
  path: /bin/sh
  args:
  - -c
  - echo "foo" > result/file
```

Then I can run the task as expected like this:
```
[alex@darkstar fly-output-bug]$ fly -t stg execute -c test-task.yml
executing build 13321
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6792    0  6792    0     0   104k      0 --:--:-- --:--:-- --:--:--  390k
initializing
running /bin/sh -c echo "foo" > result/file
succeeded
```
If I hijack to the build, I can see the file exists:
```
[alex@darkstar fly-output-bug]$ fly -t stg hijack -b 13321 /bin/sh
1: build id: 13321, step: fly-output-bug, type: get
2: build id: 13321, step: one-off, type: check
3: build id: 13321, step: one-off, type: task
choose a container: 3
/tmp/build/e55deab7 # cat result/file
foo
```

However, if I run the same task with an output, fly will crash:
```
[alex@darkstar fly-output-bug]$ tempdir=$(mktemp) fly -t stg execute -c test-task.yml --output result=${tempdir}
executing build 13323
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6792    0  6792    0     0   116k      0 --:--:-- --:--:-- --:--:--  288k
initializing
panic: tar extract failed (exit status 2). output: "\ngzip: stdin: unexpected end of file\n/usr/bin/tar: Child returned status 1\n/usr/bin/tar: Error is not recoverable: exiting now\n"

goroutine 9 [running]:
panic(0x808e00, 0xc4203a4070)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/concourse/fly/commands/internal/executehelpers.Download(0xa80200, 0xc420171610, 0x7fffa284c93f, 0x6, 0xc4204181c0, 0x1d, 0xc4203fccf0, 0x24, 0xc42040e2d0, 0x4d, ...)
	/tmp/build/9674af12/concourse/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:30 +0x1c3
github.com/concourse/fly/commands.(*ExecuteCommand).Execute.func2(0xa80200, 0xc420171610, 0x7fffa284c93f, 0x6, 0xc4204181c0, 0x1d, 0xc4203fccf0, 0x24, 0xc42040e2d0, 0x4d, ...)
	/tmp/build/9674af12/concourse/src/github.com/concourse/fly/commands/execute.go:106 +0x7d
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
	/tmp/build/9674af12/concourse/src/github.com/concourse/fly/commands/execute.go:110 +0x89c
```

When I hijack to the build, the file seems to exist:
```
[alex@darkstar fly-output-bug]$ fly -t stg hijack -b 13323 /bin/sh
1: build id: 13323, step: fly-output-bug, type: get
2: build id: 13323, step: one-off, type: check
3: build id: 13323, step: one-off, type: task
4: build id: 13323, step: result, type: put
choose a container: 3
/tmp/build/e55deab7 # cat result/file
foo
```

**Comment by vito** [comment]
Pretty sure this is the same as https://github.com/concourse/fly/issues/86

**Comment by chendrix** [comment]
This appears to still be broken. 

```
$fly -t ci e -c ci/build-docs.yml -x -iconcourse=. -o built-docs=/tmp/
...
+ ./scripts/build
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.9M    0     0    0 14.9M      0  4647k --:--:--  0:00:03 --:--:-- 4654k
succeeded
panic: tar extract failed (exit status 1). output: "./: Can't update time for .\ntar: Error exit delayed from previous errors.\n"

goroutine 41 [running]:
github.com/concourse/fly/commands/internal/executehelpers.Download(0x1841240, 0xc420173bb0, 0x7fff5fbff81d, 0xa, 0x7fff5fbff828, 0x4, 0xc4202d4a50, 0x24, 0xc4202ec050, 0x49, ...)
	/Users/pilot/workspace/concourse/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:30 +0x357
github.com/concourse/fly/commands.(*ExecuteCommand).Execute.func2(0x1841240, 0xc420173bb0, 0x7fff5fbff81d, 0xa, 0x7fff5fbff828, 0x4, 0xc4202d4a50, 0x24, 0xc4202ec050, 0x49, ...)
	/Users/pilot/workspace/concourse/src/github.com/concourse/fly/commands/execute.go:107 +0x7d
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
	/Users/pilot/workspace/concourse/src/github.com/concourse/fly/commands/execute.go:111 +0x82e
```

If we remove the `-o` flag it succeeds.

```
fly -t ci e -c ci/build-docs.yml -x -iconcourse=.
executing build 46250
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 56.5M    0 56.5M    0     0  4502k      0 --:--:--  0:00:12 --:--:-- 3591k
initializing
running concourse/ci/scripts/build-docs
+ BUILT_DOCS=/tmp/build/e55deab7/built-docs
+ cp -a concourse/docs/README.md concourse/docs/Staticfile concourse/docs/css concourse/docs/favicon.ico concourse/docs/fonts concourse/docs/html concourse/docs/images concourse/docs/js concourse/docs/lit concourse/docs/manifest.yml concourse/docs/scripts concourse/docs/src /tmp/build/e55deab7/built-docs
+ cd /tmp/build/e55deab7/built-docs
+ ./scripts/build
succeeded
```

**Comment by jtarchie** [comment]
There is a testflight [test](https://github.com/concourse/testflight/blob/372e1b0e31f02557675ec78757e104fd8f927651/flying/flying_test.go#L129-L155) that covers this use case.

**Comment by mhuangpivotal** [comment]
The Master Pipeline team is seeing the same issue since upgrading to Concourse 3.3.3. We were able to repro the error with the simple testflight test linked above.

**Comment by xtreme-james-thomson** [comment]
@mhuangpivotal asked for the Master Pipeline team to add more details about how we came about this problem.

We upgraded to 3.3.3 sometime last week, and our integration tests were passing Tuesday morning. 

We then did a redeploy (to change our worker sizes) Tuesday afternoon, and then after that we started seeing this issue consistently.

```
initializing
[integration_test]13:00:11 fly_execute_helper.go:127: errorText: [panic: tar extract failed (exit status 2). output: "\ngzip: stdin: unexpected end of file\n/bin/tar: Child returned status 1\n/bin/tar: Error is not recoverable: exiting now\n"

goroutine 36 [running]:
github.com/concourse/fly/commands/internal/executehelpers.Download(0xc31d40, 0xc420174370, 0x7fff240ad483, 0x1d, 0x7fff240ad4a1, 0x36, 0xc420177170, 0x24, 0xc4201707e0, 0x61, ...)
	/tmp/build/9674af12/concourse/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:30 +0x354
github.com/concourse/fly/commands.(*ExecuteCommand).Execute.func2(0xc31d40, 0xc420174370, 0x7fff240ad483, 0x1d, 0x7fff240ad4a1, 0x36, 0xc420177170, 0x24, 0xc4201707e0, 0x61, ...)
	/tmp/build/9674af12/concourse/src/github.com/concourse/fly/commands/execute.go:117 +0x7d
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
	/tmp/build/9674af12/concourse/src/github.com/concourse/fly/commands/execute.go:121 +0x90c
]
[integration_test]13:00:11 fly_execute_helper.go:128: err: [exit status 2]
```

The tests that are failing are performing fly execute against a concourse deployment (we are testing our  tasks). We usually have some inputs, run a task, and then check the outputs to make sure everything is going according to plan. So outputs are important to us! :)

Let me know if you need any more details, or if we can help debug this any further.

**Comment by xtreme-james-thomson** [comment]
Update:

@vito and @mhuangpivotal just helped us debug, it seems as our load balancer had a connection timeout of 10 seconds, and our connections were getting killed before things were finished transferring.

So it seems to have been solved in our situation. Thanks Alex and Mark!

**Comment by jtarchie** [comment]
@chendrix, it looks like you actually received a different error:

```
panic: tar extract failed (exit status 1). output: "./: Can't update time for .\ntar: Error exit delayed from previous errors.\n"
```
 as apposed to other listed here originally

```
panic: tar extract failed (exit status 2). output: "\ngzip: stdin: unexpected end of file\n/usr/bin/tar: Child returned status 1\n/usr/bin/tar: Error is not recoverable: exiting now\n"
```

It looks like it has resolved itself on our ci as @mhuangpivotal and @andrewedstrom verified it was working again.
