### ISSUE TITLE
Broken ssh key generation subcommand.

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#8945]
## Summary

Generating ssh keys is borked

## Expected results

Generated ssh keys

## Actual results

```
./concourse/bin/concourse generate-key -t ssh --bits=4096 -f foo
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
reflect.(*rtype).In(0x7fff0c4385a0?, 0x3?)
	reflect/type.go:780 +0x85
github.com/jessevdk/go-flags.(*Option).call(0xc0002f9380, 0xc00093f548)
	github.com/jessevdk/go-flags@v1.5.0/option.go:484 +0x9f
github.com/jessevdk/go-flags.(*Option).set(0xc0002f9380, 0xc00093f548)
	github.com/jessevdk/go-flags@v1.5.0/option.go:277 +0x196
github.com/jessevdk/go-flags.(*Option).setDefault(0xc0002f9380, 0x11?)
	github.com/jessevdk/go-flags@v1.5.0/option.go:290 +0x25
github.com/jessevdk/go-flags.(*Option).clearDefault(0xc0002f9380)
	github.com/jessevdk/go-flags@v1.5.0/option.go:351 +0x2be
github.com/jessevdk/go-flags.(*Parser).ParseArgs.func2(0xc00093f638?, 0x7?, 0xc0002f9380)
	github.com/jessevdk/go-flags@v1.5.0/parser.go:313 +0x31
github.com/jessevdk/go-flags.(*Parser).ParseArgs.(*Command).eachOption.func4.1(0xc000893040)
	github.com/jessevdk/go-flags@v1.5.0/command.go:281 +0x53
github.com/jessevdk/go-flags.(*Group).eachGroup(0xc000893040, 0xc00093f690)
	github.com/jessevdk/go-flags@v1.5.0/group.go:191 +0x22
github.com/jessevdk/go-flags.(*Group).eachGroup(0xc000892fa0, 0xc00093f690)
	github.com/jessevdk/go-flags@v1.5.0/group.go:194 +0x53
github.com/jessevdk/go-flags.(*Parser).ParseArgs.(*Command).eachOption.func4(0xc000012a38?)
	github.com/jessevdk/go-flags@v1.5.0/command.go:279 +0x45
github.com/jessevdk/go-flags.(*Command).eachCommand(0xc000961e80, 0xc00093f868, 0x1)
	github.com/jessevdk/go-flags@v1.5.0/command.go:288 +0x28
github.com/jessevdk/go-flags.(*Command).eachOption(...)
	github.com/jessevdk/go-flags@v1.5.0/command.go:278
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0003eb260, {0xc000152010, 0x6, 0x6})
	github.com/jessevdk/go-flags@v1.5.0/parser.go:312 +0x87f
github.com/jessevdk/go-flags.(*Parser).Parse(...)
	github.com/jessevdk/go-flags@v1.5.0/parser.go:191
main.main()
	github.com/concourse/concourse/cmd/concourse/main.go:30 +0x34b
```

## Triaging info

* Concourse version: 7.11.2
* Browser (if applicable): -
* Did this used to work? yes

**Comment by taylorsilva** [comment]
Trying to reproduce:

```
mkdir /tmp/keys-test
cd /tmp/keys-test
curl -L 'https://github.com/concourse/concourse/releases/download/v7.11.2/concourse-7.11.2-linux-amd64.tgz' concourse.tgz
tar xzf concourse.tgz
./concourse/bin/concourse generate-key -t ssh -b 4096 -f foo
```
And it worked:
![image](https://github.com/concourse/concourse/assets/4583837/08c40366-bdf2-47e3-976a-ac23db780286)

Tried again with your exact command and it still worked:
![image](https://github.com/concourse/concourse/assets/4583837/5cdd07af-96a3-4cf1-bc69-be5b7c2f3f60)

Where did you get your Concourse binary from? Are you on a different OS? I ran my commands on Linux, specifically Ubuntu 22.04

**Comment by taylorsilva** [comment]
No further info provided and no one else reporting this as an issue.

**Comment by drahnr** [comment]
Re-tried with 7.10.0 on fedora 39 x86_64, and it works :shrug:
