### ISSUE TITLE
TSA has unthreadsafe behavior and causes workers to stall

### ISSUE THREAD

**Issue by zaksoup** [concourse/concourse#933]
#Bug Report: concurrent map writes

occasionally (about once per day) our workers will disconnect and the TSA will report them as stalled. After a few hours (1-5) the workers will report as running.

Relevant Logs from groundcrew:
```
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
Timeout, server 5d0a3dfb-48d9-4746-8df6-f77f344d3fc6.concourse-cpi.concourse.concourse-cpi.bosh not responding.
Timeout, server 5d0a3dfb-48d9-4746-8df6-f77f344d3fc6.concourse-cpi.concourse.concourse-cpi.bosh not responding.
Timeout, server 5d0a3dfb-48d9-4746-8df6-f77f344d3fc6.concourse-cpi.concourse.concourse-cpi.bosh not responding.
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
Connection to 10.0.0.8 timed out while waiting to read
ssh_exchange_identification: read: Connection reset by peer
ssh: connect to host 5d0a3dfb-48d9-4746-8df6-f77f344d3fc6.concourse-cpi.concourse.concourse-cpi.bosh port 2222: Connection refused
ssh: connect to host 5d0a3dfb-48d9-4746-8df6-f77f344d3fc6.concourse-cpi.concourse.concourse-cpi.bosh port 2222: Connection refused
```

Relevant Logs from TSA:
```
fatal error: concurrent map writes

goroutine 22789981 [running]:
runtime.throw(0x809484, 0x15)
        /var/vcap/data/packages/golang/3dc24448472fa8f0783a95d2fdccb67b9503def8/src/runtime/panic.go:566 +0x95 fp=0xc5ad4896f8 sp=0xc5ad4896d8
runtime.mapassign1(0x79b000, 0xc42011b7d0, 0xc5ad489888, 0xc5ad489898)
        /var/vcap/data/packages/golang/3dc24448472fa8f0783a95d2fdccb67b9503def8/src/runtime/hashmap.go:458 +0x8ef fp=0xc5ad4897e0 sp=0xc5ad4896f8
github.com/concourse/tsa/tsacmd.(*TSACommand).configureSSHServer.func2(0x9b4d20, 0xc6ee229100, 0x9b27e0, 0xc6ee828320, 0x0, 0x20c, 0x41f)
        /var/vcap/packages/tsa/src/github.com/concourse/tsa/tsacmd/command.go:192 +0x416 fp=0xc5ad4898f8 sp=0xc5ad4897e0
golang.org/x/crypto/ssh.(*CertChecker).Authenticate(0xc420130440, 0x9b4d20, 0xc6ee229100, 0x9b27e0, 0xc6ee828320, 0x7, 0xc6ee82c4c3, 0xc6ee8282d8)
        /var/vcap/packages/tsa/src/golang.org/x/crypto/ssh/certs.go:303 +0x1f2 fp=0xc5ad489960 sp=0xc5ad4898f8
github.com/concourse/tsa/tsacmd.(*TSACommand).configureSSHServer.func3(0x9b4d20, 0xc6ee229100, 0x9b27e0, 0xc6ee828320, 0x217, 0x42a, 0x0)
        /var/vcap/packages/tsa/src/github.com/concourse/tsa/tsacmd/command.go:204 +0x52 fp=0xc5ad4899b0 sp=0xc5ad489960
golang.org/x/crypto/ssh.(*connection).serverAuthenticate(0xc6ee229100, 0xc6ee2eee70, 0x11, 0x40, 0x0)
        /var/vcap/packages/tsa/src/golang.org/x/crypto/ssh/server.go:351 +0x1ab7 fp=0xc5ad489cd8 sp=0xc5ad4899b0
golang.org/x/crypto/ssh.(*connection).serverHandshake(0xc6ee229100, 0xc6ee2eee70, 0xc4201766e0, 0xc6d29dc000, 0xc65ff4be48)
        /var/vcap/packages/tsa/src/golang.org/x/crypto/ssh/server.go:218 +0x584 fp=0xc5ad489db8 sp=0xc5ad489cd8
golang.org/x/crypto/ssh.NewServerConn(0x9b5440, 0xc6ecb318d8, 0xc4201766e0, 0x455470, 0xc4201f11e0, 0x4, 0xc65ff4bea0, 0x404f9e)
        /var/vcap/packages/tsa/src/golang.org/x/crypto/ssh/server.go:149 +0xe5 fp=0xc5ad489e20 sp=0xc5ad489db8
github.com/concourse/tsa/tsacmd.(*registrarSSHServer).handshake(0xc42013c3c0, 0x9b5320, 0xc6ee31bb00, 0x9b5440, 0xc6ecb318d8)
        /var/vcap/packages/tsa/src/github.com/concourse/tsa/tsacmd/server.go:66 +0x61 fp=0xc5ad489f78 sp=0xc5ad489e20
runtime.goexit()
        /var/vcap/data/packages/golang/3dc24448472fa8f0783a95d2fdccb67b9503def8/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc5ad489f80 sp=0xc5ad489f78
created by github.com/concourse/tsa/tsacmd.(*registrarSSHServer).Serve
        /var/vcap/packages/tsa/src/github.com/concourse/tsa/tsacmd/server.go:61 +0x231

goroutine 1 [chan receive, 983 minutes]:
github.com/concourse/tsa/tsacmd.(*TSACommand).Execute(0xc42014a3c0, 0xc42016e000, 0x0, 0x18, 0x0, 0x0)
        /var/vcap/packages/tsa/src/github.com/concourse/tsa/tsacmd/command.go:56 +0xf5
main.main()
        /var/vcap/packages/tsa/src/github.com/concourse/tsa/cmd/tsa/main.go:23 +0xe4

goroutine 17 [syscall, 983 minutes, locked to thread]:
runtime.goexit()
        /var/vcap/data/packages/golang/3dc24448472fa8f0783a95d2fdccb67b9503def8/src/runtime/asm_amd64.s:2086 +0x1

goroutine 6 [select, 983 minutes]:
github.com/concourse/tsa/tsacmd.serverRunner.Run(0x9b5320, 0xc42013c180, 0xc42013c3c0, 0xc42011cd60, 0xc, 0xc42005a1e0, 0xc42005a240, 0xe, 0xc4)
        /var/vcap/packages/tsa/src/github.com/concourse/tsa/tsacmd/server_runner.go:37 +0x239
github.com/concourse/tsa/tsacmd.(*serverRunner).Run(0xc42011ba10, 0xc42005a1e0, 0xc42005a240, 0x4333a8, 0x8373f8)
        <autogenerated>:3 +0x82
github.com/tedsuo/ifrit.(*process).run(0xc42004c300)
        /var/vcap/packages/tsa/src/github.com/tedsuo/ifrit/process.go:71 +0x49
created by github.com/tedsuo/ifrit.Background
        /var/vcap/packages/tsa/src/github.com/tedsuo/ifrit/process.go:49 +0x14e

goroutine 18 [syscall, 983 minutes]:
os/signal.signal_recv(0x0)
        /var/vcap/data/packages/golang/3dc24448472fa8f0783a95d2fdccb67b9503def8/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /var/vcap/data/packages/golang/3dc24448472fa8f0783a95d2fdccb67b9503def8/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /var/vcap/data/packages/golang/3dc24448472fa8f0783a95d2fdccb67b9503def8/src/os/signal/signal_unix.go:28 +0x41
```

* Concourse version: 2.7.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Did this used to work: Never on Concourse 2.5.1 or greater on GCP

**Comment by zaksoup** [comment]
from @mariash 
> sounds like this maybe is not thread-safe 
> https://github.com/concourse/tsa/blob/master/tsacmd/command.go#L192

**Comment by beyhan** [comment]
As workaround for now would it help if a stalled worker is restarted/redeployed?

**Comment by vito** [comment]
@beyhan possibly, the issue comes in when multiple workers register at the same time
